### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json" failed.

### ISSUE THREAD

**Issue by monkeyman09** [RatScanner/RatScanner#101]
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json" failed.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\wendi\Downloads\rat scanner\Data\items.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
```
<details>
<summary>Log</summary>

```
[00:37:27.9016210] > [Info]  ----- RatScanner 2.7.0 -----
[00:37:27.9065950] > [Info]  Starting RatScanner...
[00:37:27.9066487] > [Info]  Loading config...
[00:37:27.9311705] > [Info]  Loading item data...
[00:37:27.9379700] > [Info]  Loading resource "RSItemDataVersion"...
[00:37:28.3265948] > [Info]  A new item data version is available: 20210630
[00:37:28.3266043] > [Info]  Loading resource "RSItemDataLink"...
[00:37:28.4598690] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[00:37:29.9993438] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json" failed.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\wendi\Downloads\rat scanner\Data\items.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)

```
</details>

**Comment by Blightbuster** [comment]
Hey, please try starting rat scanner as administrator. Also could you please verify that the path `C:\Users\wendi\Downloads\rat scanner\Data\` exists?

**Comment by Blightbuster** [comment]
Closing due to inactivity.
If the issue persists, comment and I will reopen it.
