### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\domib\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by Miicky777** [RatScanner/RatScanner#105]
**Error**
Could not find dynamic correlation data at: C:\Users\domib\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[13:59:21.9258913] > [Info]  ----- RatScanner 2.7.0 -----
[13:59:21.9309956] > [Info]  Starting RatScanner...
[13:59:21.9311476] > [Info]  Loading config...
[13:59:21.9570273] > [Info]  Loading item data...
[13:59:21.9634043] > [Info]  Loading resource "RSItemDataVersion"...
[13:59:25.8283851] > [Info]  Loading progress data...
[13:59:29.1205397] > [Info]  Loading price data...
[13:59:30.5831029] > [Info]  Setting default item...
[13:59:30.5836053] > [Info]  Initializing name scan...
[13:59:30.5838848] > [Info]  Loading OCR data...
[13:59:30.6950588] > [Info]  Initializing icon scan...
[13:59:30.6959641] > [Info]  Loading static icons...
[13:59:30.8045576] > [Info]  Loaded 1197/1197 icons successfully.
[13:59:30.8055635] > [Info]  Loading static correlation data...
[13:59:30.8132882] > [Info]  Loading dynamic correlation data...
[13:59:30.8291008] > [Error] Could not find dynamic correlation data at: C:\Users\domib\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlT
```
</details>

**Comment by Blightbuster** [comment]
Have a look here:
https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#could-not-find-dynamic-correlation-data-at-

Please comment if this doesn't solve the issue and I will reopen the issue.
