### ISSUE TITLE
Unhandled exception in RatScanner 2.7.0

### ISSUE THREAD

**Issue by SavvySloth** [RatScanner/RatScanner#108]
**Error**
Unhandled exception in RatScanner 2.7.0
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The process cannot access the file 'D:\Users\*username*\Documents\RatScanner\Log.txt' because it is being used by another process.)
 ---> System.IO.IOException: The process cannot access the file 'D:\Users\*username*\Documents\RatScanner\Log.txt' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.AppendAllText(String path, String contents, Encoding 
```
<details>
<summary>Log</summary>

```
[15:51:27.1849002] > [Info]  ----- RatScanner 2.7.0 -----
[15:51:27.1919426] > [Info]  Starting RatScanner...
[15:51:27.1919601] > [Info]  Loading config...
[15:51:27.3330583] > [Info]  Loading item data...
[15:51:27.4393067] > [Info]  Loading resource "RSItemDataVersion"...
[15:51:30.8188038] > [Info]  Loading TarkovTracker...
[15:51:32.6935848] > [Info]  Loading progress data...
[15:51:33.1486011] > [Info]  Loading price data...
[15:51:33.8168617] > [Info]  Setting default item...
[15:51:33.8175560] > [Info]  Initializing name scan...
[15:51:33.8179963] > [Info]  Loading OCR data...
[15:51:34.5178826] > [Info]  Initializing icon scan...
[15:51:34.5192458] > [Info]  Loading static icons...
[15:51:39.9225225] > [Info]  Loaded 1197/1197 icons successfully.
[15:51:39.9235436] > [Info]  Loading static correlation data...
[15:51:39.9596764] > [Info]  Loading dynamic correlation data...
[15:51:40.0025183] > [Info]  Loading dynamic icons...
[15:51:40.3669695] > [Info]  Loaded 1496/1496 icons successfully.
[15:51:40.3691749] > [Info]  Initializing file watcher for icon cache...
[15:51:40.3735082] > [Info]  Prewarming name tool tip...
[15:51:40.6887784] > [Info]  Prewarming icon tool tip...
[15:51:40.7482064] > [Info]  Initializing hotkey manager...
[15:51:40.7509228] > [Info]  Checking for new updates...
[15:51:40.7511526] > [Info]  Loading resource "RSClientVersion"...
[15:51:41.0715262] > [Info]  Setting up data update routines...
[15:51:41.0715413] > [Info]  Ready!
[15:51:41.2307089] > [Info]  Loading resource "RSPatreonLink"...
[15:51:41.5502301] > [Info]  Loading resource "RSDiscordLink"...
[15:51:41.8711578] > [Info]  Loading resource "RSGithubLink"...
[15:51:55.2711582] > [Warning] Could not find icon key for:
Id: 5a957c3fa2750c00137fa5f7
Mod: 
Mod: 
Mod: 
Mod: 
[15:52:02.9177515] > [Warning] Could not find icon key for:
Id: 5a9548c9159bd400133e97b3
Mod: 
Mod: 
[15:54:29.9071439] > [Info]  Loading dynamic correlation data...
[15:54:29.9218650] > [Info]  Loading dynamic icons...
[15:54:29.9246874] > [Info]  Loading dynamic icons...
[15:54:30.0408568] > [Info]  Loaded 1497/1497 icons successfully.
[15:54:30.0436516] > [Info]  Loading dynamic correlation data...
[15:54:30.0646158] > [Info]  Loading dynamic icons...
[15:54:30.1863336] > [Info]  Loaded 1500/1500 icons successfully.
[15:54:30.1883919] > [Info]  Loading dynamic correlation data...
[15:54:30.2046730] > [Info]  Loading dynamic icons...
[15:54:30.3271119] > [Info]  Loaded 1502/1502 icons successfully.
[15:54:30.3293548] > [Info]  Loading dynamic correlation data...
[15:54:30.3427797] > [Info]  Loading dynamic icons...
[15:54:30.4602869] > [Info]  Loaded 1503/1503 icons successfully.
[15:54:30.4622905] > [Info]  Loading dynamic correlation data...
[15:54:30.4630366] > [Info]  Dynamic correlation data already up to date
[15:54:30.4631032] > [Info]  Loading dynamic correlation data...
[15:54:30.4720970] > [Info]  Dynamic correlation data already up to date
[15:54:30.4721937] > [Info]  Loading
```
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.1.0](https://github.com/RatScanner/RatScanner/releases/tag/v3.1.0).
Please comment if this issue persists and I will reopen it.
