### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\uhigh\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by FAesthetic** [RatScanner/RatScanner#109]
**Error**
Could not find dynamic correlation data at: C:\Users\uhigh\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[17:42:30.5003988] > [Info]  ----- RatScanner 2.7.0 -----
[17:42:30.5062044] > [Info]  Starting RatScanner...
[17:42:30.5062679] > [Info]  Loading config...
[17:42:30.5327234] > [Info]  Loading item data...
[17:42:30.5400127] > [Info]  Loading resource "RSItemDataVersion"...
[17:42:33.5427188] > [Info]  Loading progress data...
[17:42:33.9460219] > [Info]  Loading price data...
[17:42:34.5953291] > [Info]  Setting default item...
[17:42:34.5959372] > [Info]  Initializing name scan...
[17:42:34.5967916] > [Info]  Loading OCR data...
[17:42:34.7455612] > [Info]  Initializing icon scan...
[17:42:34.7470863] > [Info]  Loading static icons...
[17:42:34.8918812] > [Info]  Loaded 1197/1197 icons successfully.
[17:42:34.8931737] > [Info]  Loading static correlation data...
[17:42:34.9052502] > [Info]  Loading dynamic correlation data...
[17:42:34.9390272] > [Error] Could not find dynamic correlation data at: C:\Users\uhigh\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlT
```
</details>

**Comment by Blightbuster** [comment]
Please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#could-not-find-dynamic-correlation-data-at-)

If this didnt resolve the issue, please comment and I will reopen it.
