### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\J2787\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by j278787** [RatScanner/RatScanner#110]
**Error**
Could not find dynamic correlation data at: C:\Users\J2787\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[16:35:44.8283389] > [Info]  ----- RatScanner 2.7.0 -----
[16:35:44.8347034] > [Info]  Starting RatScanner...
[16:35:44.8347935] > [Info]  Loading config...
[16:35:44.8381120] > [Warning] Config version (-1) is not supported!
[16:35:45.2825553] > [Info]  Loading item data...
[16:35:45.4328110] > [Info]  Loading resource "RSItemDataVersion"...
[16:35:46.7048357] > [Info]  A new item data version is available: 20210630
[16:35:46.7048749] > [Info]  Loading resource "RSItemDataLink"...
[16:35:46.9814484] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[16:35:51.4135809] > [Info]  Loading progress data...
[16:35:51.9991913] > [Info]  Loading price data...
[16:35:52.6273421] > [Info]  Setting default item...
[16:35:52.6278962] > [Info]  Initializing name scan...
[16:35:52.6282138] > [Info]  Loading OCR data...
[16:35:52.7550946] > [Info]  Initializing icon scan...
[16:35:52.7634863] > [Info]  Loading static icons...
[16:35:53.3084178] > [Info]  Loaded 1197/1197 icons successfully.
[16:35:53.3096189] > [Info]  Loading static correlation data...
[16:35:53.3487898] > [Info]  Loading dynamic correlation data...
[16:35:53.6120125] > [Error] Could not find dynamic correlation data at: C:\Users\J2787\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at S
```
</details>

**Comment by Blightbuster** [comment]
Please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#could-not-find-dynamic-correlation-data-at-)

If this didnt resolve the issue, please comment and I will reopen it.
