### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\J2787\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by j278787** [RatScanner/RatScanner#111]
**Error**
Could not find dynamic correlation data at: C:\Users\J2787\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[16:38:44.5321956] > [Info]  ----- RatScanner 2.7.0 -----
[16:38:44.5386969] > [Info]  Starting RatScanner...
[16:38:44.5388315] > [Info]  Loading config...
[16:38:44.5424802] > [Warning] Config version (-1) is not supported!
[16:38:45.0369658] > [Info]  Loading item data...
[16:38:45.1770346] > [Info]  Loading resource "RSItemDataVersion"...
[16:38:46.3161467] > [Info]  A new item data version is available: 20210630
[16:38:46.3161623] > [Info]  Loading resource "RSItemDataLink"...
[16:38:46.6027790] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[16:38:51.1877034] > [Info]  Loading progress data...
[16:38:51.5592306] > [Info]  Loading price data...
[16:38:52.1551940] > [Info]  Setting default item...
[16:38:52.1557705] > [Info]  Initializing name scan...
[16:38:52.1560861] > [Info]  Loading OCR data...
[16:38:52.3042964] > [Info]  Initializing icon scan...
[16:38:52.3120529] > [Info]  Loading static icons...
[16:38:52.5608289] > [Info]  Loaded 1197/1197 icons successfully.
[16:38:52.5621288] > [Info]  Loading static correlation data...
[16:38:52.5967879] > [Info]  Loading dynamic correlation data...
[16:38:52.8394675] > [Error] Could not find dynamic correlation data at: C:\Users\J2787\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at S
```
</details>

**Comment by Blightbuster** [comment]
#110
