### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\grubb\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by cgrubbers** [RatScanner/RatScanner#112]
**Error**
Could not find dynamic correlation data at: C:\Users\grubb\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[19:10:13.9794861] > [Info]  ----- RatScanner 2.7.0 -----
[19:10:13.9837653] > [Info]  Starting RatScanner...
[19:10:13.9838115] > [Info]  Loading config...
[19:10:14.0099203] > [Info]  Loading item data...
[19:10:14.0168518] > [Info]  Loading resource "RSItemDataVersion"...
[19:10:16.3978983] > [Info]  Loading progress data...
[19:10:16.5954102] > [Info]  Loading price data...
[19:10:16.8396275] > [Info]  Setting default item...
[19:10:16.8399814] > [Info]  Initializing name scan...
[19:10:16.8401943] > [Info]  Loading OCR data...
[19:10:16.9438566] > [Info]  Initializing icon scan...
[19:10:16.9447676] > [Info]  Loading static icons...
[19:10:17.0319794] > [Info]  Loaded 1197/1197 icons successfully.
[19:10:17.0328152] > [Info]  Loading static correlation data...
[19:10:17.0442175] > [Info]  Loading dynamic correlation data...
[19:10:17.0558441] > [Error] Could not find dynamic correlation data at: C:\Users\grubb\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlT
```
</details>

**Comment by Blightbuster** [comment]
Please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#could-not-find-dynamic-correlation-data-at-)

If this didnt resolve the issue, please comment and I will reopen it.
