### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\Marvin\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by marvk** [RatScanner/RatScanner#114]
I've just received a crash on startup with the following error. The issue persists even after trying to restart.

**Error**
Could not find dynamic correlation data at: C:\Users\Marvin\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[10:54:54.9084939] > [Info]  ----- RatScanner 2.7.0 -----
[10:54:54.9128466] > [Info]  Starting RatScanner...
[10:54:54.9129098] > [Info]  Loading config...
[10:54:54.9340437] > [Info]  Loading item data...
[10:54:54.9391679] > [Info]  Loading resource "RSItemDataVersion"...
[10:54:57.3563081] > [Info]  Loading TarkovTracker...
[10:54:58.8579534] > [Info]  Loading progress data...
[10:54:59.0060131] > [Info]  Loading price data...
[10:54:59.6385850] > [Info]  Setting default item...
[10:54:59.6390362] > [Info]  Initializing name scan...
[10:54:59.6392499] > [Info]  Loading OCR data...
[10:54:59.7109105] > [Info]  Initializing icon scan...
[10:54:59.7118428] > [Info]  Loading static icons...
[10:54:59.7647969] > [Info]  Loaded 1197/1197 icons successfully.
[10:54:59.7656174] > [Info]  Loading static correlation data...
[10:54:59.7722842] > [Info]  Loading dynamic correlation data...
[10:54:59.7827295] > [Error] Could not find dynamic correlation data at: C:\Users\Marvin\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime
```
</details>

**Comment by Blightbuster** [comment]
Please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#could-not-find-dynamic-correlation-data-at-)

If this didnt resolve the issue, please comment and I will reopen it.
