### ISSUE TITLE
Could not find icon folder at: C:\Users\CheatR\Desktop\RatScanner-master\publish\Data\name

### ISSUE THREAD

**Issue by attHD** [RatScanner/RatScanner#116]
**Error**
Could not find icon folder at: C:\Users\CheatR\Desktop\RatScanner-master\publish\Data\name
<details>
<summary>Log</summary>

```
[20:24:21.0013621] > [Info]  ----- RatScanner 2.7.0 -----
[20:24:21.0080171] > [Info]  Starting RatScanner...
[20:24:21.0080924] > [Info]  Loading config...
[20:24:21.0452306] > [Info]  Loading item data...
[20:24:21.0544315] > [Info]  Loading resource "RSItemDataVersion"...
[20:24:24.8106878] > [Info]  Loading progress data...
[20:24:24.9997457] > [Info]  Loading price data...
[20:24:25.7276959] > [Info]  Setting default item...
[20:24:25.7284079] > [Info]  Initializing name scan...
[20:24:25.7287975] > [Info]  Loading OCR data...
[20:24:25.8113761] > [Info]  Initializing icon scan...
[20:24:25.8125351] > [Info]  Loading static icons...
[20:24:25.8287905] > [Error] Could not find icon folder at: C:\Users\CheatR\Desktop\RatScanner-master\publish\Data\name
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadStaticIcons()
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo,
```
</details>

**Comment by Blightbuster** [comment]
Hey, it looks like your trying to build the source files. If you only want to use rat scanner and not modify it, you can download the compiled version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).
