### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\darkn\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by Nevelke** [RatScanner/RatScanner#117]
**Error**
Could not find dynamic correlation data at: C:\Users\darkn\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[14:26:39.6458362] > [Info]  ----- RatScanner 2.7.0 -----
[14:26:39.6507346] > [Info]  Starting RatScanner...
[14:26:39.6508312] > [Info]  Loading config...
[14:26:39.6820624] > [Info]  Loading item data...
[14:26:39.6888948] > [Info]  Loading resource "RSItemDataVersion"...
[14:26:42.5931763] > [Info]  Loading progress data...
[14:26:42.9910440] > [Info]  Loading price data...
[14:26:43.7032278] > [Info]  Setting default item...
[14:26:43.7036937] > [Info]  Initializing name scan...
[14:26:43.7039626] > [Info]  Loading OCR data...
[14:26:43.8206051] > [Info]  Initializing icon scan...
[14:26:43.8220083] > [Info]  Loading static icons...
[14:26:43.9299336] > [Info]  Loaded 1197/1197 icons successfully.
[14:26:43.9309863] > [Info]  Loading static correlation data...
[14:26:43.9445636] > [Info]  Loading dynamic correlation data...
[14:26:43.9591753] > [Error] Could not find dynamic correlation data at: C:\Users\darkn\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlT
```
</details>

**Comment by Blightbuster** [comment]
Please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#could-not-find-dynamic-correlation-data-at-)

If this didnt resolve the issue, please comment and I will reopen it.
