### ISSUE TITLE
Index was outside of the bounds of the array. (post patch 0.12.11.2.13615)

### ISSUE THREAD

**Issue by ArkahnX** [RatScanner/RatScanner#118]
1. Trying to launch RatScanner while tarkov is open, or while it was closed, the app begins to load, then the dialogue box shown appears.
2. Error dialogue box:
![image](https://user-images.githubusercontent.com/1167959/128941569-1ab2f187-8c95-4a67-8972-22481646477a.png)

**Additional context**
I've tried letting all of the vendors load their images post patch.
Tarkov: 0.12.11.2.13615
RatScanner: 2.8.0 Draft

**Log file content**
```
[22:02:45.4950523] > [Info]  ----- RatScanner 2.7.0 -----
[22:02:45.5018709] > [Info]  Starting RatScanner...
[22:02:45.5019320] > [Info]  Prewarming name tool tip...
[22:02:46.0641177] > [Info]  Prewarming icon tool tip...
[22:02:46.1320864] > [Info]  Loading config...
[22:02:46.1492031] > [Info]  Loading item data...
[22:02:46.1590680] > [Info]  Loading resource "RSItemDataVersion"...
[22:02:48.5506699] > [Error] Index was outside the bounds of the array.
 -------------------- 
 System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RatStash.Extensions.Split(String str, String separator, Boolean reverse)
   at RatStash.CacheIndexParser.DeserializeItem(String serializedItem)
   at RatStash.CacheIndexParser.Parse(String filepath)
   at RatStash.Database.ParseItemCacheIndex(String filepath)
   at RatEye.IconManager.LoadDynamicCorrelationData()
   at RatEye.IconManager.LoadDynamicIcons()
   at RatEye.IconManager..ctor(Config overrideConfig)
   at RatEye.Config.Apply()
   at RatScanner.RatScannerMain.SetupRatEye()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
[22:02:49.3588321] > [Info]  Loading progress data...
[22:02:49.5627300] > [Info]  Loading price data...
[22:02:50.1031051] > [Info]  Setting default item...
[22:02:50.1037761] > [Info]  Initializing RatEye...
[22:02:52.2273834] > [Error] Index was outside the bounds of the array.
 -------------------- 
 System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RatStash.Extensions.Split(String str, String separator, Boolean reverse)
   at RatStash.CacheIndexParser.DeserializeItem(String serializedItem)
   at RatStash.CacheIndexParser.Parse(String filepath)
   at RatStash.Database.ParseItemCacheIndex(String filepath)
   at RatEye.IconManager.LoadDynamicCorrelationData()
   at RatEye.IconManager.LoadDynamicIcons()
   at RatEye.IconManager..ctor(Config overrideConfig)
   at RatEye.Config.Apply()
   at RatScanner.RatScannerMain.SetupRatEye()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()

```

**Comment by Blightbuster** [comment]
Fixed in [v2.8.0](https://github.com/RatScanner/RatScanner/releases/tag/v2.8.0)
