### ISSUE TITLE
Unhandled exception in RatScanner 2.8.2

### ISSUE THREAD

**Issue by shortywz** [RatScanner/RatScanner#120]
**Error**
Unhandled exception in RatScanner 2.8.2
```
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at RatStash.CacheHashIndexParser.Parse(String filepath)
   at RatEye.IconManager.LoadDynamicCorrelationData()
   at RatEye.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous l
```
<details>
<summary>Log</summary>

```
[02:34:51.3373593] > [Info]  ----- RatScanner 2.8.2 -----
[02:34:51.3446742] > [Info]  Starting RatScanner...
[02:34:51.3448305] > [Info]  Prewarming name tool tip...
[02:34:51.5056985] > [Info]  Prewarming icon tool tip...
[02:34:51.5347440] > [Info]  Checking for new updates...
[02:34:51.5454746] > [Info]  Loading resource "RSClientVersion"...
[02:34:51.8229125] > [Info]  Loading config...
[02:34:51.8310705] > [Info]  Loading item data...
[02:34:51.8327236] > [Info]  Loading resource "RSItemDataVersion"...
[02:34:51.9362911] > [Info]  A new item data version is available: 20210630
[02:34:51.9363009] > [Info]  Loading resource "RSItemDataLink"...
[02:34:52.0416604] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[02:34:54.5178866] > [Info]  Loading TarkovTracker...
[02:34:55.2348967] > [Info]  Loading progress data...
[02:34:55.4120622] > [Info]  Loading price data...
[02:34:55.6472986] > [Info]  Setting default item...
[02:34:55.6476481] > [Info]  Initializing RatEye...
[02:34:58.2907983] > [Info]  Initializing hotkey manager...
[02:34:58.2935989] > [Info]  Setting up data update routines...
[02:34:58.2936175] > [Info]  Ready!
[02:34:58.5629212] > [Info]  Loading resource "RSPatreonLink"...
[02:34:58.6726301] > [Info]  Loading resource "RSDiscordLink"...
[02:34:58.7736362] > [Info]  Loading resource "RSGithubLink"...
[02:44:58.3155834] > [Info]  Refreshing TarkovTracker DB...
[02:54:58.7124108] > [Info]  Refreshing TarkovTracker DB...
[03:04:59.2407526] > [Info]  Refreshing TarkovTracker DB...
[03:15:03.3819322] > [Info]  Refreshing TarkovTracker DB...
[03:23:25.9514713] > [Error] Unhandled exception in RatScanner 2.8.2
 -------------------- 
 Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at RatStash.CacheHashIndexParser.Parse(String filepath)
   at RatEye.IconManager.LoadDynamicCorrelationData()
   at RatEye.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting, fixed in v2.8.3
