### ISSUE TITLE
Loading of resource "RSClientVersion" failed.

### ISSUE THREAD

**Issue by minsu-kim-digipen** [RatScanner/RatScanner#121]
**Error**
Loading of resource "RSClientVersion" failed.
```
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
```
<details>
<summary>Log</summary>

```
[10:32:19.1308499] > [Info]  ----- RatScanner 2.8.2 -----
[10:32:19.1374851] > [Info]  Starting RatScanner...
[10:32:19.1375549] > [Info]  Prewarming name tool tip...
[10:32:19.3269984] > [Info]  Prewarming icon tool tip...
[10:32:19.3898155] > [Info]  Checking for new updates...
[10:32:19.4023712] > [Info]  Loading resource "RSClientVersion"...
[10:32:50.6172452] > [Error] Loading of resource "RSClientVersion" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
[10:32:57.2143353] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Hey, thanks for reporting.
Could you try again now and report back if you still got the issue?

**Comment by minsu-kim-digipen** [comment]
Sorry for that, I re-downloaded program just before so I couldn't report back.
If I have same issue, I will report back immediately.
