### ISSUE TITLE
Loading of resource "RSPatreonLink" failed.

### ISSUE THREAD

**Issue by minsu-kim-digipen** [RatScanner/RatScanner#123]
**Error**
Loading of resource "RSPatreonLink" failed.
```
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
```
<details>
<summary>Log</summary>

```
[05:40:18.6207147] > [Info]  ----- RatScanner 2.8.3 -----
[05:40:18.6256450] > [Info]  Starting RatScanner...
[05:40:18.6257176] > [Info]  Prewarming name tool tip...
[05:40:18.7628902] > [Info]  Prewarming icon tool tip...
[05:40:18.8130153] > [Info]  Checking for new updates...
[05:40:18.8229507] > [Info]  Loading resource "RSClientVersion"...
[05:40:20.1270206] > [Info]  Loading config...
[05:40:20.1386467] > [Info]  Loading item data...
[05:40:20.1405022] > [Info]  Loading resource "RSItemDataVersion"...
[05:40:23.1069380] > [Info]  Loading progress data...
[05:40:23.7910518] > [Info]  Loading price data...
[05:40:25.0756390] > [Info]  Setting default item...
[05:40:25.0763235] > [Info]  Initializing RatEye...
[05:40:27.6987037] > [Info]  Initializing hotkey manager...
[05:40:27.7013441] > [Info]  Setting up data update routines...
[05:40:27.7014789] > [Info]  Ready!
[05:40:27.8748604] > [Info]  Loading resource "RSPatreonLink"...
[05:40:58.5158447] > [Error] Loading of resource "RSPatreonLink" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
[05:40:58.6003511] > [Info]  Loading resource "RSDiscordLink"...
[05:41:04.4785417] > [Info]  Loading resource "RSGithubLink"...
[05:41:20.5835558] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by minsu-kim-digipen** [comment]
Is this a temporary error?

**Comment by Blightbuster** [comment]
Sorry I didnt have time yet to investigate it. But yeah it's most likely a temporary error. Are you getting these error on a consistent scale?

**Comment by minsu-kim-digipen** [comment]
Not at all. Thanks for answering!
