### ISSUE TITLE
Loading of market data failed. System.Net.WebException: No such host is known (Exception on internet connection loss)

### ISSUE THREAD

**Issue by gunstarpl** [RatScanner/RatScanner#126]
**Error**
Loading of market data failed.
System.Net.WebException: No such host is known. No such host is known.
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetMarketDB(Language language)
<details>
<summary>Log</summary>

```
[08:18:22.7198603] > [Info]  ----- RatScanner 2.8.4 -----
[08:18:22.7241258] > [Info]  Starting RatScanner...
[08:18:22.7241932] > [Info]  Prewarming name tool tip...
[08:18:22.8213096] > [Info]  Prewarming icon tool tip...
[08:18:22.8481242] > [Info]  Checking for new updates...
[08:18:22.8542413] > [Info]  Loading resource "RSClientVersion"...
[08:18:23.4839787] > [Info]  Loading config...
[08:18:23.4922763] > [Info]  Loading item data...
[08:18:23.4930667] > [Info]  Loading resource "RSItemDataVersion"...
[08:18:23.8623187] > [Info]  A new item data version is available: 20210630
[08:18:23.8623510] > [Info]  Loading resource "RSItemDataLink"...
[08:18:24.2359185] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[08:18:27.9083899] > [Info]  Loading TarkovTracker...
[08:18:28.8990958] > [Info]  Loading progress data...
[08:18:29.4065001] > [Info]  Loading price data...
[08:18:30.1748018] > [Info]  Setting default item...
[08:18:30.1752034] > [Info]  Initializing RatEye...
[08:18:32.2934585] > [Info]  Initializing hotkey manager...
[08:18:32.2959237] > [Info]  Setting up data update routines...
[08:18:32.2959409] > [Info]  Ready!
[08:18:32.4407899] > [Info]  Loading resource "RSPatreonLink"...
[08:18:32.8127152] > [Info]  Loading resource "RSDiscordLink"...
[08:18:33.1874996] > [Info]  Loading resource "RSGithubLink"...
[08:28:32.2989014] > [Info]  Refreshing TarkovTracker DB...
[08:38:32.8053392] > [Info]  Refreshing TarkovTracker DB...
[08:48:33.3666090] > [Info]  Refreshing TarkovTracker DB...
[08:58:33.8589968] > [Info]  Refreshing TarkovTracker DB...
[09:08:34.3654306] > [Info]  Refreshing TarkovTracker DB...
[09:18:32.3131783] > [Info]  Refreshing Market DB...
[09:18:32.3200238] > [Error] Loading of market data failed.
System.Net.WebException: No such host is known. No such host is known.
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAs
```
</details>

Lost connection to internet while RatScanner was open. Should propably handle connection errors like this more gracefully if possible.

**Comment by DysektAI** [comment]
Closing as a duplicate of https://github.com/RatScanner/RatScanner/issues/519.

The body is a DNS/connectivity failure (`No such host is known` while loading market data). That network class is already tracked under #519. The title asks not to surface connection errors as crashes; tracking that product behavior with the DNS/network reports is cleaner than a separate stale auto-report.
