### ISSUE TITLE
Loading of quest data failed.

### ISSUE THREAD

**Issue by liweitong1997** [RatScanner/RatScanner#129]
**Error**
Loading of quest data failed.
```
System.Net.WebException: 由于目标计算机积极拒绝，无法连接。 由于目标计算机积极拒绝，无法连接。
 ---> System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken c
```
<details>
<summary>Log</summary>

```
[06:23:08.0706076] > [Info]  ----- RatScanner 2.8.6 -----
[06:23:08.0767259] > [Info]  Starting RatScanner...
[06:23:08.0767727] > [Info]  Prewarming name tool tip...
[06:23:08.1776210] > [Info]  Prewarming icon tool tip...
[06:23:08.2039016] > [Info]  Checking for new updates...
[06:23:08.2101276] > [Info]  Loading resource "RSClientVersion"...
[06:23:10.6700699] > [Info]  Loading config...
[06:23:10.6725776] > [Warning] Config version (-1) is not supported!
[06:23:10.6792086] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[06:23:22.8935885] > [Info]  Loading item data...
[06:23:22.8943893] > [Info]  Loading resource "RSItemDataVersion"...
[06:23:23.6406822] > [Info]  A new item data version is available: 20210630
[06:23:23.6407109] > [Info]  Loading resource "RSItemDataLink"...
[06:23:24.3804257] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[06:23:30.0137172] > [Info]  Loading progress data...
[06:23:34.1562328] > [Error] Loading of quest data failed.
 -------------------- 
 System.Net.WebException: 由于目标计算机积极拒绝，无法连接。 由于目标计算机积极拒绝，无法连接。
 ---> System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetProgressDataQuest()
[06:23:48.1605786] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Fixed. Thanks for reporting 👍
