### ISSUE TITLE
Retrieving token metadata failed.

### ISSUE THREAD

**Issue by SelfmadeTommy** [RatScanner/RatScanner#131]
**Error**
Retrieving token metadata failed.
```
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetTarkovTrackerToken()
```
<details>
<summary>Log</summary>

```
[16:53:56.5545315] > [Info]  ----- RatScanner 2.8.6 -----
[16:53:56.5602770] > [Info]  Starting RatScanner...
[16:53:56.5603438] > [Info]  Prewarming name tool tip...
[16:53:56.6546848] > [Info]  Prewarming icon tool tip...
[16:53:56.6808127] > [Info]  Checking for new updates...
[16:53:56.6872934] > [Info]  Loading resource "RSClientVersion"...
[16:53:57.9434827] > [Info]  Loading config...
[16:53:57.9561182] > [Info]  Loading item data...
[16:53:57.9568043] > [Info]  Loading resource "RSItemDataVersion"...
[16:54:01.3560825] > [Info]  Loading progress data...
[16:54:01.7319785] > [Info]  Loading price data...
[16:54:03.4002921] > [Info]  Setting default item...
[16:54:03.4008048] > [Info]  Initializing RatEye...
[16:54:06.3984008] > [Info]  Initializing hotkey manager...
[16:54:06.4009697] > [Info]  Setting up data update routines...
[16:54:06.4010056] > [Info]  Ready!
[16:54:06.5059829] > [Info]  Loading resource "RSPatreonLink"...
[16:54:07.2897697] > [Info]  Loading resource "RSDiscordLink"...
[16:54:08.0569491] > [Info]  Loading resource "RSGithubLink"...
[16:54:58.8526979] > [Info]  Applying config...
[16:55:00.0145418] > [Error] Retrieving token metadata failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetTarkovTrackerToken()

```
</details>

**Comment by Blightbuster** [comment]
Fixed in with a recent update to the backend.
Please comment if this issue persists and I will reopen it.
