### ISSUE TITLE
Loading of resource "RSClientVersion" failed.

### ISSUE THREAD

**Issue by Garyyy77** [RatScanner/RatScanner#137]
**Error**
Loading of resource "RSClientVersion" failed.
```
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
```
<details>
<summary>Log</summary>

```
[15:06:59.7705359] > [Info]  ----- RatScanner 2.8.7 -----
[15:06:59.7854114] > [Info]  Starting RatScanner...
[15:06:59.7866367] > [Info]  Prewarming name tool tip...
[15:07:00.2173405] > [Info]  Prewarming icon tool tip...
[15:07:00.2915339] > [Info]  Checking for new updates...
[15:07:00.3060670] > [Info]  Loading resource "RSClientVersion"...
[15:07:31.3763350] > [Error] Loading of resource "RSClientVersion" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)

```
</details>

**Comment by Spazjuaner** [comment]
Same issue, Same log.

> [13:37:59.8896069] > [Info]  ----- RatScanner 2.8.7 -----
[13:37:59.8938970] > [Info]  Starting RatScanner...
[13:37:59.8939479] > [Info]  Prewarming name tool tip...
[13:38:00.0323748] > [Info]  Prewarming icon tool tip...
[13:38:00.0572867] > [Info]  Checking for new updates...
[13:38:00.0622324] > [Info]  Loading resource "RSClientVersion"...
[13:38:31.1492526] > [Error] Loading of resource "RSClientVersion" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)

**Comment by Blightbuster** [comment]
Fixed. Thanks for reporting 👍
