### ISSUE TITLE
Loading of resource "RSPatreonLink" failed.

### ISSUE THREAD

**Issue by greensmyname** [RatScanner/RatScanner#138]
**Error**
Loading of resource "RSPatreonLink" failed.
```
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
```
<details>
<summary>Log</summary>

```
[22:39:48.8103464] > [Info]  ----- RatScanner 2.8.7 -----
[22:39:48.8202430] > [Info]  Starting RatScanner...
[22:39:48.8206099] > [Info]  Prewarming name tool tip...
[22:39:49.0748637] > [Info]  Prewarming icon tool tip...
[22:39:49.1663518] > [Info]  Checking for new updates...
[22:39:49.1748368] > [Info]  Loading resource "RSClientVersion"...
[22:39:49.6250851] > [Info]  Loading config...
[22:39:49.6379237] > [Info]  Loading item data...
[22:39:49.6392513] > [Info]  Loading resource "RSItemDataVersion"...
[22:39:54.1994701] > [Info]  Loading progress data...
[22:39:54.4478057] > [Info]  Loading price data...
[22:39:54.6342187] > [Info]  Setting default item...
[22:39:54.6347165] > [Info]  Initializing RatEye...
[22:40:03.0767697] > [Info]  Initializing hotkey manager...
[22:40:03.0791524] > [Info]  Setting up data update routines...
[22:40:03.0792518] > [Info]  Ready!
[22:40:03.4104789] > [Info]  Loading resource "RSPatreonLink"...
[22:40:33.5235572] > [Error] Loading of resource "RSPatreonLink" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.Get(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
[22:40:33.5558857] > [Info]  Loading resource "RSDiscordLink"...
[22:40:47.1502391] > [Info]  Loading resource "RSGithubLink"...
[22:50:03.0789421] > [Info]  Refreshing TarkovTracker DB...
[22:52:05.3964385] > [Info]  Loading resource "RSPatreonLink"...

```
</details>

**Comment by Blightbuster** [comment]
Fixed. Thanks for reporting 👍
