### ISSUE TITLE
Unhandled exception in RatScanner 3.0.0

### ISSUE THREAD

**Issue by Dr4g0nK** [RatScanner/RatScanner#162]
**Error**
Unhandled exception in RatScanner 3.0.0
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (Unexpected character encountered while parsing value: E. Path '', line 0, position 0.))
 ---> System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: E. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at N
```
<details>
<summary>Log</summary>

```
[17:50:59.2347099] > [Info]  ----- RatScanner 3.0.0 -----
[17:50:59.2349256] > [Info]  Starting RatScanner...
[17:50:59.2351653] > [Info]  Prewarming name tool tip...
[17:50:59.2635926] > [Info]  Prewarming icon tool tip...
[17:50:59.2849830] > [Info]  Checking for new updates...
[17:50:59.2911704] > [Info]  Loading resource "RSClientVersion"...
[17:50:59.9123721] > [Info]  Loading config...
[17:50:59.9189981] > [Info]  Loading item data...
[17:50:59.9192074] > [Info]  Loading resource "RSItemDataVersion"...
[17:51:01.9406492] > [Info]  Loading progress data...
[17:51:02.2639998] > [Info]  Loading price data...
[17:51:02.7695931] > [Info]  Setting default item...
[17:51:02.7699188] > [Info]  Initializing RatEye...
[17:51:06.1041963] > [Info]  Initializing hotkey manager...
[17:51:06.1061025] > [Info]  Setting up data update routines...
[17:51:06.1061235] > [Info]  Ready!
[17:52:34.5623545] > [Error] Unhandled exception in RatScanner 3.0.0
 -------------------- 
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (Unexpected character encountered while parsing value: E. Path '', line 0, position 0.))
 ---> System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: E. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateToken() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 60
   at RatTracking.TarkovTrackerDB.ValidToken() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 42
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 21
   at RatScanner.ViewModel.SettingsVM.UpdateTarkovTrackerToken()
   at RatScanner.ViewModel.SettingsVM.SaveSettings()
   at RatRazor.Pages.App.Settings.SettingsSave.SaveSettings() in D:\Programmierung\Projects\RatScanner\RatScanner\RatRazor\Pages\App\Settings\SettingsSave.razor:line 18
   at Microsoft.AspNetCore.Components.EventC
```
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.1.0](https://github.com/RatScanner/RatScanner/releases/tag/v3.1.0).
Please comment if this issue persists and I will reopen it.
