### ISSUE TITLE
Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.

### ISSUE THREAD

**Issue by Limosk** [RatScanner/RatScanner#169]
**Error**
Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
```
System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, 
```
<details>
<summary>Log</summary>

```
[02:13:37.4844474] > [Error] Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
 -------------------- 
 System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RatScanner.PageSwitcher.InitializeComponent()
   at RatScanner.PageSwitcher..ctor()
[02:13:55.5597228] > [Error] Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
 -------------------- 
 System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTy
```
</details>

**Comment by Blightbuster** [comment]
Hey, it seems like RatScanner is being blocked by some other software.
- Try adding a exception for RatScanner to your antivirus or disable it temporarily
- Try starting RatScanner as administrator

**Comment by Limosk** [comment]
Tried both and it's still not working

**Comment by Blightbuster** [comment]
- Are you trying to use version 3.1.0?
- Did you unzip the downloaded `RatScanner.zip`?
- Where did you unzip it to? (Perhaps a system or onedrive folder?)
- Do you start `RatScanner.exe` directly or through the startmenu / a shortcut?
- Is this error happening as soon as you start `RatScanner.exe`?

**Comment by Limosk** [comment]
I'm using version 3.1.0.
I unzipped it onto the Documents folder (not on OneDrive).
I'm running the executable directly.
It happens as soon as I try to open RatScanner.exe.

**Comment by Limosk** [comment]
After further testing, it worked.
  
I had to install version 3.0.0, then update to 3.1.0 through the prompt. This somehow made it work.
  
Downloading 3.1.0 directly however, still results in the same error.

**Comment by Blightbuster** [comment]
While I dont understand why that worked, Im glad it did. Thanks for letting me know ❤️
