### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.

### ISSUE THREAD

**Issue by henrique-costa** [RatScanner/RatScanner#170]
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Projects\RatScanner\RatScanner\bin\Debug\net6.0-windows\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int6
```
<details>
<summary>Log</summary>

```
[04:01:32.5515607] > [Info]  ----- RatScanner 3.1.0 -----
[04:01:32.5517493] > [Info]  Starting RatScanner...
[04:01:32.5517588] > [Info]  Checking for new updates...
[04:01:32.5586468] > [Info]  Loading resource "RSClientVersion"...
[04:01:33.3649915] > [Info]  Loading config...
[04:01:33.3668366] > [Info]  Loading item data...
[04:01:33.3672186] > [Info]  Loading resource "RSItemDataVersion"...
[04:01:33.5308799] > [Info]  A new item data version is available: 20211216
[04:01:33.5308923] > [Info]  Loading resource "RSItemDataLink"...
[04:01:33.6938317] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[04:01:35.4116536] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Projects\RatScanner\RatScanner\bin\Debug\net6.0-windows\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination) in E:\Projects\RatScanner\RatScanner\ApiManager.cs:line 105

```
</details>

**Comment by Blightbuster** [comment]
Hey, it seems like your trying to build ratscanner yourself for development purposes is this correct or do you just want to use the program?

**Comment by henrique-costa** [comment]
> Hey, it seems like your trying to build ratscanner yourself for development purposes is this correct or do you just want to use the program?

Hey, yeah. Im a junior C# dev. I found it amaizing to see complex/production code. I dont intend to override or code anything new. Just tried to build it on Visual Studio 2022. You can close this issue if u want

**Comment by Blightbuster** [comment]
Did you solve the problem? If not, perhaps I can help you out with making it work 😄

**Comment by henrique-costa** [comment]
> 

No, I didnt solve it haha I have no ideia what to do. I know a bit of WebSevices and API but even if I download the missing json i woudnt know where to put it. Ok, how can u help me?

**Comment by Blightbuster** [comment]
So it looks like the program is trying to access this path: `E:\Projects\RatScanner\RatScanner\bin\Debug\net6.0-windows\Data\` but it does not exist for some reason. A easy fix would be to manually create this folder structure or even directly place the `items.json` file in there which you can download [here](https://api.ratscanner.com/v3/file/items-en-16.12.2021.json) (You will still need to rename it to `items.json` after downloading).

**Comment by henrique-costa** [comment]
> So it looks like the program is trying to access this path: `E:\Projects\RatScanner\RatScanner\bin\Debug\net6.0-windows\Data\` but it does not exist for some reason. A easy fix would be to manually create this folder structure or even directly place the `items.json` file in there which you can download [here](https://api.ratscanner.com/v3/file/items-en-16.12.2021.json) (You will still need to rename it to `items.json` after downloading).

It worked out creating a new Data folder and placing the json inside it. 

Now the ratscanner window shows up but with a another error:

 System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'E:\Projects\RatScanner\RatScanner\bin\Debug\net6.0-windows\Data\icons\correlation.json'.
  Source=System.Private.CoreLib
  StackTrace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)

**Comment by Blightbuster** [comment]
Looks like you didnt do step 2 from here:
https://github.com/RatScanner/RatScanner#setting-up-the-repository-for-development
