### ISSUE TITLE
Unhandled exception in RatScanner 2.6.1

### ISSUE THREAD

**Issue by TheRobberPanda** [RatScanner/RatScanner#177]
**Error**
Unhandled exception in RatScanner 2.6.1
```
Newtonsoft.Json.JsonSerializationException: Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.
 ---> System.ArgumentException: Requested value 'factory4_day' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Po
```
<details>
<summary>Log</summary>

```
[13:26:32.0861890] > [Info]  ----- RatScanner 2.6.1 -----
[13:26:32.0869167] > [Info]  Starting RatScanner...
[13:26:32.0869721] > [Info]  Loading config...
[13:26:32.1037726] > [Info]  Loading item data...
[13:26:32.1096914] > [Info]  Loading resource "RSItemDataLink"...
[13:26:32.7263355] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[13:26:35.9475982] > [Error] Unhandled exception in RatScanner 2.6.1
 -------------------- 
 Newtonsoft.Json.JsonSerializationException: Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.
 ---> System.ArgumentException: Requested value 'factory4_day' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Se
```
</details>

**Comment by Blightbuster** [comment]
Hey, could you update to the latest version (3.1.0) and try again?
