### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by mapkellll** [RatScanner/RatScanner#180]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Games\Rat Scanner\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileM
```
<details>
<summary>Log</summary>

```
[04:51:48.3067942] > [Info]  ----- RatScanner 3.1.0 -----
[04:51:48.3069271] > [Info]  Starting RatScanner...
[04:51:48.3069316] > [Info]  Checking for new updates...
[04:51:48.3146077] > [Info]  Loading resource "RSClientVersion"...
[04:51:49.0040734] > [Info]  Loading config...
[04:51:49.0060513] > [Info]  Loading item data...
[04:51:49.0066334] > [Info]  Loading resource "RSItemDataVersion"...
[04:51:51.7276964] > [Info]  Loading progress data...
[04:51:52.2815285] > [Info]  Loading price data...
[04:51:54.3807269] > [Info]  Setting default item...
[04:51:54.3808881] > [Info]  Initializing RatEye...
[04:51:58.4822764] > [Info]  Initializing hotkey manager...
[04:51:58.4835986] > [Info]  Setting up data update routines...
[04:51:58.4836356] > [Info]  Ready!
[04:52:00.8168673] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:00.8180358] > [Debug] NameScan:235 -> Name scanning at: (1433, 436)
[04:52:01.3846200] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:01.3848088] > [Debug] NameScan:235 -> Name scanning at: (1433, 436)
[04:52:01.5525172] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:01.5526822] > [Debug] NameScan:235 -> Name scanning at: (1433, 436)
[04:52:02.9845698] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:02.9847159] > [Debug] NameScan:235 -> Name scanning at: (831, 446)
[04:52:04.8644735] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:04.8646414] > [Debug] NameScan:235 -> Name scanning at: (826, 441)
[04:52:06.4485405] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:06.4486136] > [Debug] NameScan:235 -> Name scanning at: (1164, 444)
[04:52:07.9524474] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:07.9525041] > [Debug] NameScan:235 -> Name scanning at: (836, 404)
[04:52:08.2404611] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:08.2406121] > [Debug] NameScan:235 -> Name scanning at: (836, 404)
[04:52:08.8004533] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:08.8005934] > [Debug] NameScan:235 -> Name scanning at: (836, 406)
[04:52:09.0004583] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:09.0006107] > [Debug] NameScan:235 -> Name scanning at: (836, 406)
[04:52:09.5844376] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:09.5845696] > [Debug] NameScan:235 -> Name scanning at: (868, 414)
[04:52:10.2804517] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:10.2805970] > [Debug] NameScan:235 -> Name scanning at: (872, 406)
[04:52:11.3125045] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:11.3126546] > [Debug] NameScan:235 -> Name scanning at: (838, 406)
[04:52:11.5844154] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:11.5845796] > [Debug] NameScan:235 -> Name scanning at: (839, 405)
[04:52:13.0323218] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:13.0324916] > [Debug] NameScan:235 -> Name scanning at: (195, 244)
[04:52:14.1203980] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:14.1205780] > [Debug] NameScan:235 -> Name scanning at: (861, 405)
[04:52:14.4484163] > [Debug] OnKeyUp:96 -> Pressed: Left
[04:52:14.4485611] > [Debug] NameScan:235 -> Name scanning at: (826, 407)
```
</details>

**Comment by Blightbuster** [comment]
Hey, when Rat scanner starts for the first time, it might have to install a dependency. While doing that the rat scanner window will just be empty with a dark background. Did you perhaps close it while it was in that state?

Opening it again and waiting for it to complete this installation should solve the issue.
