### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.

### ISSUE THREAD

**Issue by ihugo911** [RatScanner/RatScanner#181]
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\Desktop\RatScanner\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   a
```
<details>
<summary>Log</summary>

```
[05:26:57.6559180] > [Info]  ----- RatScanner 3.1.0 -----
[05:26:57.6560441] > [Info]  Starting RatScanner...
[05:26:57.6560464] > [Info]  Checking for new updates...
[05:26:57.6618769] > [Info]  Loading resource "RSClientVersion"...
[05:26:58.3369327] > [Info]  Loading config...
[05:26:58.3383713] > [Info]  Loading item data...
[05:26:58.3385166] > [Info]  Loading resource "RSItemDataVersion"...
[05:26:58.4864433] > [Info]  A new item data version is available: 20211216
[05:26:58.4864593] > [Info]  Loading resource "RSItemDataLink"...
[05:26:58.6111977] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[05:27:00.3625478] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\Desktop\RatScanner\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)

```
</details>

**Comment by Blightbuster** [comment]
Hey, is your desktop possibly a one drove folder? If so please move rat scanner to a location which is not a onedrive folder.

**Comment by Blightbuster** [comment]
Please comment and I will re-open this issue, if the error persists.
