### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by MeetyMicheal523** [RatScanner/RatScanner#191]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
<details>
<summary>Log</summary>

```
[12:22:39.4473745] > [Warning] Config version (-1) is not supported!
[12:22:39.4717773] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[12:22:39.4877511] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[12:22:43.1151448] > [Info]  Loading resource "RSGithubLink"...
[12:24:06.2141199] > [Warning] Config version (-1) is not supported!
[12:24:06.2293333] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[12:24:06.2451896] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[12:24:44.3251789] > [Warning] Config version (-1) is not supported!
[12:24:44.3405210] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[12:24:44.3557943] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[12:25:15.7117562] > [Warning] Config version (-1) is not supported!
[12:25:15.7296917] > [Info]  Detected 1920x1080 Resolution.

Y
```
</details>

**Comment by Blightbuster** [comment]
Will be tracked in #182
