### ISSUE TITLE
Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')

### ISSUE THREAD

**Issue by Abd11101** [RatScanner/RatScanner#198]
**Error**
Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')
```
System.ArgumentException: Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')
   at RatEye.Processing.Inspection.GetTesseractInstance()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatLib.Scan.ItemNameScan..ctor(Bitmap capture, Vector2 mousePosition, Int32 scanSize, Int32 duration)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap[T](Func`1 func)
```
<details>
<summary>Log</summary>

```
[16:26:59.8602048] > [Error] Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')
 -------------------- 
 System.ArgumentException: Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')
   at RatEye.Processing.Inspection.GetTesseractInstance()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatLib.Scan.ItemNameScan..ctor(Bitmap capture, Vector2 mousePosition, Int32 scanSize, Int32 duration)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap[T](Func`1 func)
[16:27:00.0993832] > [Error] Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')
 -------------------- 
 System.ArgumentException: Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')
   at RatEye.Processing.Inspection.GetTesseractInstance()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatLib.Scan.ItemNameScan..ctor(Bitmap capture, Vector2 mousePosition, Int32 scanSize, Int32 duration)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap[T](Func`1 func)
[16:27:07.7236072] > [Error] Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')
 -------------------- 
 System.ArgumentException: Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa13056.7821\Data')
   at RatEye.Processing.Inspection.GetTesseractInstance()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatLib.Scan.ItemNameScan..ctor(Bitmap capture, Vector2 mousePosition, Int32 scanSize, Int32 duration)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap[T](Func`1 func)
[16:27:09.1680850] > [Info]  Loading resource "RSFAQLink"...
[16:27:20.2984161] > [Info]  Loading resource "RSGithubLink"...
[16:27:20.8235956] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.DllNotFoundException: Dll was not found.
   at __std_type_info_destroy_list(__type_info_node* )
   at 
```
</details>

**Comment by Blightbuster** [comment]
Hey, please extract rat scanner to a location instead of running it from the zip file.
