### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\Vol12\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by blackyxyz** [RatScanner/RatScanner#199]
**Error**
Could not find dynamic correlation data at: C:\Users\Vol12\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[17:04:39.3324979] > [Info]  ----- RatScanner 2.5.0 -----
[17:04:39.3334058] > [Info]  Starting RatScanner...
[17:04:39.3334681] > [Info]  Loading config...
[17:04:39.3492503] > [Info]  Loading price data...
[17:04:39.9911691] > [Info]  Setting default item...
[17:04:39.9958289] > [Info]  Initializing name scan...
[17:04:39.9960362] > [Info]  Loading OCR data...
[17:04:40.0732715] > [Info]  Initializing icon scan...
[17:04:40.0746041] > [Info]  Loading static icons...
[17:04:40.1724629] > [Info]  Loaded 1197/1197 icons successfully.
[17:04:40.1744538] > [Info]  Loading static correlation data...
[17:04:40.1950343] > [Info]  Loading dynamic correlation data...
[17:04:40.2092806] > [Error] Could not find dynamic correlation data at: C:\Users\Vol12\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr 
```
</details>

**Comment by Blightbuster** [comment]
Hey, please update to the latest version:
https://github.com/RatScanner/RatScanner/releases/tag/v3.1.0
