### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by absolutikdadad** [RatScanner/RatScanner#202]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: Не удается найти указанный файл. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfWebView2Wrapper.CreateEnvironmentAsync()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass4_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsyn
```
<details>
<summary>Log</summary>

```
[19:00:48.0282998] > [Warning] Config version (-1) is not supported!
[19:00:48.0434892] > [Info]  Detected 2560x1440 Resolution.

You can adjust this inside the settings.
[19:00:52.0973451] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: Не удается найти указанный файл. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfWebView2Wrapper.CreateEnvironmentAsync()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass4_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[19:00:52.1927029] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: Не удается найти указанный файл. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfWebView2Wrapper.CreateEnvironmentAsync()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebV
```
</details>

**Comment by Blightbuster** [comment]
Hey, please try manually installing the web view 2 runtime:
https://go.microsoft.com/fwlink/p/?LinkId=2124703
