### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by Hor1st** [RatScanner/RatScanner#209]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
System.DllNotFoundException: Dll was not found.
   at __std_type_info_destroy_list(__type_info_node* )
   at __scrt_uninitialize_type_info()
   at _app_exit_callback()
   at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
   at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
   at System.AppContext.OnProcessExit()
```
<details>
<summary>Log</summary>

```
[23:10:00.8868048] > [Error] Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa5508.33846\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa5508.33846\Data')
 -------------------- 
 System.ArgumentException: Could not find traineddata at: C:\Users\User\AppData\Local\Temp\Rar$EXa5508.33846\Data\bender.traineddata (Parameter 'C:\Users\User\AppData\Local\Temp\Rar$EXa5508.33846\Data')
   at RatEye.Processing.Inspection.GetTesseractInstance()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatLib.Scan.ItemNameScan..ctor(Bitmap capture, Vector2 mousePosition, Int32 scanSize, Int32 duration)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<>c.<OnNameScanHotkey>b__7_0()
   at RatScanner.HotkeyManager.Wrap[T](Func`1 func)
[23:10:04.7037358] > [Info]  Loading resource "RSFAQLink"...
[23:10:13.8920027] > [Info]  Loading resource "RSGithubLink"...
[23:10:14.2624313] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.DllNotFoundException: Dll was not found.
   at __std_type_info_destroy_list(__type_info_node* )
   at __scrt_uninitialize_type_info()
   at _app_exit_callback()
   at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
   at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
   at System.AppContext.OnProcessExit()

```
</details>

**Comment by Blightbuster** [comment]
You cannot run `RatScanner.exe` from within the zip file. Please extract it first and then run it.
