### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.

### ISSUE THREAD

**Issue by EEdle506** [RatScanner/RatScanner#215]
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\My Projects\GitHub\EEdle506\RatScanner\RatScanner\bin\Debug\net6.0-windows\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOp
```
<details>
<summary>Log</summary>

```
[20:02:44.4427623] > [Info]  ----- RatScanner 3.1.0 -----
[20:02:44.4429726] > [Info]  Starting RatScanner...
[20:02:44.4429760] > [Info]  Checking for new updates...
[20:02:44.4955605] > [Info]  Loading resource "RSClientVersion"...
[20:02:44.9794783] > [Info]  Loading config...
[20:02:44.9828469] > [Info]  Loading item data...
[20:02:44.9831791] > [Info]  Loading resource "RSItemDataVersion"...
[20:02:45.0932030] > [Info]  A new item data version is available: 20211216
[20:02:45.0932147] > [Info]  Loading resource "RSItemDataLink"...
[20:02:45.2027646] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[20:02:46.4082218] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\My Projects\GitHub\EEdle506\RatScanner\RatScanner\bin\Debug\net6.0-windows\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination) in D:\My Projects\GitHub\EEdle506\RatScanner\RatScanner\ApiManager.cs:line 105

```
</details>

**Comment by Blightbuster** [comment]
Hey, are you trying to build rat scanner on your own or do you want to use a precompiled version?

What you will need to do if you wanna build yourself is to copy the `Data` folder into the compile target folder

**Comment by EEdle506** [comment]
Hi, I want to run precompiled version

**Comment by EEdle506** [comment]
It is seems like I have no WebView2 Runtime on my Edge

**Comment by Blightbuster** [comment]
If you didnt find it already, you can download the precompiled version [here](https://github.com/RatScanner/RatScanner/releases/download/v3.1.0/RatScanner.zip).

It should automatically install everything which is required, you might just have to wait a short minute while its loading.
