### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by assa1993q** [RatScanner/RatScanner#222]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot provide a value for property 'TarkovTrackerDB' on type 'RatRazor.Pages.App.Index'. There is no registered service of type 'RatTracking.TarkovTrackerDB'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffCon
```
<details>
<summary>Log</summary>

```
[12:46:34.2830069] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\ratata\Desktop\Новая папка\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at RatScanner.App.InstallWebview2Runtime()
   at RatScanner.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[12:46:41.5957816] > [Info]  Loading resource "RSGithubLink"...

```
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
