### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by AnimeshnikIQD** [RatScanner/RatScanner#225]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\User\Desktop\Игры\RatScanner\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, S
```
<details>
<summary>Log</summary>

```
[18:12:07.6070423] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\User\Desktop\Игры\RatScanner\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at RatScanner.App.InstallWebview2Runtime()
   at RatScanner.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[18:12:10.5724715] > [Info]  Loading resource "RSGithubLink"...
[18:12:21.1619563] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\User\Desktop\Игры\RatScanner\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStr
```
</details>

**Comment by Blightbuster** [comment]
To fix this, please uninstall the Webview2 runtime through windows "Add or remove programs" option and then try again with the latest version.

The core issue of this error has since been fixed in version 3.3.0.
