### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by Soboliny** [RatScanner/RatScanner#226]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
<details>
<summary>Log</summary>

```
[19:06:54.7976263] > [Warning] Config version (-1) is not supported!
[19:06:54.8114314] > [Info]  Detected 2560x1440 Resolution.

You can adjust this inside the settings.
[19:06:54.8243730] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[19:06:58.8555762] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
