### ISSUE TITLE
External component has thrown an exception.

### ISSUE THREAD

**Issue by FilStudioDev** [RatScanner/RatScanner#230]
**Error**
External component has thrown an exception.
```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at OpenCvSharp.Internal.NativeMethods.text_OCRTesseract_create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode, IntPtr& returnValue)
   at OpenCvSharp.Text.OCRTesseract.Create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode)
   at RatEye.Processing.Inspection.GetTesseractInstance()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatLib.Scan.ItemNameScan..ctor(Bitmap capture, Vector2 mousePosition, Int32 scanSize, Int32 duration) in D:\Programmierung\Projects\RatScanner\RatScanner\RatLib\Scan\ItemNameScan.cs:line 23
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<>c.<OnNameScanHotkey>b__7_0()
   at R
```
<details>
<summary>Log</summary>

```
[10:04:25.2048919] > [Info]  ----- RatScanner 3.1.0 -----
[10:04:25.2049054] > [Info]  Starting RatScanner...
[10:04:25.2049076] > [Info]  Checking for new updates...
[10:04:25.2146768] > [Info]  Loading resource "RSClientVersion"...
[10:04:25.9375456] > [Info]  Loading config...
[10:04:25.9377093] > [Warning] Config version (-1) is not supported!
[10:04:25.9377195] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[10:04:27.1576230] > [Info]  Loading item data...
[10:04:27.1584531] > [Info]  Loading resource "RSItemDataVersion"...
[10:04:27.3043052] > [Info]  A new item data version is available: 20211216
[10:04:27.3043180] > [Info]  Loading resource "RSItemDataLink"...
[10:04:27.4502737] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[10:04:42.7470458] > [Info]  Loading progress data...
[10:04:43.6791464] > [Info]  Loading price data...
[10:04:44.7748430] > [Info]  Setting default item...
[10:04:44.7750571] > [Info]  Initializing RatEye...
[10:04:47.3517126] > [Info]  Initializing hotkey manager...
[10:04:47.3536853] > [Info]  Setting up data update routines...
[10:04:47.3537370] > [Info]  Ready!
[10:05:00.8117874] > [Error] External component has thrown an exception.
 -------------------- 
 System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at OpenCvSharp.Internal.NativeMethods.text_OCRTesseract_create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode, IntPtr& returnValue)
   at OpenCvSharp.Text.OCRTesseract.Create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode)
   at RatEye.Processing.Inspection.GetTesseractInstance()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatLib.Scan.ItemNameScan..ctor(Bitmap capture, Vector2 mousePosition, Int32 scanSize, Int32 duration) in D:\Programmierung\Projects\RatScanner\RatScanner\RatLib\Scan\ItemNameScan.cs:line 23
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<>c.<OnNameScanHotkey>b__7_0()
   at RatScanner.HotkeyManager.Wrap[T](Func`1 func)
[10:07:28.0776953] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
