### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by FNchy** [RatScanner/RatScanner#240]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
<details>
<summary>Log</summary>

```
[00:02:45.2147218] > [Warning] Config version (-1) is not supported!
[00:02:45.2369925] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[00:02:45.2570285] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[00:09:30.3505243] > [Warning] Config version (-1) is not supported!
[00:09:30.3751903] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[00:09:30.3989491] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[00:09:33.4970922] > [Warning] Config version (-1) is not supported!
[00:09:33.5204161] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[00:09:33.5417935] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.PageSwitcher.OnClosed(EventArgs e)
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[00:09:39.4376030] > [Warning] Config version (-1) is not supported!
[00:09:39.4619451] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[00:09:39.4872128] > [Er
```
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
