### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by tomeramen** [RatScanner/RatScanner#241]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 22
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(B
```
<details>
<summary>Log</summary>

```
[23:06:43.0538530] > [Info]  ----- RatScanner 3.1.0 -----
[23:06:43.0541022] > [Info]  Starting RatScanner...
[23:06:43.0541102] > [Info]  Checking for new updates...
[23:06:43.0704961] > [Info]  Loading resource "RSClientVersion"...
[23:06:43.6034279] > [Info]  Loading config...
[23:06:43.6051618] > [Info]  Loading item data...
[23:06:43.6077299] > [Info]  Loading resource "RSItemDataVersion"...
[23:06:46.9500938] > [Info]  Loading TarkovTracker...
[23:06:47.6179777] > [Info]  Loading progress data...
[23:06:47.7382979] > [Info]  Loading price data...
[23:06:48.2116320] > [Info]  Setting default item...
[23:06:48.2118174] > [Info]  Initializing RatEye...
[23:06:56.5956911] > [Info]  Initializing hotkey manager...
[23:06:56.5984755] > [Info]  Setting up data update routines...
[23:06:56.5985350] > [Info]  Ready!
[23:11:56.5987770] > [Info]  Refreshing TarkovTracker DB...
[23:16:57.0617324] > [Info]  Refreshing TarkovTracker DB...
[23:21:57.5004004] > [Info]  Refreshing TarkovTracker DB...
[23:26:57.9681486] > [Info]  Refreshing TarkovTracker DB...
[23:31:58.3810685] > [Info]  Refreshing TarkovTracker DB...
[23:36:56.6005168] > [Info]  Refreshing Market DB...
[23:36:58.8128658] > [Info]  Refreshing TarkovTracker DB...
[23:41:59.4066090] > [Info]  Refreshing TarkovTracker DB...
[23:46:59.9841393] > [Info]  Refreshing TarkovTracker DB...
[23:52:00.5955723] > [Info]  Refreshing TarkovTracker DB...
[23:57:01.0925327] > [Info]  Refreshing TarkovTracker DB...
[00:02:01.5863972] > [Info]  Refreshing TarkovTracker DB...
[00:06:57.3636783] > [Info]  Refreshing Market DB...
[00:07:01.9404011] > [Info]  Refreshing TarkovTracker DB...
[00:12:09.5491081] > [Info]  Refreshing TarkovTracker DB...
[00:17:10.1778683] > [Info]  Refreshing TarkovTracker DB...
[00:22:10.9148697] > [Info]  Refreshing TarkovTracker DB...
[00:22:29.0298301] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 22
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQu
```
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
