### ISSUE TITLE
Unhandled exception (TaskScheduler.UnobservedTaskException)

### ISSUE THREAD

**Issue by xGrimreave** [RatScanner/RatScanner#242]
**Error**
Unhandled exception (TaskScheduler.UnobservedTaskException)
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot provide a value for property 'TarkovTrackerDB' on type 'RatRazor.Pages.App.Index'. There is no registered service of type 'RatTracking.TarkovTrackerDB'.)
 ---> System.InvalidOperationException: Cannot provide a value for property 'TarkovTrackerDB' on type 'RatRazor.Pages.App.Index'. There is no registered service of type 'RatTracking.TarkovTrackerDB'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type compone
```
<details>
<summary>Log</summary>

```
[04:36:00.3811801] > [Info]  ----- RatScanner 3.1.0 -----
[04:36:00.3811893] > [Info]  Starting RatScanner...
[04:36:00.3811908] > [Info]  Checking for new updates...
[04:36:00.3879802] > [Info]  Loading resource "RSClientVersion"...
[04:36:03.0749881] > [Info]  Loading config...
[04:36:03.0765964] > [Info]  Loading item data...
[04:36:03.0771469] > [Info]  Loading resource "RSItemDataVersion"...
[04:36:03.1176726] > [Info]  A new item data version is available: 20211216
[04:36:03.1176820] > [Info]  Loading resource "RSItemDataLink"...
[04:36:03.1583017] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[04:36:05.7116762] > [Info]  Loading progress data...
[04:36:05.8785826] > [Info]  Loading price data...
[04:36:06.0732731] > [Info]  Setting default item...
[04:36:06.0734132] > [Info]  Initializing RatEye...
[04:36:09.4790212] > [Info]  Initializing hotkey manager...
[04:36:09.4806676] > [Info]  Setting up data update routines...
[04:36:09.4807033] > [Info]  Ready!
[04:39:04.2644953] > [Info]  Saving config...
[04:39:04.2681292] > [Info]  Config saved!
[04:39:13.0312148] > [Info]  Saving config...
[04:39:13.0345967] > [Info]  Config saved!
[04:39:35.9253601] > [Info]  Saving config...
[04:39:35.9297117] > [Info]  Config saved!
[04:39:45.9338604] > [Info]  Saving config...
[04:39:45.9374549] > [Info]  Config saved!
[04:41:09.4821710] > [Info]  Refreshing TarkovTracker DB...

```
</details>

**Comment by Blightbuster** [comment]
Fixed in [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
Thanks for creating the issue.
