### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by GYURZA1** [RatScanner/RatScanner#251]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
System.DllNotFoundException: Dll was not found.
   at __std_type_info_destroy_list(__type_info_node* )
   at __scrt_uninitialize_type_info()
   at _app_exit_callback()
   at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
   at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
   at System.AppContext.OnProcessExit()
```
<details>
<summary>Log</summary>

```
[14:04:42.8585018] > [Error] Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
 -------------------- 
 System.Windows.Markup.XamlParseException: Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RatScanner.PageSwitcher.InitializeComponent()
   at RatScanner.PageSwitcher..ctor()
[14:05:06.7908362] > [Info]  Loading resource "RSFAQLink"...
[14:07:21.7432506] > [Info]  Loading resource "RSGithubLink"...
[14:07:22.2123471] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.DllNotFoundException: Dll was not found.
   at __std_type_info_destroy_list(__type_info_node* )
   at __scrt_uninitialize_type_info()
   at _app_exit_callback()
   at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
   at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
   at System.AppContext.OnProcessExit()

```
</details>

**Comment by Blightbuster** [comment]
It looks like your running `RatScanner.exe` from within the zip file. You need to extract the zip file first and then run `RatScanner.exe`.

**Comment by Blightbuster** [comment]
From now on tracked in #247.

Thanks for creating the issue.
