### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by Timyr112** [RatScanner/RatScanner#255]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Net.WebException: Этот хост неизвестен. (go.microsoft.com:443)
 ---> System.Net.Http.HttpRequestException: Этот хост неизвестен. (go.microsoft.com:443)
 ---> System.Net.Sockets.SocketException (11001): Этот хост неизвестен.
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.HttpWebRequest.<>c__DisplayClass216_0.<<CreateHttpClient>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exc
```
<details>
<summary>Log</summary>

```
[14:19:45.4623908] > [Info]  ----- RatScanner 3.1.0 -----
[14:19:45.4625662] > [Info]  Starting RatScanner...
[14:19:45.4625733] > [Info]  Checking for new updates...
[14:19:45.4720336] > [Info]  Loading resource "RSClientVersion"...
[14:19:46.0569137] > [Info]  Loading config...
[14:19:46.0610983] > [Info]  Loading item data...
[14:19:46.0619771] > [Info]  Loading resource "RSItemDataVersion"...
[14:19:49.1573509] > [Info]  Loading progress data...
[14:19:49.4986193] > [Info]  Loading price data...
[14:19:50.3534505] > [Info]  Setting default item...
[14:19:50.3536308] > [Info]  Initializing RatEye...
[14:19:55.3442541] > [Info]  Initializing hotkey manager...
[14:19:55.3460229] > [Info]  Setting up data update routines...
[14:19:55.3460694] > [Info]  Ready!
[15:57:53.3191131] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Net.WebException: Этот хост неизвестен. (go.microsoft.com:443)
 ---> System.Net.Http.HttpRequestException: Этот хост неизвестен. (go.microsoft.com:443)
 ---> System.Net.Sockets.SocketException (11001): Этот хост неизвестен.
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.HttpWebRequest.<>c__DisplayClass216_0.<<CreateHttpClient>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage
```
</details>

**Comment by Blightbuster** [comment]
Please comment if the issue persists and I will reopen it.
