### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.

### ISSUE THREAD

**Issue by PrinzG123** [RatScanner/RatScanner#268]
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\Desktop\RatScanner-master\publish\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 prealloc
```
<details>
<summary>Log</summary>

```
[11:58:17.3852148] > [Info]  ----- RatScanner 3.1.0 -----
[11:58:17.3853790] > [Info]  Starting RatScanner...
[11:58:17.3853812] > [Info]  Checking for new updates...
[11:58:17.3911307] > [Info]  Loading resource "RSClientVersion"...
[11:58:17.9538757] > [Info]  Loading config...
[11:58:17.9553097] > [Info]  Loading item data...
[11:58:17.9555140] > [Info]  Loading resource "RSItemDataVersion"...
[11:58:18.3012576] > [Info]  A new item data version is available: 20211216
[11:58:18.3012771] > [Info]  Loading resource "RSItemDataLink"...
[11:58:18.6609929] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[11:58:32.8473611] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\Desktop\RatScanner-master\publish\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
[11:58:47.8385435] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Are you trying to compile the project yourself? If not you can also just download the pre-compiled build from [here](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip).
