### ISSUE TITLE
Exception has been thrown by the target of an invocation. 3.2.0pre3. when inspecting to scan

### ISSUE THREAD

**Issue by Molier** [RatScanner/RatScanner#293]
**Error**
Exception has been thrown by the target of an invocation.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at InteropDotNet.LibraryLoader.InternalLoadLibrary(String baseDirectory, String platformName, String fileName)
   at InteropDotNet.LibraryLoader.CheckExecutingAssemblyDomain(String fileName, String platformName)
   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)
   at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   
```
<details>
<summary>Log</summary>

```
[23:38:54.4552839] > [Info]  ----- RatScanner 3.1.0 -----
[23:38:54.4554763] > [Info]  Starting RatScanner...
[23:38:54.4554842] > [Info]  Checking for updates...
[23:38:54.4577421] > [Info]  Loading resource "RSClientVersion"...
[23:38:56.3001934] > [Info]  Loading config...
[23:38:56.3014254] > [Info]  Checking for item data updates...
[23:38:56.3018516] > [Info]  Loading resource "RSItemDataBundleVersion"...
[23:38:56.6389416] > [Info]  Loading progress data...
[23:38:58.7732784] > [Info]  Loading price data...
[23:39:00.9919749] > [Info]  Initializing RatEye...
[23:39:04.0363044] > [Info]  Setting default item...
[23:39:04.0931414] > [Info]  Initializing hotkey manager...
[23:39:04.0949884] > [Info]  Setting up data update routines...
[23:39:04.0950034] > [Info]  Ready!
[23:39:44.1136742] > [Info]  Saving config...
[23:39:44.1256097] > [Info]  Config saved!
[23:39:50.3042211] > [Info]  Saving config...
[23:39:50.3147293] > [Info]  Config saved!
[23:40:42.0266792] > [Error] Exception has been thrown by the target of an invocation.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at InteropDotNet.LibraryLoader.InternalLoadLibrary(String baseDirectory, String platformName, String fileName)
   at InteropDotNet.LibraryLoader.CheckExecutingAssemblyDomain(String fileName, String platformName)
   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)
   at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at InteropDotNet.InteropRuntimeImplementer.CreateInstance[T]()
   at Tesseract.Interop.LeptonicaApi.Initialize()
   at Tesseract.Interop.LeptonicaApi.get_Native()
   at Tesseract.Pix.Create(Int32 width, Int32 height, Int32 depth)
   at Tesseract.BitmapToPixConverter.Convert(Bitmap img)
   at Tesseract.PixConverter.ToPix(Bitmap img)
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatSc
```
</details>

**Comment by Blightbuster** [comment]
Fixed in final release. Thanks for reporting.

**Comment by gyfprivate** [comment]
> Fixed in final release. Thanks for reporting.

My other code also has the same problem, can you tell me which version is fixed?
