### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by Bakuritsuki** [RatScanner/RatScanner#297]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
System.DllNotFoundException: Dll was not found.
   at __std_type_info_destroy_list(__type_info_node* )
   at __scrt_uninitialize_type_info()
   at _app_exit_callback()
   at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
   at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
   at System.AppContext.OnProcessExit()
```
<details>
<summary>Log</summary>

```
[13:09:37.6019498] > [Info]  ----- RatScanner 3.1.0 -----
[13:09:37.6021731] > [Info]  Starting RatScanner...
[13:09:37.6021806] > [Info]  Checking for new updates...
[13:09:37.6107048] > [Info]  Loading resource "RSClientVersion"...
[13:09:38.2373413] > [Info]  Loading config...
[13:09:38.2390062] > [Info]  Loading item data...
[13:09:38.2397957] > [Info]  Loading resource "RSItemDataVersion"...
[13:09:38.3622412] > [Info]  A new item data version is available: 20211216
[13:09:38.3622539] > [Info]  Loading resource "RSItemDataLink"...
[13:09:38.4824677] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[13:09:51.9395934] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json" failed.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dimab\AppData\Local\Temp\Rar$EXa20632.2598\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
[13:10:04.1365852] > [Info]  Loading resource "RSFAQLink"...
[13:10:12.0395029] > [Info]  Loading resource "RSGithubLink"...
[13:10:12.1817971] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.DllNotFoundException: Dll was not found.
   at __std_type_info_destroy_list(__type_info_node* )
   at __scrt_uninitialize_type_info()
   at _app_exit_callback()
   at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
   at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
   at System.AppContext.OnProcessExit()

```
</details>

**Comment by Blightbuster** [comment]
Looks like your anti virus is blocking rat scanner. Please try disabling it or adding a exception.

**Comment by Blightbuster** [comment]
You are running `RatScanner.exe` from within the zip file. You need to extract the zip file first and then run `RatScanner.exe`.
