### ISSUE TITLE
C:\Users\gavri\OneDrive\Рабочий стол\qwerty\RatUpdater.exe could not be found! Please update manually.

### ISSUE THREAD

**Issue by ProstoGavrik** [RatScanner/RatScanner#305]
**Error**
C:\Users\gavri\OneDrive\Рабочий стол\qwerty\RatUpdater.exe could not be found! Please update manually.
<details>
<summary>Log</summary>

```
[12:41:50.2132277] > [Info]  ----- RatScanner 3.1.0 -----
[12:41:50.2134385] > [Info]  Starting RatScanner...
[12:41:50.2134478] > [Info]  Checking for new updates...
[12:41:50.2245860] > [Info]  Loading resource "RSClientVersion"...
[12:41:50.8990613] > [Info]  A new version is available: 3.2.1
[12:41:55.4052566] > [Error] C:\Users\gavri\OneDrive\Рабочий стол\qwerty\RatUpdater.exe could not be found! Please update manually.
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.RatScannerMain.UpdateRatScanner()
   at RatScanner.RatScannerMain.CheckForUpdates()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__8_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext
```
</details>

**Comment by struers-cge** [comment]
+1

**Comment by Blightbuster** [comment]
Hey, please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#ratupdaterexe-could-not-be-found-please-update-manually).
