### ISSUE TITLE
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)

### ISSUE THREAD

**Issue by GJSGLOVE** [RatScanner/RatScanner#306]
**Error**
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
```
System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1674_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at OpenCvSharp.Mat.MatchTemplate(InputArray templ, TemplateMatchModes method, InputArray mask)
   at RatEye.Processing.Icon.<>c__DisplayClass39_0.<TemplateMatchSub>b__0(KeyValuePair`2 icon)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator&
```
<details>
<summary>Log</summary>

```
[14:46:54.1424499] > [Info]  ----- RatScanner 3.2.1 -----
[14:46:54.1426394] > [Info]  Starting RatScanner...
[14:46:54.1426416] > [Info]  Checking for updates...
[14:46:54.1454896] > [Info]  Loading resource "RSClientVersion"...
[14:46:55.0513246] > [Info]  Loading config...
[14:46:55.0525909] > [Info]  Checking for item data updates...
[14:46:55.0529580] > [Info]  Loading resource "RSItemDataBundleVersion"...
[14:46:55.2482765] > [Info]  Loading progress data...
[14:46:55.6879389] > [Info]  Loading price data...
[14:46:56.4937752] > [Info]  Initializing RatEye...
[14:46:59.5189269] > [Info]  Setting default item...
[14:46:59.5839185] > [Info]  Initializing hotkey manager...
[14:46:59.5858400] > [Info]  Setting up data update routines...
[14:46:59.5858636] > [Info]  Ready!
[14:47:17.1905141] > [Error] One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 -------------------- 
 System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1674_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at OpenCvSharp.Mat.MatchTemplate(InputArray templ, TemplateMatchModes method, InputArray mask)
   at RatEye.Processing.Icon.<>c__DisplayClass39_0.<TemplateMatchSub>b__0(KeyValuePair`2 icon)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
```
</details>
Error when scanning drinks, syringes, cigarettes, etc.

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue.
