### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by RipeakeD** [RatScanner/RatScanner#308]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
Newtonsoft.Json.JsonReaderException: Error parsing Infinity value. Path '', line 1, position 2.
   at Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(ReadType readType, Boolean matched)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 123
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 23
   at RatScanner.RatScannerM
```
<details>
<summary>Log</summary>

```
[15:54:02.2133022] > [Info]  ----- RatScanner 3.2.1 -----
[15:54:02.2135062] > [Info]  Starting RatScanner...
[15:54:02.2135099] > [Info]  Checking for updates...
[15:54:02.2160697] > [Info]  Loading resource "RSClientVersion"...
[15:54:02.8141793] > [Info]  Loading config...
[15:54:02.8152450] > [Info]  Checking for item data updates...
[15:54:02.8156316] > [Info]  Loading resource "RSItemDataBundleVersion"...
[15:54:02.9170559] > [Info]  Loading TarkovTracker...
[15:54:03.9777054] > [Info]  Loading progress data...
[15:54:04.2733463] > [Info]  Loading price data...
[15:54:04.7190162] > [Info]  Initializing RatEye...
[15:54:08.8893254] > [Info]  Setting default item...
[15:54:08.9833625] > [Info]  Initializing hotkey manager...
[15:54:08.9856745] > [Info]  Setting up data update routines...
[15:54:08.9857534] > [Info]  Ready!
[15:54:12.4778589] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:12.4787509] > [Debug] NameScan:274 -> Name scanning at: (-275, 1222)
[15:54:14.0076989] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:14.0077686] > [Debug] NameScan:274 -> Name scanning at: (2072, 1469)
[15:54:14.1477271] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:14.1478071] > [Debug] NameScan:274 -> Name scanning at: (2072, 1469)
[15:54:15.3708751] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:15.3709621] > [Debug] NameScan:274 -> Name scanning at: (1269, 594)
[15:54:21.9955542] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:21.9957692] > [Debug] NameScan:274 -> Name scanning at: (-387, 1490)
[15:54:33.8425608] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:33.8426451] > [Debug] NameScan:274 -> Name scanning at: (-3144, 27)
[15:54:35.4665229] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:35.4666161] > [Debug] NameScan:274 -> Name scanning at: (1356, 1496)
[15:54:37.3744882] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:37.3746195] > [Debug] NameScan:274 -> Name scanning at: (1723, 1542)
[15:54:37.5196804] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:37.5197486] > [Debug] NameScan:274 -> Name scanning at: (1723, 1542)
[15:54:56.3733182] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:56.3735026] > [Debug] NameScan:274 -> Name scanning at: (1789, 1089)
[15:54:56.5193870] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:56.5194987] > [Debug] NameScan:274 -> Name scanning at: (1791, 1089)
[15:54:57.9993360] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:57.9994065] > [Debug] NameScan:274 -> Name scanning at: (2565, 602)
[15:54:58.8082860] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:58.8083645] > [Debug] NameScan:274 -> Name scanning at: (1786, 1080)
[15:54:58.9474558] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:54:58.9475427] > [Debug] NameScan:274 -> Name scanning at: (1786, 1080)
[15:55:00.0252859] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:55:00.0253439] > [Debug] NameScan:274 -> Name scanning at: (1275, 606)
[15:55:03.4812833] > [Debug] OnKeyUp:96 -> Pressed: Left
[15:55:03.4813719] > [Debug] NameScan:274 -> Name scanning at: (-315, 1464)
[15:55:11.0852696] > [Debug] OnKeyUp:
```
</details>

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue.
