### ISSUE TITLE
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)

### ISSUE THREAD

**Issue by KekFish** [RatScanner/RatScanner#313]
**Error**
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
```
System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1674_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at OpenCvSharp.Mat.MatchTempla
```
<details>
<summary>Log</summary>

```
[21:09:57.9109723] > [Info]  ----- RatScanner 3.2.1 -----
[21:09:57.9112885] > [Info]  Starting RatScanner...
[21:09:57.9112908] > [Info]  Checking for updates...
[21:09:57.9220873] > [Info]  Loading resource "RSClientVersion"...
[21:09:58.9154903] > [Info]  Loading config...
[21:09:58.9180176] > [Info]  Checking for item data updates...
[21:09:58.9186626] > [Info]  Loading resource "RSItemDataBundleVersion"...
[21:09:59.0440292] > [Info]  Loading TarkovTracker...
[21:10:00.1297886] > [Info]  Loading progress data...
[21:10:00.4203583] > [Info]  Loading price data...
[21:10:01.6683887] > [Info]  Initializing RatEye...
[21:10:13.3617088] > [Info]  Setting default item...
[21:10:13.4816130] > [Info]  Initializing hotkey manager...
[21:10:13.4837090] > [Info]  Setting up data update routines...
[21:10:13.4837234] > [Info]  Ready!
[21:11:44.3207244] > [Error] One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 -------------------- 
 System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1674_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at OpenCvSharp.Mat.MatchTemplate(InputArray templ, TemplateMatchModes method, InputArray mask)
   at RatEye.Processing.Icon.<>c__DisplayClass39_0.<TemplateMatchSub>b__0(KeyValuePair`2 icon)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Ta
```
</details>

**Comment by KekFish** [comment]
Happened when tried to image inspect flashdrive in my docs case inside gamma

**Comment by Blightbuster** [comment]
Could you attach a screenshot of your inventory which has the docs case inside your gamma with the flashdrive open? That way, I would be able to test it myself and reproduce the error.

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue.
