### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by JoshAlvarado** [RatScanner/RatScanner#316]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 123
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 23
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.ExecutionConte
```
<details>
<summary>Log</summary>

```
[05:36:35.2608065] > [Info]  ----- RatScanner 3.2.1 -----
[05:36:35.2610562] > [Info]  Starting RatScanner...
[05:36:35.2610586] > [Info]  Checking for updates...
[05:36:35.2666057] > [Info]  Loading resource "RSClientVersion"...
[05:36:35.9960348] > [Info]  Loading config...
[05:36:35.9977489] > [Info]  Checking for item data updates...
[05:36:35.9995578] > [Info]  Loading resource "RSItemDataBundleVersion"...
[05:36:36.0838174] > [Info]  Loading TarkovTracker...
[05:36:37.0958224] > [Info]  Loading progress data...
[05:36:37.5286371] > [Info]  Loading price data...
[05:36:37.8930987] > [Info]  Initializing RatEye...
[05:36:43.2544347] > [Info]  Setting default item...
[05:36:43.3360776] > [Info]  Initializing hotkey manager...
[05:36:43.3381671] > [Info]  Setting up data update routines...
[05:36:43.3381816] > [Info]  Ready!
[05:41:43.3578443] > [Info]  Refreshing TarkovTracker DB...
[05:46:43.8622853] > [Info]  Refreshing TarkovTracker DB...
[05:51:44.4251677] > [Info]  Refreshing TarkovTracker DB...
[05:56:45.1021131] > [Info]  Refreshing TarkovTracker DB...
[06:01:47.0736478] > [Info]  Refreshing TarkovTracker DB...
[06:06:43.3481903] > [Info]  Refreshing Market DB...
[06:06:51.7095815] > [Info]  Refreshing TarkovTracker DB...
[06:11:56.4835914] > [Info]  Refreshing TarkovTracker DB...
[06:16:57.0839475] > [Info]  Refreshing TarkovTracker DB...
[06:22:02.2592671] > [Info]  Refreshing TarkovTracker DB...
[06:27:02.8461772] > [Info]  Refreshing TarkovTracker DB...
[06:32:03.3371091] > [Info]  Refreshing TarkovTracker DB...
[06:36:43.9222597] > [Info]  Refreshing Market DB...
[06:37:08.1850676] > [Info]  Refreshing TarkovTracker DB...
[06:42:08.8258437] > [Info]  Refreshing TarkovTracker DB...
[06:47:14.5857738] > [Info]  Refreshing TarkovTracker DB...
[06:52:15.1156144] > [Info]  Refreshing TarkovTracker DB...
[06:57:15.6953561] > [Info]  Refreshing TarkovTracker DB...
[07:02:16.2174620] > [Info]  Refreshing TarkovTracker DB...
[07:06:44.5076224] > [Info]  Refreshing Market DB...
[07:07:16.8518506] > [Info]  Refreshing TarkovTracker DB...
[07:12:22.5586153] > [Info]  Refreshing TarkovTracker DB...
[07:17:23.0695064] > [Info]  Refreshing TarkovTracker DB...
[07:18:51.6130389] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6131870] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6132175] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6132491] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6134951] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6135239] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6137949] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6138242] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6141131] > [Warning] Could not find item with uid: 5a294d8486f774068638cd93
[07:18:51.6142475] > [Warnin
```
</details>

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue.
