### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by xNarkon** [RatScanner/RatScanner#317]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Pr
```
<details>
<summary>Log</summary>

```
[10:25:21.8736841] > [Info]  ----- RatScanner 3.2.1 -----
[10:25:21.8738695] > [Info]  Starting RatScanner...
[10:25:21.8738724] > [Info]  Checking for updates...
[10:25:21.8758285] > [Info]  Loading resource "RSClientVersion"...
[10:25:22.4512576] > [Info]  Loading config...
[10:25:22.4530694] > [Info]  Checking for item data updates...
[10:25:22.4536241] > [Info]  Loading resource "RSItemDataBundleVersion"...
[10:25:22.5659421] > [Info]  Loading TarkovTracker...
[10:25:26.6458626] > [Info]  Loading progress data...
[10:25:27.0487880] > [Info]  Loading price data...
[10:25:27.5136695] > [Info]  Initializing RatEye...
[10:25:30.6050542] > [Info]  Setting default item...
[10:25:30.7427966] > [Info]  Initializing hotkey manager...
[10:25:30.7447031] > [Info]  Setting up data update routines...
[10:25:30.7447181] > [Info]  Ready!
[10:30:30.7487589] > [Info]  Refreshing TarkovTracker DB...
[10:35:33.2629249] > [Info]  Refreshing TarkovTracker DB...
[10:40:33.8878667] > [Info]  Refreshing TarkovTracker DB...
[10:45:34.7889246] > [Info]  Refreshing TarkovTracker DB...
[10:50:39.1796048] > [Info]  Refreshing TarkovTracker DB...
[10:55:30.7579726] > [Info]  Refreshing Market DB...
[10:55:44.0806181] > [Info]  Refreshing TarkovTracker DB...
[10:55:44.7649032] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 22
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
[11:12:13.1451053] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue and especially the PR. ❤️
