### ISSUE TITLE
Unhandled exception (TaskScheduler.UnobservedTaskException)

### ISSUE THREAD

**Issue by seler** [RatScanner/RatScanner#320]
I've got my RatScanner connected to TarkovTracker. I assume this might be connected to my current state on tarkovtracker so I'm enclosing [progress export](https://github.com/RatScanner/RatScanner/files/7960273/tarkovtrackersave.txt).

![image](https://user-images.githubusercontent.com/255675/151585613-d4238b3b-e5a9-46b7-824c-9680f937149a.png)

**Error**
Unhandled exception (TaskScheduler.UnobservedTaskException)
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unexpected character encountered while parsing value: E. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeO
```
<details>
<summary>Log</summary>

```
[16:32:55.0721715] > [Info]  ----- RatScanner 3.2.1 -----
[16:32:55.0723551] > [Info]  Starting RatScanner...
[16:32:55.0723583] > [Info]  Checking for updates...
[16:32:55.0750883] > [Info]  Loading resource "RSClientVersion"...
[16:32:55.6358544] > [Info]  Loading config...
[16:32:55.6375285] > [Info]  Checking for item data updates...
[16:32:55.6380350] > [Info]  Loading resource "RSItemDataBundleVersion"...
[16:32:55.7350554] > [Info]  Loading TarkovTracker...
[16:33:01.2883390] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 22
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__8_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope servic
```
</details>

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue.
