### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by djodars89** [RatScanner/RatScanner#321]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Pr
```
<details>
<summary>Log</summary>

```
[15:20:35.8684719] > [Info]  ----- RatScanner 3.2.1 -----
[15:20:35.8686465] > [Info]  Starting RatScanner...
[15:20:35.8686490] > [Info]  Checking for updates...
[15:20:35.8705783] > [Info]  Loading resource "RSClientVersion"...
[15:20:36.0931139] > [Info]  Loading config...
[15:20:36.0948700] > [Info]  Checking for item data updates...
[15:20:36.0952558] > [Info]  Loading resource "RSItemDataBundleVersion"...
[15:20:36.1286562] > [Info]  Loading TarkovTracker...
[15:20:42.1477039] > [Info]  Loading progress data...
[15:20:42.3016648] > [Info]  Loading price data...
[15:20:42.4147133] > [Info]  Initializing RatEye...
[15:20:48.3544315] > [Info]  Setting default item...
[15:20:48.6440938] > [Info]  Initializing hotkey manager...
[15:20:48.6462927] > [Info]  Setting up data update routines...
[15:20:48.6727681] > [Info]  Ready!
[15:25:48.6524046] > [Info]  Refreshing TarkovTracker DB...
[15:30:53.3944338] > [Info]  Refreshing TarkovTracker DB...
[15:30:53.9211784] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 22
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
[15:50:48.6634698] > [Info]  Refreshing Market DB...
[16:20:48.8080336] > [Info]  Refreshing Market DB...
[16:50:49.0499756] > [Info]  Refreshing Market DB...
[17:20:49.1890393] > [Info]  Refreshing Market DB...
[17:50:49.3761229] > [Info]  Refreshing Market DB...
[18:20:49.5111502] > [Info]  Refreshing Market DB...

```
</details>

**Comment by Elec0** [comment]
I also have this error that pops up.
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Pr
```
<details>
<summary>Log</summary>

```
[04:49:32.8442193] > [Info]  ----- RatScanner 3.2.1 -----
[04:49:32.8443992] > [Info]  Starting RatScanner...
[04:49:32.8444030] > [Info]  Checking for updates...
[04:49:32.8471116] > [Info]  Loading resource "RSClientVersion"...
[04:49:33.4246754] > [Info]  Loading config...
[04:49:33.4257329] > [Info]  Checking for item data updates...
[04:49:33.4262021] > [Info]  Loading resource "RSItemDataBundleVersion"...
[04:49:33.5058515] > [Info]  Loading TarkovTracker...
[04:49:44.7844903] > [Info]  Loading progress data...
[04:49:45.1786228] > [Info]  Loading price data...
[04:49:45.5486148] > [Info]  Initializing RatEye...
[04:49:51.2536341] > [Info]  Setting default item...
[04:49:51.3280256] > [Info]  Initializing hotkey manager...
[04:49:51.3307467] > [Info]  Setting up data update routines...
[04:49:51.3307621] > [Info]  Ready!
[04:54:51.3490035] > [Info]  Refreshing TarkovTracker DB...
[04:59:52.0034345] > [Info]  Refreshing TarkovTracker DB...
[05:04:52.4716874] > [Info]  Refreshing TarkovTracker DB...
[05:04:53.4658207] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 22
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
[05:09:57.9888933] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue.
