### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by Jaidan** [RatScanner/RatScanner#322]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Pr
```
<details>
<summary>Log</summary>

```
[02:45:23.4092536] > [Info]  ----- RatScanner 3.2.1 -----
[02:45:23.4094578] > [Info]  Starting RatScanner...
[02:45:23.4094609] > [Info]  Checking for updates...
[02:45:23.4117967] > [Info]  Loading resource "RSClientVersion"...
[02:45:23.8815242] > [Info]  Loading config...
[02:45:23.8826232] > [Info]  Checking for item data updates...
[02:45:23.8831238] > [Info]  Loading resource "RSItemDataBundleVersion"...
[02:45:23.9510078] > [Info]  Loading TarkovTracker...
[02:45:41.2699415] > [Warning] TarkovTracker API Token invalid!

Please provide a new token.
[02:45:44.4937498] > [Info]  Loading progress data...
[02:45:44.7888573] > [Info]  Loading price data...
[02:45:45.1111510] > [Info]  Initializing RatEye...
[02:46:21.5802083] > [Info]  Setting default item...
[02:46:21.6348806] > [Info]  Initializing hotkey manager...
[02:46:21.6366069] > [Info]  Setting up data update routines...
[02:46:21.6366232] > [Info]  Ready!
[02:51:21.6491408] > [Info]  Refreshing TarkovTracker DB...
[02:56:23.4327199] > [Info]  Refreshing TarkovTracker DB...
[03:01:24.9207130] > [Info]  Refreshing TarkovTracker DB...
[03:06:31.8490469] > [Info]  Refreshing TarkovTracker DB...
[03:11:32.9265851] > [Info]  Refreshing TarkovTracker DB...
[03:16:21.6408574] > [Info]  Refreshing Market DB...
[03:16:34.3507859] > [Info]  Refreshing TarkovTracker DB...
[03:21:35.4175642] > [Info]  Refreshing TarkovTracker DB...
[03:26:41.2332087] > [Info]  Refreshing TarkovTracker DB...
[03:31:44.0310189] > [Info]  Refreshing TarkovTracker DB...
[03:36:46.3787201] > [Info]  Refreshing TarkovTracker DB...
[03:36:48.2408657] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 22
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, C
```
</details>

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue.
