### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by vaiels** [RatScanner/RatScanner#323]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Pr
```
<details>
<summary>Log</summary>

```
[03:50:22.3271134] > [Info]  ----- RatScanner 3.2.1 -----
[03:50:22.3273360] > [Info]  Starting RatScanner...
[03:50:22.3273385] > [Info]  Checking for updates...
[03:50:22.3319817] > [Info]  Loading resource "RSClientVersion"...
[03:50:23.5579543] > [Info]  Loading config...
[03:50:23.5601201] > [Info]  Checking for item data updates...
[03:50:23.5620331] > [Info]  Loading resource "RSItemDataBundleVersion"...
[03:50:23.8007484] > [Info]  Loading TarkovTracker...
[03:50:25.6690387] > [Info]  Loading progress data...
[03:50:26.2556733] > [Info]  Loading price data...
[03:50:27.2576539] > [Info]  Initializing RatEye...
[03:50:33.9287614] > [Info]  Setting default item...
[03:50:34.2013220] > [Info]  Initializing hotkey manager...
[03:50:34.2068343] > [Info]  Setting up data update routines...
[03:50:34.2071617] > [Info]  Ready!
[03:55:34.2266850] > [Info]  Refreshing TarkovTracker DB...
[04:00:35.2937822] > [Info]  Refreshing TarkovTracker DB...
[04:05:36.4305615] > [Info]  Refreshing TarkovTracker DB...
[04:10:37.3265722] > [Info]  Refreshing TarkovTracker DB...
[04:15:44.3058752] > [Info]  Refreshing TarkovTracker DB...
[04:20:34.2143763] > [Info]  Refreshing Market DB...
[04:20:49.4838124] > [Info]  Refreshing TarkovTracker DB...
[04:25:56.4732720] > [Info]  Refreshing TarkovTracker DB...
[04:31:03.6454561] > [Info]  Refreshing TarkovTracker DB...
[04:36:04.8906421] > [Info]  Refreshing TarkovTracker DB...
[04:36:06.6730543] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 89
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 22
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
[04:36:32.0967916]
```
</details>

**Comment by Blightbuster** [comment]
Fixed in the latest release.

Either use the automatic updater of RatScanner or download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).

Thanks for creating the issue.
