### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by inaeven** [RatScanner/RatScanner#328]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\прога таркова\Data\icons\correlation.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, 
```
<details>
<summary>Log</summary>

```
[14:59:07.1313586] > [Info]  ----- RatScanner 3.2.1 -----
[14:59:07.1313731] > [Info]  Starting RatScanner...
[14:59:07.1313758] > [Info]  Checking for updates...
[14:59:07.1344024] > [Info]  Loading resource "RSClientVersion"...
[14:59:07.8772580] > [Info]  Loading config...
[14:59:07.8800511] > [Info]  Checking for item data updates...
[14:59:07.8807498] > [Info]  Loading resource "RSItemDataBundleVersion"...
[14:59:08.0075485] > [Info]  A new item data bundle is available: 20220118
[14:59:08.0075719] > [Info]  Loading resource "RSItemDataBundleLink"...
[14:59:08.1337578] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2021-12-29.zip"...
[14:59:24.7821058] > [Info]  Successfully updated to the latest item data bundle
[14:59:24.7825099] > [Info]  Loading progress data...
[14:59:24.8054747] > [Error] Unhandled exception (TaskScheduler.UnobservedTaskException)
 -------------------- 
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Системе не удается найти указанный путь. (0x80070003))
 ---> System.IO.DirectoryNotFoundException: Системе не удается найти указанный путь. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass4_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   --- End of inner exception stack trace ---
[14:59:25.1165743] > [Info]  Loading price data...
[14:59:25.5772479] > [Info]  Initializing RatEye...
[14:59:25.8150177] > [Info]  Loading resource "RSFAQLink"...
[14:59:28.6074862] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\прога таркова\Data\icons\correlation.json'.
   at Microsoft.Win32.SafeHandles.SafeFil
```
</details>

**Comment by Blightbuster** [comment]
Hey, are you trying to build the project your self?

If you just want to use it, you can download the latest version [here](https://github.com/RatScanner/RatScanner/releases/latest/download/RatScanner.zip).
