### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by RebKut** [RatScanner/RatScanner#332]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.InvalidOperationException: Нельзя задать Visibility или вызвать Show, ShowDialog или WindowInteropHelper.EnsureHandle после закрытия окна.
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.View.MinimalMenu.OnMouseDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Control.OnMouseDoubleClick(MouseButtonEventArgs e)
   at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Bo
```
<details>
<summary>Log</summary>

```
[18:34:08.3872815] > [Info]  ----- RatScanner 3.2.2 -----
[18:34:08.3874735] > [Info]  Starting RatScanner...
[18:34:08.3874767] > [Info]  Checking for updates...
[18:34:08.3897505] > [Info]  Loading resource "RSClientVersion"...
[18:34:08.8752047] > [Info]  Loading config...
[18:34:08.8764796] > [Info]  Checking for item data updates...
[18:34:08.8769244] > [Info]  Loading resource "RSItemDataBundleVersion"...
[18:34:09.0111528] > [Info]  Loading progress data...
[18:34:09.4744331] > [Info]  Loading price data...
[18:34:09.9554472] > [Info]  Initializing RatEye...
[18:34:13.6824637] > [Info]  Setting default item...
[18:34:13.7392423] > [Info]  Initializing hotkey manager...
[18:34:13.7413801] > [Info]  Setting up data update routines...
[18:34:13.7413965] > [Info]  Ready!
[18:39:13.7495872] > [Info]  Refreshing TarkovTracker DB...
[18:40:50.4880070] > [Info]  Loading resource "RSGithubLink"...
[18:44:13.7602908] > [Info]  Refreshing TarkovTracker DB...
[18:49:13.7648491] > [Info]  Refreshing TarkovTracker DB...
[18:54:13.7653526] > [Info]  Refreshing TarkovTracker DB...
[18:59:13.7704944] > [Info]  Refreshing TarkovTracker DB...
[19:04:13.7621695] > [Info]  Refreshing Market DB...
[19:04:13.7779909] > [Info]  Refreshing TarkovTracker DB...
[19:09:13.7892942] > [Info]  Refreshing TarkovTracker DB...
[19:14:13.7945667] > [Info]  Refreshing TarkovTracker DB...
[19:19:13.8063536] > [Info]  Refreshing TarkovTracker DB...
[19:24:13.8294444] > [Info]  Refreshing TarkovTracker DB...
[19:29:13.8326974] > [Info]  Refreshing TarkovTracker DB...
[19:34:13.8395974] > [Info]  Refreshing TarkovTracker DB...
[19:34:14.4606134] > [Info]  Refreshing Market DB...
[19:39:13.8614810] > [Info]  Refreshing TarkovTracker DB...
[19:44:13.8636699] > [Info]  Refreshing TarkovTracker DB...
[19:49:13.8678614] > [Info]  Refreshing TarkovTracker DB...
[19:54:13.8721853] > [Info]  Refreshing TarkovTracker DB...
[19:59:13.8734183] > [Info]  Refreshing TarkovTracker DB...
[20:04:13.8882815] > [Info]  Refreshing TarkovTracker DB...
[20:04:15.2042842] > [Info]  Refreshing Market DB...
[20:09:13.8900705] > [Info]  Refreshing TarkovTracker DB...
[20:14:13.9012172] > [Info]  Refreshing TarkovTracker DB...
[20:19:13.9159268] > [Info]  Refreshing TarkovTracker DB...
[20:24:13.9275762] > [Info]  Refreshing TarkovTracker DB...
[20:29:13.9411941] > [Info]  Refreshing TarkovTracker DB...
[20:34:13.9487133] > [Info]  Refreshing TarkovTracker DB...
[20:34:15.9029886] > [Info]  Refreshing Market DB...
[20:39:13.9745918] > [Info]  Refreshing TarkovTracker DB...
[20:44:13.9803156] > [Info]  Refreshing TarkovTracker DB...
[20:49:13.9926861] > [Info]  Refreshing TarkovTracker DB...
[20:52:36.2464864] > [Warning] Could not find item with uid: 5909d36d86f774660f0bb900
[20:52:36.2466809] > [Warning] Could not find item with uid: 5909d36d86f774660f0bb900
[20:52:36.2467197] > [Warning] Could not find item with uid: 5909d36d86f774660f0bb900
[20:52:36.2467477] > [Warning] Could not find item with uid: 
```
</details>

**Comment by Blightbuster** [comment]
Hey, can you please try if this issue still persists in the latest version (v3.3.1)?

**Comment by Blightbuster** [comment]
Please comment if the issue persists and I'll reopen it.
