### ISSUE TITLE
Unhandled exception (TaskScheduler.UnobservedTaskException)

### ISSUE THREAD

**Issue by Never91** [RatScanner/RatScanner#334]
**Error**
Unhandled exception (TaskScheduler.UnobservedTaskException)
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Access to the path 'C:\Users\Max\Desktop\RatScaner\Log.txt' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Max\Desktop\RatScaner\Log.txt' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at RatScanner.Logger.Clear()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__8_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Mic
```
<details>
<summary>Log</summary>

```
[14:59:47.8454012] > [Info]  ----- RatScanner 3.2.2 -----
[14:59:47.8454129] > [Info]  Starting RatScanner...
[14:59:47.8454177] > [Info]  Checking for updates...
[14:59:47.8479097] > [Info]  Loading resource "RSClientVersion"...
[14:59:48.6317440] > [Info]  Loading config...
[14:59:48.6339239] > [Info]  Checking for item data updates...
[14:59:48.6345132] > [Info]  Loading resource "RSItemDataBundleVersion"...
[14:59:48.7643392] > [Info]  Loading progress data...
[14:59:49.0623998] > [Info]  Loading price data...
[14:59:49.6326045] > [Info]  Initializing RatEye...
[14:59:54.3194311] > [Info]  Setting default item...
[14:59:54.3833710] > [Info]  Initializing hotkey manager...
[14:59:54.3859310] > [Info]  Setting up data update routines...
[14:59:54.3859608] > [Info]  Ready!

```
</details>

**Comment by Blightbuster** [comment]
Looks like your anti virus is blocking Rat Scanner. Please try to disable your anti virus and check if that solves it. If it does, you can simply  add an exception in it for `RatScanner.exe` and `RatUpdater.exe`.
