### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by Vasili-Terkin** [RatScanner/RatScanner#340]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.ItemExtensions.GetMarketItem(Item item)
   at RatScanner.ViewModel.MainWindowVM.get_IconLink()
   at RatRazor.Pages.App.Index.<BuildRenderTree>b__0_1(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudItem.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.HandleException(Exc
```
<details>
<summary>Log</summary>

```
[20:43:09.4935372] > [Info]  ----- RatScanner 3.2.2 -----
[20:43:09.4938069] > [Info]  Starting RatScanner...
[20:43:09.4938109] > [Info]  Checking for updates...
[20:43:09.4969865] > [Info]  Loading resource "RSClientVersion"...
[20:43:10.0849406] > [Info]  Loading config...
[20:43:10.0870285] > [Info]  Checking for item data updates...
[20:43:10.0877695] > [Info]  Loading resource "RSItemDataBundleVersion"...
[20:43:10.4216362] > [Info]  Loading progress data...
[20:43:10.7676308] > [Info]  Loading price data...
[20:43:12.0746450] > [Info]  Initializing RatEye...
[20:43:14.9184057] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Games\сканер предметов тарков\Data\icons\correlation.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at RatEye.IconManager.ReadFileNonBlocking(String path)
   at RatEye.IconManager.LoadStaticCorrelationData()
   at RatEye.IconManager.LoadStaticIcons()
   at RatEye.IconManager..ctor(Config config)
   at RatEye.RatEyeEngine..ctor(Config config)
   at RatScanner.RatScannerMain.SetupRatEye()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__8_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInj
```
</details>

**Comment by Blightbuster** [comment]
Hey, did you try to compile rat scanner yourself?

**Comment by Blightbuster** [comment]
I assume you did and forgot to copy over the data folder.
Please comment if this is not the case and I will reopen the issue.
