### ISSUE TITLE
Unhandled exception (TaskScheduler.UnobservedTaskException)

### ISSUE THREAD

**Issue by Rastard1** [RatScanner/RatScanner#342]
**Error**
Unhandled exception (TaskScheduler.UnobservedTaskException)
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot provide a value for property 'TarkovTrackerDB' on type 'RatRazor.Pages.App.Index'. There is no registered service of type 'RatTracking.TarkovTrackerDB'.)
 ---> System.InvalidOperationException: Cannot provide a value for property 'TarkovTrackerDB' on type 'RatRazor.Pages.App.Index'. There is no registered service of type 'RatTracking.TarkovTrackerDB'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type compone
```
<details>
<summary>Log</summary>

```
[19:23:26.7061097] > [Info]  ----- RatScanner 3.2.2 -----
[19:23:26.7061200] > [Info]  Starting RatScanner...
[19:23:26.7061223] > [Info]  Checking for updates...
[19:23:26.7083556] > [Info]  Loading resource "RSClientVersion"...
[19:23:27.3872412] > [Info]  Loading config...
[19:23:27.3893356] > [Info]  Checking for item data updates...
[19:23:27.3899025] > [Info]  Loading resource "RSItemDataBundleVersion"...
[19:23:27.4975823] > [Info]  Loading progress data...
[19:23:27.9063505] > [Info]  Loading price data...
[19:23:28.4116839] > [Info]  Initializing RatEye...
[19:23:33.4006070] > [Info]  Setting default item...
[19:23:33.4626104] > [Info]  Initializing hotkey manager...
[19:23:33.4649743] > [Info]  Setting up data update routines...
[19:23:33.4650043] > [Info]  Ready!
[19:23:54.3190949] > [Info]  Saving config...
[19:23:54.3235742] > [Info]  Config saved!
[19:28:33.4747759] > [Info]  Refreshing TarkovTracker DB...
[19:33:33.9186756] > [Info]  Refreshing TarkovTracker DB...
[19:38:34.2923602] > [Info]  Refreshing TarkovTracker DB...
[19:43:34.9083837] > [Info]  Refreshing TarkovTracker DB...
[19:48:35.4281125] > [Info]  Refreshing TarkovTracker DB...
[19:51:09.2165910] > [Info]  Saving config...
[19:51:09.2211959] > [Info]  Config saved!
[19:53:33.4801328] > [Info]  Refreshing Market DB...
[19:53:35.8760160] > [Info]  Refreshing TarkovTracker DB...
[19:58:41.2298650] > [Info]  Refreshing TarkovTracker DB...
[20:03:41.6006115] > [Info]  Refreshing TarkovTracker DB...
[20:08:41.9943552] > [Info]  Refreshing TarkovTracker DB...
[20:13:42.5575091] > [Info]  Refreshing TarkovTracker DB...
[20:18:43.0320446] > [Info]  Refreshing TarkovTracker DB...
[20:23:34.2147318] > [Info]  Refreshing Market DB...
[20:23:43.6633347] > [Info]  Refreshing TarkovTracker DB...
[20:28:44.1995343] > [Info]  Refreshing TarkovTracker DB...
[20:33:44.6744080] > [Info]  Refreshing TarkovTracker DB...
[20:38:45.0007362] > [Info]  Refreshing TarkovTracker DB...
[20:43:45.4630050] > [Info]  Refreshing TarkovTracker DB...
[20:48:45.9628277] > [Info]  Refreshing TarkovTracker DB...
[20:53:34.9615986] > [Info]  Refreshing Market DB...
[20:53:46.3079824] > [Info]  Refreshing TarkovTracker DB...
[20:58:46.7074652] > [Info]  Refreshing TarkovTracker DB...
[21:03:47.0872197] > [Info]  Refreshing TarkovTracker DB...
[21:08:47.5148505] > [Info]  Refreshing TarkovTracker DB...
[21:13:52.9633788] > [Info]  Refreshing TarkovTracker DB...
[21:18:53.4445250] > [Info]  Refreshing TarkovTracker DB...
[21:23:35.6864823] > [Info]  Refreshing Market DB...
[21:23:53.8768626] > [Info]  Refreshing TarkovTracker DB...
[21:28:54.3234777] > [Info]  Refreshing TarkovTracker DB...
[21:33:54.8114710] > [Info]  Refreshing TarkovTracker DB...
[21:34:05.9453344] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type typ
```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting the issue, it has since been fixed in version 3.3.1.
You can launch rat scanner and it will ask you to update automatically.
