### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by SlivkaPlum** [RatScanner/RatScanner#344]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(String javaScript)
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass4_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.Invoke
```
<details>
<summary>Log</summary>

```
[13:06:58.1377338] > [Warning] Config version (-1) is not supported!
[13:06:58.1512241] > [Info]  Detected 2560x1440 Resolution.

You can adjust this inside the settings.
[13:06:58.6688311] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: Не удается найти указанный файл. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfWebView2Wrapper.CreateEnvironmentAsync()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass4_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[13:06:58.7510770] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: Не удается найти указанный файл. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfWebView2Wrapper.CreateEnvironmentAsync()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft
```
</details>

**Comment by SlivkaPlum** [comment]
im not trying to build it by myself. Just trying to use it from Download section

**Comment by Blightbuster** [comment]
Please try manually downloading the WebView2 runtime and then after installing it, restart your pc.
https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by TheMockinJay** [comment]
Have the exact issue, WebView2 and reinstall does not work.

**Comment by Blightbuster** [comment]
@TheMockinJay If you have the exact same issue, the problem is that for some reason windows cant locate the WebView2 runtime. Thats either because it isnt installed correctly, some anti-virus is blocking access to it or Rat Scanner having insuficient access rights (starting as admin prevents this).

So I recommend starting as admin if that doesnt work, temporarily disabling your AV and start as admin again. At last if it still cant find the webview2 runtime, the installation of it must be corrupted in some way so try to get rid of it and any traces and then reinstall it (maybe as admin this time).

**Comment by Blightbuster** [comment]
Did this fix the issue?

**Comment by TheMockinJay** [comment]
I don't remember exactly, was so long ago, but I fixed it myself. had to reinstall windows. it was a case of webview2 literally missing.
