### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by SmokeySeven** [RatScanner/RatScanner#347]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at RatTracking.TarkovTrackerDB.UpdateProgression() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 127
   at RatTracking.TarkovTrackerDB.Init() in D:\Programmierung\Projects\RatScanner\RatScanner\RatTracking\TarkovTrackerDB.cs:line 23
   at RatScanner.RatScannerMain.RefreshTarkovTrackerDB(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```
<details>
<summary>Log</summary>

```
[10:01:28.3798535] > [Info]  ----- RatScanner 3.2.2 -----
[10:01:28.3800486] > [Info]  Starting RatScanner...
[10:01:28.3800521] > [Info]  Checking for updates...
[10:01:28.3833098] > [Info]  Loading resource "RSClientVersion"...
[10:01:33.9635947] > [Info]  Loading config...
[10:01:33.9654134] > [Info]  Checking for item data updates...
[10:01:33.9661765] > [Info]  Loading resource "RSItemDataBundleVersion"...
[10:01:35.1128684] > [Info]  Loading TarkovTracker...
[10:01:36.9145575] > [Info]  Loading progress data...
[10:01:37.5944749] > [Info]  Loading price data...
[10:01:41.1381340] > [Info]  Initializing RatEye...
[10:01:46.1942871] > [Info]  Setting default item...
[10:01:46.3108165] > [Info]  Initializing hotkey manager...
[10:01:46.3135888] > [Info]  Setting up data update routines...
[10:01:46.3136119] > [Info]  Ready!
[10:02:10.0867034] > [Info]  Saving config...
[10:02:10.1020631] > [Info]  Config saved!
[10:02:25.1208702] > [Info]  Saving config...
[10:02:25.1348664] > [Info]  Config saved!
[10:03:23.1147157] > [Info]  Saving config...
[10:03:23.1313326] > [Info]  Config saved!
[10:03:28.8865671] > [Info]  Saving config...
[10:03:28.8982697] > [Info]  Config saved!
[10:03:34.5336853] > [Info]  Saving config...
[10:03:34.5469767] > [Info]  Config saved!
[10:06:46.3244220] > [Info]  Refreshing TarkovTracker DB...
[10:11:47.2163970] > [Info]  Refreshing TarkovTracker DB...
[10:16:47.9247183] > [Info]  Refreshing TarkovTracker DB...
[10:21:48.5249002] > [Info]  Refreshing TarkovTracker DB...
[10:26:49.1097122] > [Info]  Refreshing TarkovTracker DB...
[10:31:46.3275865] > [Info]  Refreshing Market DB...
[10:31:49.6791452] > [Info]  Refreshing TarkovTracker DB...
[10:36:50.3255589] > [Info]  Refreshing TarkovTracker DB...
[10:41:50.9261746] > [Info]  Refreshing TarkovTracker DB...
[10:46:51.4033538] > [Info]  Refreshing TarkovTracker DB...
[10:51:51.9116527] > [Info]  Refreshing TarkovTracker DB...
[10:56:52.3730384] > [Info]  Refreshing TarkovTracker DB...
[11:01:50.4822885] > [Info]  Refreshing Market DB...
[11:01:52.9732134] > [Info]  Refreshing TarkovTracker DB...
[11:06:58.9790142] > [Info]  Refreshing TarkovTracker DB...
[11:11:59.4664624] > [Info]  Refreshing TarkovTracker DB...
[11:16:59.9537553] > [Info]  Refreshing TarkovTracker DB...
[11:22:00.6147720] > [Info]  Refreshing TarkovTracker DB...
[11:27:01.0551821] > [Info]  Refreshing TarkovTracker DB...
[11:32:00.6209310] > [Info]  Refreshing Market DB...
[11:32:03.6793395] > [Info]  Refreshing TarkovTracker DB...
[11:37:04.3349890] > [Info]  Refreshing TarkovTracker DB...
[11:42:04.9554913] > [Info]  Refreshing TarkovTracker DB...
[11:47:05.5278742] > [Info]  Refreshing TarkovTracker DB...
[11:52:06.0096969] > [Info]  Refreshing TarkovTracker DB...
[11:57:06.5538575] > [Info]  Refreshing TarkovTracker DB...
[12:02:02.4840326] > [Info]  Refreshing Market DB...
[12:02:07.1112550] > [Info]  Refreshing TarkovTracker DB...
[12:07:07.5934875] > [Info]  Refreshing TarkovTracker DB...
[12:
```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting the issue, it has since been fixed in version 3.3.1.
You can launch rat scanner and it will ask you to update automatically.
