### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by n1komo** [RatScanner/RatScanner#349]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\n1komo\Downloads\RatScanner\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, St
```
<details>
<summary>Log</summary>

```
[06:57:35.0277494] > [Info]  ----- RatScanner 3.2.2 -----
[06:57:35.0282360] > [Info]  Starting RatScanner...
[06:57:35.0282429] > [Info]  Checking for updates...
[06:57:35.0396659] > [Info]  Loading resource "RSClientVersion"...
[06:57:36.7000249] > [Info]  Loading config...
[06:57:36.7049076] > [Info]  Checking for item data updates...
[06:57:36.7062021] > [Info]  Loading resource "RSItemDataBundleVersion"...
[06:57:37.2290107] > [Info]  Loading TarkovTracker...
[06:57:38.3868116] > [Info]  Loading progress data...
[06:57:39.0746780] > [Info]  Loading price data...
[06:57:41.3780983] > [Info]  Initializing RatEye...
[06:57:59.9772024] > [Info]  Setting default item...
[06:58:00.1657752] > [Info]  Initializing hotkey manager...
[06:58:00.1708013] > [Info]  Setting up data update routines...
[06:58:00.1708375] > [Info]  Ready!
[06:58:54.0938987] > [Info]  Saving config...
[06:58:54.1887193] > [Info]  Config saved!
[06:59:11.9088336] > [Info]  Saving config...
[06:59:11.9591067] > [Info]  Config saved!
[06:59:31.2058370] > [Info]  Saving config...
[06:59:31.2705399] > [Info]  Config saved!
[06:59:41.1994515] > [Info]  Saving config...
[06:59:41.2494650] > [Info]  Config saved!
[06:59:46.6916426] > [Info]  Saving config...
[06:59:46.7382132] > [Info]  Config saved!
[07:04:21.4592452] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\n1komo\Downloads\RatScanner\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at RatScanner.App.InstallWebview2Runtime()
   at RatScanner.App.OnStartup(StartupEventArgs e)
   at System.Windows.A
```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting the issue, it has since been fixed in version 3.3.1.
You can launch rat scanner and it will ask you to update automatically.
