### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by N0lens** [RatScanner/RatScanner#350]
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\N0lens\Downloads\RatScanner\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, St
```
<details>
<summary>Log</summary>

```
[12:53:55.6694110] > [Info]  ----- RatScanner 3.2.2 -----
[12:53:55.6697863] > [Info]  Starting RatScanner...
[12:53:55.6697900] > [Info]  Checking for updates...
[12:53:55.6780586] > [Info]  Loading resource "RSClientVersion"...
[12:53:57.9473905] > [Info]  Loading config...
[12:53:57.9508930] > [Info]  Checking for item data updates...
[12:53:57.9737580] > [Info]  Loading resource "RSItemDataBundleVersion"...
[12:53:58.6305223] > [Info]  Loading progress data...
[12:54:01.8389850] > [Info]  Loading price data...
[12:54:03.1801117] > [Info]  Initializing RatEye...
[12:54:31.8290516] > [Info]  Setting default item...
[12:54:32.3367227] > [Info]  Initializing hotkey manager...
[12:54:32.3397363] > [Info]  Setting up data update routines...
[12:54:32.3397784] > [Info]  Ready!
[12:59:32.3511528] > [Info]  Refreshing TarkovTracker DB...
[13:04:32.3587072] > [Info]  Refreshing TarkovTracker DB...
[13:09:32.3658179] > [Info]  Refreshing TarkovTracker DB...
[13:14:32.3772708] > [Info]  Refreshing TarkovTracker DB...
[13:19:32.3866221] > [Info]  Refreshing TarkovTracker DB...
[13:24:32.3427196] > [Info]  Refreshing Market DB...
[13:24:32.3906314] > [Info]  Refreshing TarkovTracker DB...
[13:29:32.4003445] > [Info]  Refreshing TarkovTracker DB...
[13:34:32.4150404] > [Info]  Refreshing TarkovTracker DB...
[13:39:32.4157309] > [Info]  Refreshing TarkovTracker DB...
[13:44:15.4214348] > [Info]  Saving config...
[13:44:15.4618337] > [Info]  Config saved!
[13:44:32.4165818] > [Info]  Refreshing TarkovTracker DB...
[13:49:32.4248103] > [Info]  Refreshing TarkovTracker DB...
[13:54:32.4275296] > [Info]  Refreshing TarkovTracker DB...
[13:54:33.5800982] > [Info]  Refreshing Market DB...
[13:59:32.4424565] > [Info]  Refreshing TarkovTracker DB...
[14:01:05.8843607] > [Info]  Saving config...
[14:01:05.9320438] > [Info]  Config saved!
[14:01:38.7884153] > [Info]  Saving config...
[14:01:38.8083683] > [Info]  Config saved!
[12:21:59.1383249] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\N0lens\Downloads\RatScanner\MicrosoftEdgeWebview2Setup.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strateg
```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting the issue, it has since been fixed in version 3.3.1.
You can launch rat scanner and it will ask you to update automatically.
