### ISSUE TITLE
Unhandled exception (Application.Current.DispatcherUnhandledException)

### ISSUE THREAD

**Issue by BeaconDev** [RatScanner/RatScanner#352]
Crash on starting. Running as Administrator.

**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot provide a value for property 'TarkovTrackerDB' on type 'RatRazor.Pages.App.Index'. There is no registered service of type 'RatTracking.TarkovTrackerDB'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffCon
```
<details>
<summary>Log</summary>

```
[14:18:33.8553817] > [Info]  ----- RatScanner 3.2.1 -----
[14:18:33.8556053] > [Info]  Starting RatScanner...
[14:18:33.8556080] > [Info]  Checking for updates...
[14:18:33.8580883] > [Info]  Loading resource "RSClientVersion"...
[14:18:35.2417732] > [Info]  A new version is available: 3.2.2
[14:18:37.2214869] > [Info]  Loading config...
[14:18:37.2236052] > [Info]  Checking for item data updates...
[14:18:37.2240690] > [Info]  Loading resource "RSItemDataBundleVersion"...
[14:18:37.3518463] > [Info]  Loading TarkovTracker...
[14:18:39.7389500] > [Info]  Loading progress data...
[14:18:47.4053730] > [Info]  Loading price data...
[14:18:47.9051937] > [Info]  Initializing RatEye...
[14:18:51.5531667] > [Info]  Setting default item...
[14:18:51.6227422] > [Info]  Initializing hotkey manager...
[14:18:51.6247553] > [Info]  Setting up data update routines...
[14:18:51.6247667] > [Info]  Ready!
[14:23:51.6327491] > [Info]  Refreshing TarkovTracker DB...
[14:28:52.5714353] > [Info]  Refreshing TarkovTracker DB...
[14:33:53.0851015] > [Info]  Refreshing TarkovTracker DB...
[14:38:53.6339805] > [Info]  Refreshing TarkovTracker DB...
[14:43:54.0492510] > [Info]  Refreshing TarkovTracker DB...
[14:48:51.6289501] > [Info]  Refreshing Market DB...
[14:48:54.6059026] > [Info]  Refreshing TarkovTracker DB...
[14:53:55.0256845] > [Info]  Refreshing TarkovTracker DB...
[14:58:55.4203441] > [Info]  Refreshing TarkovTracker DB...
[15:03:55.7786412] > [Info]  Refreshing TarkovTracker DB...
[15:08:56.2942921] > [Info]  Refreshing TarkovTracker DB...
[15:13:56.8047280] > [Info]  Refreshing TarkovTracker DB...
[15:18:52.3355843] > [Info]  Refreshing Market DB...
[15:18:57.3891343] > [Info]  Refreshing TarkovTracker DB...
[15:23:57.8531914] > [Info]  Refreshing TarkovTracker DB...
[15:28:58.3338955] > [Info]  Refreshing TarkovTracker DB...
[15:33:58.7755353] > [Info]  Refreshing TarkovTracker DB...
[15:38:59.2037867] > [Info]  Refreshing TarkovTracker DB...
[15:43:59.7174035] > [Info]  Refreshing TarkovTracker DB...
[15:48:53.1603524] > [Info]  Refreshing Market DB...
[15:49:00.1995938] > [Info]  Refreshing TarkovTracker DB...
[15:54:00.7198143] > [Info]  Refreshing TarkovTracker DB...
[15:59:01.4170960] > [Info]  Refreshing TarkovTracker DB...
[16:04:01.8180824] > [Info]  Refreshing TarkovTracker DB...
[16:09:06.6938888] > [Info]  Refreshing TarkovTracker DB...
[16:14:07.2592298] > [Info]  Refreshing TarkovTracker DB...
[16:18:53.8156886] > [Info]  Refreshing Market DB...
[16:19:07.7302829] > [Info]  Refreshing TarkovTracker DB...
[16:24:08.2346499] > [Info]  Refreshing TarkovTracker DB...
[16:29:08.6816817] > [Info]  Refreshing TarkovTracker DB...
[16:34:09.1939348] > [Info]  Refreshing TarkovTracker DB...
[16:39:09.7496938] > [Info]  Refreshing TarkovTracker DB...
[16:44:10.2501360] > [Info]  Refreshing TarkovTracker DB...
[16:48:54.5338562] > [Info]  Refreshing Market DB...
[16:49:10.6984380] > [Info]  Refreshing TarkovTracker DB...
[16:54:11.2627603] > [Info]  Refr
```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting the issue, it has since been fixed in version 3.3.1.
You can launch rat scanner and it will ask you to update automatically.
