### ISSUE TITLE
Out of memory.

### ISSUE THREAD

**Issue by godxxy5453** [RatScanner/RatScanner#353]
**Error**
Out of memory.
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[16:16:11.6245437] > [Info]  ----- RatScanner 3.2.2 -----
[16:16:11.6247600] > [Info]  Starting RatScanner...
[16:16:11.6247639] > [Info]  Checking for updates...
[16:16:11.6268114] > [Info]  Loading resource "RSClientVersion"...
[16:16:12.4952549] > [Info]  Loading config...
[16:16:12.4970924] > [Info]  Checking for item data updates...
[16:16:12.4977021] > [Info]  Loading resource "RSItemDataBundleVersion"...
[16:16:12.7096190] > [Info]  Loading progress data...
[16:16:13.4644859] > [Info]  Loading price data...
[16:16:14.3477694] > [Info]  Initializing RatEye...
[16:16:19.3981877] > [Info]  Setting default item...
[16:16:19.4634580] > [Info]  Initializing hotkey manager...
[16:16:19.4657108] > [Info]  Setting up data update routines...
[16:16:19.4657356] > [Info]  Ready!
[16:21:19.4860700] > [Info]  Refreshing TarkovTracker DB...
[16:26:19.5007613] > [Info]  Refreshing TarkovTracker DB...
[16:31:19.5076486] > [Info]  Refreshing TarkovTracker DB...
[16:36:19.5176184] > [Info]  Refreshing TarkovTracker DB...
[16:41:19.5249558] > [Info]  Refreshing TarkovTracker DB...
[16:46:19.4811268] > [Info]  Refreshing Market DB...
[16:46:19.5404143] > [Info]  Refreshing TarkovTracker DB...
[16:51:19.5521738] > [Info]  Refreshing TarkovTracker DB...
[16:56:19.5553696] > [Info]  Refreshing TarkovTracker DB...
[17:01:19.5740240] > [Info]  Refreshing TarkovTracker DB...
[17:06:19.5832158] > [Info]  Refreshing TarkovTracker DB...
[17:11:19.5839653] > [Info]  Refreshing TarkovTracker DB...
[17:16:19.5952196] > [Info]  Refreshing TarkovTracker DB...
[17:16:20.7675189] > [Info]  Refreshing Market DB...
[17:21:19.5979061] > [Info]  Refreshing TarkovTracker DB...
[17:26:19.6116198] > [Info]  Refreshing TarkovTracker DB...
[17:28:42.2061960] > [Error] Out of memory.
 -------------------- 
 System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap(Action action)
[17:31:19.6307208] > [Info]  Refreshing TarkovTracker DB...
[17:36:19.6457248] > [Info]  Refreshing TarkovTracker DB...
[17:41:19.6540577] > [Info]  Refreshing TarkovTracker DB...
[17:46:19.6770464] > [Info]  Refreshing TarkovTracker DB...
[17:46:22.2551776] > [Info]  Refreshing Market DB...
[17:51:19.6856133] > [Info]  Refreshing TarkovTracker DB...
[17:56:19.6907137] > [Info]  Refreshing TarkovTracker DB...

```
</details>

**Comment by Blightbuster** [comment]
Do you by chance just have a low amount of RAM available? Rat Scanner shouldnt take up much RAM maybe a few hundred megabytes at most.

**Comment by Blightbuster** [comment]
Please comment if the issue persists and I'll reopen it.
