### ISSUE TITLE
Rectangle '{X=866,Y=43,Width=0,Height=22}' cannot have a width or height equal to 0.

### ISSUE THREAD

**Issue by godxxy5453** [RatScanner/RatScanner#357]
**Error**
Rectangle '{X=866,Y=43,Width=0,Height=22}' cannot have a width or height equal to 0.
```
System.ArgumentException: Rectangle '{X=866,Y=43,Width=0,Height=22}' cannot have a width or height equal to 0.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[12:58:19.5785677] > [Info]  ----- RatScanner 3.2.2 -----
[12:58:19.5790230] > [Info]  Starting RatScanner...
[12:58:19.5790268] > [Info]  Checking for updates...
[12:58:19.5815124] > [Info]  Loading resource "RSClientVersion"...
[12:58:20.7668415] > [Info]  Loading config...
[12:58:20.7686224] > [Info]  Checking for item data updates...
[12:58:20.7691868] > [Info]  Loading resource "RSItemDataBundleVersion"...
[12:58:21.0014425] > [Info]  Loading progress data...
[12:58:21.4104795] > [Info]  Loading price data...
[12:58:22.3891812] > [Info]  Initializing RatEye...
[12:58:29.6017849] > [Info]  Setting default item...
[12:58:29.6657107] > [Info]  Initializing hotkey manager...
[12:58:29.6688916] > [Info]  Setting up data update routines...
[12:58:29.6689417] > [Info]  Ready!
[13:03:29.6756927] > [Info]  Refreshing TarkovTracker DB...
[13:08:29.6817283] > [Info]  Refreshing TarkovTracker DB...
[13:13:29.6887980] > [Info]  Refreshing TarkovTracker DB...
[13:18:29.7075462] > [Info]  Refreshing TarkovTracker DB...
[13:23:29.7084990] > [Info]  Refreshing TarkovTracker DB...
[13:28:29.6697768] > [Info]  Refreshing Market DB...
[13:28:29.7167820] > [Info]  Refreshing TarkovTracker DB...
[13:33:29.7276447] > [Info]  Refreshing TarkovTracker DB...
[13:38:29.7370719] > [Info]  Refreshing TarkovTracker DB...
[13:43:29.7438934] > [Info]  Refreshing TarkovTracker DB...
[13:48:29.7469110] > [Info]  Refreshing TarkovTracker DB...
[13:48:31.5340012] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5341958] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5342343] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5342626] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5347273] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5347929] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5348223] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5348562] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5349022] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5350316] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5350840] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5351647] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5351923] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5354000] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5354315] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5354726] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5355054] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5355316] > [Warning] Could not find item with uid: 59387ac686f77401442ddd61
[13:48:31.5356
```
</details>

**Comment by Blightbuster** [comment]
The bug has been fixed in more recent version of Rat Scanner.
Thanks for submitting the issue ❤️
