### ISSUE TITLE
Идет завершение работы объекта Application.

### ISSUE THREAD

**Issue by sayferst** [RatScanner/RatScanner#359]
**Error**
Идет завершение работы объекта Application.
```
System.InvalidOperationException: Идет завершение работы объекта Application.
   at System.Windows.Application.GetResourcePackage(Uri packageUri)
   at System.Windows.Application.GetResourceOrContentPart(Uri uri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RatScanner.View.BlazorOverlay.InitializeComponent()
   at RatScanner.View.BlazorOverlay..ctor(ServiceProvider serviceProvider)
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
```
<details>
<summary>Log</summary>

```
[00:45:35.3078165] > [Warning] Config version (-1) is not supported!
[00:45:35.3471984] > [Info]  Detected 1600x1024 Resolution.

You can adjust this inside the settings.
[00:45:36.7077703] > [Error] Идет завершение работы объекта Application.
 -------------------- 
 System.InvalidOperationException: Идет завершение работы объекта Application.
   at System.Windows.Application.GetResourcePackage(Uri packageUri)
   at System.Windows.Application.GetResourceOrContentPart(Uri uri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RatScanner.View.BlazorOverlay.InitializeComponent()
   at RatScanner.View.BlazorOverlay..ctor(ServiceProvider serviceProvider)
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
[00:45:43.9701502] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting the issue, it has since been fixed in version 3.3.1.
You can launch rat scanner and it will ask you to update automatically.
