### ISSUE TITLE
RatStash is missing factory4_day location type

### ISSUE THREAD

**Issue by 9312231223** [RatScanner/RatScanner#360]
**Error**
Unhandled exception in RatScanner 2.6.1
```
Newtonsoft.Json.JsonSerializationException: Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.
 ---> System.ArgumentException: Requested value 'factory4_day' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Po
```
<details>
<summary>Log</summary>

```
[11:11:12.9588912] > [Info]  ----- RatScanner 2.6.1 -----
[11:11:12.9596554] > [Info]  Starting RatScanner...
[11:11:12.9597241] > [Info]  Loading config...
[11:11:12.9815166] > [Info]  Loading item data...
[11:11:12.9882843] > [Info]  Loading resource "RSItemDataLink"...
[11:11:14.0876579] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-16.12.2021.json"...
[11:11:20.5436724] > [Error] Unhandled exception in RatScanner 2.6.1
 -------------------- 
 Newtonsoft.Json.JsonSerializationException: Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.
 ---> System.ArgumentException: Requested value 'factory4_day' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Se
```
</details>

**Comment by AkroNinja** [comment]
I am having the same problem and I don't know how to fix it.

**Comment by Blightbuster** [comment]
The issue has been fixed in more recent version of Rat Scanner.
Thanks for submitting the issue ❤️
