### ISSUE TITLE
Tesseract cant find lang model

### ISSUE THREAD

**Issue by Bisaro** [RatScanner/RatScanner#361]
**Error**
Exception has been thrown by the target of an invocation.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at InteropDotNet.LibraryLoader.InternalLoadLibrary(String baseDirectory, String platformName, String fileName)
   at InteropDotNet.LibraryLoader.CheckExecutingAssemblyDomain(String fileName, String platformName)
   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)
   at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   
```
<details>
<summary>Log</summary>

```
[07:44:34.2611331] > [Error] Exception has been thrown by the target of an invocation.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at InteropDotNet.LibraryLoader.InternalLoadLibrary(String baseDirectory, String platformName, String fileName)
   at InteropDotNet.LibraryLoader.CheckExecutingAssemblyDomain(String fileName, String platformName)
   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)
   at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at InteropDotNet.InteropRuntimeImplementer.CreateInstance[T]()
   at Tesseract.Interop.LeptonicaApi.Initialize()
   at Tesseract.Interop.LeptonicaApi.get_Native()
   at Tesseract.Pix.Create(Int32 width, Int32 height, Int32 depth)
   at Tesseract.BitmapToPixConverter.Convert(Bitmap img)
   at Tesseract.PixConverter.ToPix(Bitmap img)
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap(Action action)
[07:44:40.0363492] > [Info]  Loading resource "RSFAQLink"...
[07:44:45.3313820] > [Info]  Loading resource "RSGithubLink"...
[07:44:45.4936806] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.DllNotFoundException: Dll was not found.
   at __std_type_info_destroy_list(__type_info_node* )
   at __scrt_uninitialize_type_info()
   at _app_exit_callback()
   at <CrtImplementationDetails>.LanguageSupport.DomainUnload(Object A_0, EventArgs A_1)
   at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
   at System.AppContext.OnProcessExit()
[07:46:05.3462558] > [Info]  Refreshing TarkovTracker DB...
[07:51:05.3627173] > [Info]  Refreshing TarkovTracker DB...
[07:56:05.3781698] > [Info]  Refreshing TarkovTracker DB...
[08:01:05.3927037] > [Info]  Refreshing TarkovTracker DB...
[08:06:05.4060634] > [Info
```
</details>

**Comment by Blightbuster** [comment]
The issue has been fixed in a more recent Rat Scanner version.
Thanks for submitting the issue ❤️
