### ISSUE TITLE
System.IO.DirectoryNotFoundException (Could not find a part of the path '\Data\icons\correlation.json'.)

### ISSUE THREAD

**Issue by OfficialCrypton** [RatScanner/RatScanner#374]
**Error**
Unhandled exception (TaskScheduler.UnobservedTaskException)
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Das System kann den angegebenen Pfad nicht finden. (0x80070003))
 ---> System.IO.DirectoryNotFoundException: Das System kann den angegebenen Pfad nicht finden. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous loc
```
<details>
<summary>Log</summary>

```
[20:13:08.2558851] > [Info]  ----- RatScanner 3.2.3 -----
[20:13:08.2559075] > [Info]  Starting RatScanner...
[20:13:08.2559140] > [Info]  Checking for updates...
[20:13:08.2619521] > [Info]  Loading resource "RSClientVersion"...
[20:13:08.9575363] > [Info]  Loading config...
[20:13:08.9624524] > [Info]  Checking for item data updates...
[20:13:08.9642257] > [Info]  Loading resource "RSItemDataBundleVersion"...
[20:13:09.0684836] > [Info]  A new item data bundle is available: 20220118
[20:13:09.0685020] > [Info]  Loading resource "RSItemDataBundleLink"...
[20:13:09.1730591] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2021-12-29.zip"...
[20:13:10.5225721] > [Info]  Successfully updated to the latest item data bundle
[20:13:10.5228873] > [Info]  Loading progress data...
[20:13:10.5428089] > [Error] Unhandled exception (TaskScheduler.UnobservedTaskException)
 -------------------- 
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Das System kann den angegebenen Pfad nicht finden. (0x80070003))
 ---> System.IO.DirectoryNotFoundException: Das System kann den angegebenen Pfad nicht finden. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass4_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   --- End of inner exception stack trace ---
[20:13:10.9092775] > [Info]  Loading price data...
[20:13:11.1038401] > [Info]  Initializing RatEye...
[20:13:13.1263763] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\aleks\Desktop\RatScanner-master\RatScanner\bin\Release\net6.0-windows\Data\icons\correlation.json'.
   at Microsoft.Win3
```
</details>

**Comment by Blightbuster** [comment]
Hey, are you trying to build Rat Scanner yourself or just wanting to use it?

In case you want to compile it yourself: Your missed the step in which you need to copy over the icons to the built binary (more details in the readme)

In case you just want to use it: Pre-compiled version can be downloaded here: https://github.com/RatScanner/RatScanner/releases/tag/v3.2.3
