### ISSUE TITLE
Unhandled exception (TaskScheduler.UnobservedTaskException)

### ISSUE THREAD

**Issue by Gputman88** [RatScanner/RatScanner#377]
**Error**
Unhandled exception (TaskScheduler.UnobservedTaskException)
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The system cannot find the path specified. (0x80070003))
 ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at
```
<details>
<summary>Log</summary>

```
[01:25:09.1838895] > [Info]  ----- RatScanner 3.2.3 -----
[01:25:09.1839031] > [Info]  Starting RatScanner...
[01:25:09.1839058] > [Info]  Checking for updates...
[01:25:09.1872582] > [Info]  Loading resource "RSClientVersion"...
[01:25:09.2161925] > [Error] Unhandled exception (TaskScheduler.UnobservedTaskException)
 -------------------- 
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The system cannot find the path specified. (0x80070003))
 ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.InitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass4_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   --- End of inner exception stack trace ---
[01:25:09.4552817] > [Info]  Loading config...
[01:25:09.4566583] > [Info]  Checking for item data updates...
[01:25:09.4572436] > [Info]  Loading resource "RSItemDataBundleVersion"...
[01:25:09.4958475] > [Info]  A new item data bundle is available: 20220118
[01:25:09.4958589] > [Info]  Loading resource "RSItemDataBundleLink"...
[01:25:09.5336262] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2021-12-29.zip"...
[01:25:10.1225792] > [Info]  Successfully updated to the latest item data bundle
[01:25:10.1229698] > [Info]  Loading progress data...
[01:25:10.2634901] > [Info]  Loading price data...
[01:25:10.3668801] > [Info]  Initializing RatEye...
[01:25:12.2887666] > [Error] Unhandled exception (Application.Current.DispatcherUnhandledException)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\garre\source\repos\RatScanner\RatScanner\bin\Garretts\net6.0-windows\Data\icons\correlation.json'.
   at Microsoft.Win32.SafeHandles.Saf
```
</details>

**Comment by Blightbuster** [comment]
Hey, please have a look here on how to setup the repository for compiling: https://github.com/RatScanner/RatScanner#setting-up-the-repository-for-development
