### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by aVitomin** [RatScanner/RatScanner#382]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.ItemExtensions.GetHideoutRequired(IEnumerable`1 requiredHideoutItems, Progress progress)
   at RatScanner.ItemExtensions.GetTrackingTeamNeeds(Item item)
   at RatScanner.ViewModel.MainWindowVM.get_TrackingTeamNeeds()
   at RatRazor.Pages.App.Index.<BuildRenderTree>b__0_18(RenderTreeBuilder __builder4) in D:\Programmierung\Projects\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 62
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.HandleE
```
<details>
<summary>Log</summary>

```
[19:56:22.1084518] > [Info]  ----- RatScanner 3.2.3 -----
[19:56:22.1086257] > [Info]  Starting RatScanner...
[19:56:22.1088178] > [Info]  Checking for updates...
[19:56:22.1107783] > [Info]  Loading resource "RSClientVersion"...
[19:56:22.7210163] > [Info]  Loading config...
[19:56:22.7224115] > [Info]  Checking for item data updates...
[19:56:22.7228659] > [Info]  Loading resource "RSItemDataBundleVersion"...
[19:56:22.8409741] > [Info]  Loading TarkovTracker...
[19:56:23.6336743] > [Info]  Loading progress data...
[19:56:23.8898877] > [Info]  Loading price data...
[19:56:24.3999810] > [Info]  Initializing RatEye...
[19:56:27.4345423] > [Info]  Setting default item...
[19:56:27.5080020] > [Info]  Initializing hotkey manager...
[19:56:27.5099284] > [Info]  Setting up data update routines...
[19:56:27.5099403] > [Info]  Ready!
[19:56:37.8144588] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.ItemExtensions.GetHideoutRequired(IEnumerable`1 requiredHideoutItems, Progress progress)
   at RatScanner.ItemExtensions.GetTrackingTeamNeeds(Item item)
   at RatScanner.ViewModel.MainWindowVM.get_TrackingTeamNeeds()
   at RatRazor.Pages.App.Index.<BuildRenderTree>b__0_18(RenderTreeBuilder __builder4) in D:\Programmierung\Projects\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 62
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at RatRazor.Pages.App.Index.<PropertyChangeHandler>b__5_0() in D:\Programmierung\Projects\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 121
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherO
```
</details>

**Comment by Blightbuster** [comment]
If you are in a team with someone who hasn't opened the tracker since the progress wiped last night, there is an uncaught null error. It will be fixed in the next RatScanner update, but you should be able to fix it in the mean time by either making sure the people in your team have opened the TarkovTracker website or remaking the team.
