### ISSUE TITLE
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)

### ISSUE THREAD

**Issue by kosuymum** [RatScanner/RatScanner#385]
**Error**
Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.ItemExtensions.GetQuestRequired(IEnumerable`1 requiredQuestItems, Progress progress)
   at RatScanner.ItemExtensions.GetTrackingTeamNeeds(Item item)
   at RatScanner.ViewModel.MainWindowVM.get_TrackingTeamNeeds()
   at RatRazor.Pages.App.Index.<BuildRenderTree>b__0_18(RenderTreeBuilder __builder4) in D:\Programmierung\Projects\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 62
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.HandleExcep
```
<details>
<summary>Log</summary>

```
[07:01:19.7960430] > [Info]  ----- RatScanner 3.2.3 -----
[07:01:19.7963221] > [Info]  Starting RatScanner...
[07:01:19.7963243] > [Info]  Checking for updates...
[07:01:19.8013565] > [Info]  Loading resource "RSClientVersion"...
[07:01:20.6787480] > [Info]  Loading config...
[07:01:20.6805752] > [Info]  Checking for item data updates...
[07:01:20.6823622] > [Info]  Loading resource "RSItemDataBundleVersion"...
[07:01:20.8505691] > [Info]  Loading TarkovTracker...
[07:01:21.6819912] > [Info]  Loading progress data...
[07:01:21.7495519] > [Info]  Loading price data...
[07:01:22.6099918] > [Info]  Initializing RatEye...
[07:01:26.1941524] > [Info]  Setting default item...
[07:01:26.2378843] > [Info]  Initializing hotkey manager...
[07:01:26.2398838] > [Info]  Setting up data update routines...
[07:01:26.2398956] > [Info]  Ready!
[07:03:40.9292602] > [Info]  Saving config...
[07:03:40.9438002] > [Info]  Config saved!
[07:03:40.9459047] > [Info]  Saving config...
[07:03:40.9562816] > [Info]  Config saved!
[07:03:40.9569473] > [Info]  Saving config...
[07:03:40.9674809] > [Info]  Config saved!
[07:03:44.2041056] > [Error] Unhandled exception (AppDomain.CurrentDomain.UnhandledException)
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.ItemExtensions.GetQuestRequired(IEnumerable`1 requiredQuestItems, Progress progress)
   at RatScanner.ItemExtensions.GetTrackingTeamNeeds(Item item)
   at RatScanner.ViewModel.MainWindowVM.get_TrackingTeamNeeds()
   at RatRazor.Pages.App.Index.<BuildRenderTree>b__0_18(RenderTreeBuilder __builder4) in D:\Programmierung\Projects\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 62
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at RatRazor.Pages.App.Index.<PropertyChangeHandler>b__5_0() in D:\Programmierung\Projec
```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting the issue, it has since been fixed in version 3.3.1.
You can launch rat scanner and it will ask you to update automatically.
