### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by aVitomin** [RatScanner/RatScanner#390]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatStash.Item.GetHashCode()
   at System.Collections.Hashtable.get_Item(Object key)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange
```
<details>
<summary>Log</summary>

```
[19:33:17.7704850] > [Info]  ----- RatScanner 3.3.2 -----
[19:33:17.7708991] > [Info]  Starting RatScanner...
[19:33:17.7709039] > [Info]  Checking for updates...
[19:33:17.7739138] > [Info]  Loading resource "RSClientVersion"...
[19:33:18.4693400] > [Info]  A new version is available: 3.3.1
[19:33:24.6478140] > [Info]  Loading config...
[19:33:24.6499763] > [Info]  Setting temporary default item...
[19:33:24.6517963] > [Info]  Checking for item data updates...
[19:33:24.6523209] > [Info]  Loading resource "RSItemDataBundleVersion"...
[19:33:24.7802137] > [Info]  Initializing hotkey manager...
[19:33:24.7832958] > [Info]  UI Ready!
[19:33:24.7838556] > [Info]  Loading progress data...
[19:33:25.1308892] > [Info]  Loading price data...
[19:33:25.7036259] > [Info]  Initializing RatEye...
[19:33:31.0343463] > [Info]  Setting up timer routines...
[19:33:31.0343932] > [Info]  Setting default item...
[19:33:31.0404359] > [Info]  Enabling hotkeys...
[19:33:31.0404672] > [Info]  Ready!
[19:33:33.5539850] > [Info]  Saving config...
[19:33:33.5775491] > [Info]  Config saved!
[19:33:38.2087634] > [Info]  Saving config...
[19:33:38.2245967] > [Info]  Config saved!
[19:38:31.0492399] > [Info]  Refreshing TarkovTracker DB...
[19:43:31.0614107] > [Info]  Refreshing TarkovTracker DB...
[19:48:31.0693009] > [Info]  Refreshing TarkovTracker DB...
[19:50:49.1886445] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatStash.Item.GetHashCode()
   at System.Collections.Hashtable.get_Item(Object key)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[19:53:16.3720744] > [Info]  Loading resource "RSFAQLink"...

```
</details>

Error wen try to scan new item
![image](https://user-images.githubusercontent.com/11780299/177055286-d1a3bf4b-f056-4b51-8991-5321a066e297.png)

**Comment by Blightbuster** [comment]
Trying to get my hands on the new item list right now... thanks for reporting btw. ^^

**Comment by Blightbuster** [comment]
I will close the issue, once I compiled all the data together and pushed it to the backend for delivery.

**Comment by Blightbuster** [comment]
All new items have been added to the backend and will be downloaded automatically next time you launch RatScanner.

Thanks for reporting the issue ❤️
