### ISSUE TITLE
Unable to download updater, please update manually.

### ISSUE THREAD

**Issue by xiaoji13141** [RatScanner/RatScanner#391]
**Error**
Unable to download updater, please update manually.
```
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at RatScanner.RatScannerMain.UpdateRatScanner()
```
<details>
<summary>Log</summary>

```
[01:23:51.4975376] > [Info]  ----- RatScanner 3.3.1 -----
[01:23:51.4977441] > [Info]  Starting RatScanner...
[01:23:51.4977466] > [Info]  Checking for updates...
[01:23:51.5002620] > [Info]  Loading resource "RSClientVersion"...
[01:23:53.1164914] > [Info]  A new version is available: 3.3.3
[01:23:54.5848164] > [Warning] f:\Users\CHEN\Downloads\RatScanner\RatUpdater.exe could not be found!
[01:23:54.5848331] > [Info]  Loading resource "RSUpdaterLink"...
[01:23:54.8587168] > [Info]  Downloading file "https://github.com/RatScanner/RatUpdater/releases/latest/download/RatUpdater.exe"...
[01:23:57.2750514] > [Error] Unable to download updater, please update manually.
 -------------------- 
 System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at RatScanner.RatScannerMain.UpdateRatScanner()
[01:24:02.5344154] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Hey, please try to do the automatic update again, the error message is a fluke

**Comment by Blightbuster** [comment]
Thanks for submitting the issue, this can be considered fixed as rat scanner will now automatically download the updater if it is missing.
