### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Meiru2020** [RatScanner/RatScanner#392]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatStash.Item.GetHashCode()
   at System.Collections.Hashtable.get_Item(Object key)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange
```
<details>
<summary>Log</summary>

```
[04:01:54.0764823] > [Info]  ----- RatScanner 3.3.3 -----
[04:01:54.0771757] > [Info]  Starting RatScanner...
[04:01:54.0771864] > [Info]  Loading config...
[04:01:54.0825641] > [Info]  Setting temporary default item...
[04:01:54.0850470] > [Info]  Checking for item data updates...
[04:01:54.0898388] > [Info]  Loading resource "RSItemDataBundleVersion"...
[04:01:54.9516536] > [Info]  Initializing tarkov tracker database
[04:01:54.9518889] > [Info]  Initializing hotkey manager...
[04:01:54.9549438] > [Info]  UI Ready!
[04:01:55.9557117] > [Info]  Checking for updates...
[04:01:55.9562298] > [Info]  Loading resource "RSClientVersion"...
[04:01:56.0930692] > [Info]  Loading progress data...
[04:01:56.7266931] > [Info]  Loading price data...
[04:01:57.3768306] > [Info]  Loading TarkovTracker data...
[04:01:57.3768502] > [Info]  Initializing RatEye...
[04:02:04.7945105] > [Info]  Setting up timer routines...
[04:02:04.7945693] > [Info]  Setting default item...
[04:02:04.8081362] > [Info]  Enabling hotkeys...
[04:02:04.8081856] > [Info]  Ready!
[04:07:04.8087245] > [Info]  Refreshing TarkovTracker DB...
[04:12:04.8176797] > [Info]  Refreshing TarkovTracker DB...
[04:17:04.8234552] > [Info]  Refreshing TarkovTracker DB...
[04:17:22.8442303] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:22.8969136] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:22.9242361] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:22.9705312] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.0540300] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1496643] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1497233] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1497539] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1497844] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1498146] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1498692] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1499418] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1499756] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1817976] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1819148] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1819756] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1821100] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1821851] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1824942] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1826163] > [Warning] Could not find item with uid: 5909e4b686f7747f5b744fa4
[04:17:23.1826813] > [Warning] Could not find
```
</details>

**Comment by Blightbuster** [comment]
Tracking in #390, thanks for reporting.
