### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by godxxy5453** [RatScanner/RatScanner#393]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatStash.Item.GetHashCode()
   at System.Collections.Hashtable.get_Item(Object key)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange
```
<details>
<summary>Log</summary>

```
[07:54:10.5210939] > [Info]  ----- RatScanner 3.3.3 -----
[07:54:10.5213074] > [Info]  Starting RatScanner...
[07:54:10.5213114] > [Info]  Loading config...
[07:54:10.5233745] > [Info]  Setting temporary default item...
[07:54:10.5246155] > [Info]  Checking for item data updates...
[07:54:10.5271108] > [Info]  Loading resource "RSItemDataBundleVersion"...
[07:54:11.5997856] > [Info]  Initializing tarkov tracker database
[07:54:11.5999289] > [Info]  Initializing hotkey manager...
[07:54:11.6026281] > [Info]  UI Ready!
[07:54:12.6040618] > [Info]  Checking for updates...
[07:54:12.6043545] > [Info]  Loading resource "RSClientVersion"...
[07:54:12.8090787] > [Info]  Loading progress data...
[07:54:13.4390226] > [Info]  Loading price data...
[07:54:14.3202626] > [Info]  Loading TarkovTracker data...
[07:54:14.3202738] > [Info]  Initializing RatEye...
[07:54:19.6482188] > [Info]  Setting up timer routines...
[07:54:19.6482361] > [Info]  Setting default item...
[07:54:19.6530122] > [Info]  Enabling hotkeys...
[07:54:19.6530288] > [Info]  Ready!
[07:59:19.6683751] > [Info]  Refreshing TarkovTracker DB...
[08:04:19.6776997] > [Info]  Refreshing TarkovTracker DB...
[08:09:19.6981397] > [Info]  Refreshing TarkovTracker DB...
[08:14:19.7017099] > [Info]  Refreshing TarkovTracker DB...
[08:19:19.7031535] > [Info]  Refreshing TarkovTracker DB...
[08:24:19.6535482] > [Info]  Refreshing Market DB...
[08:24:19.7151697] > [Info]  Refreshing TarkovTracker DB...
[08:29:19.7210652] > [Info]  Refreshing TarkovTracker DB...
[08:34:19.7457570] > [Info]  Refreshing TarkovTracker DB...
[08:39:19.7548465] > [Info]  Refreshing TarkovTracker DB...
[08:44:19.7594059] > [Info]  Refreshing TarkovTracker DB...
[08:49:19.7697433] > [Info]  Refreshing TarkovTracker DB...
[08:54:19.7747874] > [Info]  Refreshing TarkovTracker DB...
[08:54:20.9718363] > [Info]  Refreshing Market DB...
[08:59:19.7893515] > [Info]  Refreshing TarkovTracker DB...
[09:04:19.7928406] > [Info]  Refreshing TarkovTracker DB...
[09:08:02.5549650] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatStash.Item.GetHashCode()
   at System.Collections.Hashtable.get_Item(Object key)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.U
```
</details>

**Comment by Blightbuster** [comment]
Tracking in #390, thanks for reporting.
