### ISSUE TITLE
Unable to download updater, please update manually.

### ISSUE THREAD

**Issue by KRadmiral** [RatScanner/RatScanner#394]
**Error**
Unable to download updater, please update manually.
```
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at RatScanner.RatScannerMain.UpdateRatScanner()
```
<details>
<summary>Log</summary>

```
[09:17:48.1030610] > [Info]  ----- RatScanner 3.3.1 -----
[09:17:48.1033431] > [Info]  Starting RatScanner...
[09:17:48.1033471] > [Info]  Checking for updates...
[09:17:48.1064630] > [Info]  Loading resource "RSClientVersion"...
[09:17:55.9210959] > [Info]  A new version is available: 3.3.3
[09:18:33.5042012] > [Warning] C:\Users\tolak\OneDrive\Рабочий стол\RatScanner\RatScanner\RatUpdater.exe could not be found!
[09:18:33.5042173] > [Info]  Loading resource "RSUpdaterLink"...
[09:18:33.6707424] > [Info]  Downloading file "https://github.com/RatScanner/RatUpdater/releases/latest/download/RatUpdater.exe"...
[09:18:35.2378409] > [Error] Unable to download updater, please update manually.
 -------------------- 
 System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at RatScanner.RatScannerMain.UpdateRatScanner()
[09:18:37.9783014] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Hey, please try to do the automatic update again, the error message is a fluke

**Comment by Blightbuster** [comment]
Tracking in #391
