### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by godxxy5453** [RatScanner/RatScanner#395]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatStash.Item.GetHashCode()
   at System.Collections.Hashtable.get_Item(Object key)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange
```
<details>
<summary>Log</summary>

```
[09:34:31.4573226] > [Info]  ----- RatScanner 3.3.3 -----
[09:34:31.4576391] > [Info]  Starting RatScanner...
[09:34:31.4579543] > [Info]  Loading config...
[09:34:31.4599970] > [Info]  Setting temporary default item...
[09:34:31.4614141] > [Info]  Checking for item data updates...
[09:34:31.4641792] > [Info]  Loading resource "RSItemDataBundleVersion"...
[09:34:32.3036561] > [Info]  Initializing tarkov tracker database
[09:34:32.3038000] > [Info]  Initializing hotkey manager...
[09:34:32.3065932] > [Info]  UI Ready!
[09:34:33.3091198] > [Info]  Checking for updates...
[09:34:33.3094230] > [Info]  Loading resource "RSClientVersion"...
[09:34:33.5345598] > [Info]  Loading progress data...
[09:34:35.1220886] > [Info]  Loading price data...
[09:34:36.0488332] > [Info]  Loading TarkovTracker data...
[09:34:36.0488425] > [Info]  Initializing RatEye...
[09:34:39.8920659] > [Info]  Setting up timer routines...
[09:34:39.8921193] > [Info]  Setting default item...
[09:34:39.8969341] > [Info]  Enabling hotkeys...
[09:34:39.8969622] > [Info]  Ready!
[09:39:39.9012440] > [Info]  Refreshing TarkovTracker DB...
[09:44:39.9014444] > [Info]  Refreshing TarkovTracker DB...
[09:49:39.9096111] > [Info]  Refreshing TarkovTracker DB...
[09:54:39.9154711] > [Info]  Refreshing TarkovTracker DB...
[09:59:40.0290441] > [Info]  Refreshing TarkovTracker DB...
[10:04:39.8982072] > [Info]  Refreshing Market DB...
[10:04:40.0339676] > [Info]  Refreshing TarkovTracker DB...
[10:09:40.0472467] > [Info]  Refreshing TarkovTracker DB...
[10:14:40.0504413] > [Info]  Refreshing TarkovTracker DB...
[10:19:40.0561235] > [Info]  Refreshing TarkovTracker DB...
[10:24:40.0658679] > [Info]  Refreshing TarkovTracker DB...
[10:29:40.0687571] > [Info]  Refreshing TarkovTracker DB...
[10:34:40.0787144] > [Info]  Refreshing TarkovTracker DB...
[10:34:41.6848622] > [Info]  Refreshing Market DB...
[10:39:40.0862570] > [Info]  Refreshing TarkovTracker DB...
[10:44:40.1013865] > [Info]  Refreshing TarkovTracker DB...
[10:49:40.1039106] > [Info]  Refreshing TarkovTracker DB...
[10:54:40.1181468] > [Info]  Refreshing TarkovTracker DB...
[10:59:40.1375766] > [Info]  Refreshing TarkovTracker DB...
[11:04:40.1509311] > [Info]  Refreshing TarkovTracker DB...
[11:04:43.0247313] > [Info]  Refreshing Market DB...
[11:09:40.1543141] > [Info]  Refreshing TarkovTracker DB...
[11:14:40.1592667] > [Info]  Refreshing TarkovTracker DB...
[11:19:40.1658447] > [Info]  Refreshing TarkovTracker DB...
[11:24:40.1786855] > [Info]  Refreshing TarkovTracker DB...
[11:29:40.1888113] > [Info]  Refreshing TarkovTracker DB...
[11:34:40.1991178] > [Info]  Refreshing TarkovTracker DB...
[11:34:44.3266297] > [Info]  Refreshing Market DB...
[11:39:40.2026114] > [Info]  Refreshing TarkovTracker DB...
[11:44:40.2174117] > [Info]  Refreshing TarkovTracker DB...
[11:49:40.2233516] > [Info]  Refreshing TarkovTracker DB...
[11:54:40.2350839] > [Info]  Refreshing TarkovTracker DB...
[11:59:40.2396839] > [Info]  Refreshing TarkovTracker
```
</details>

**Comment by Blightbuster** [comment]
Tracking in #390, thanks for reporting.
