### ISSUE TITLE
Unable to download updater, please update manually.

### ISSUE THREAD

**Issue by Mertymen2010** [RatScanner/RatScanner#396]
**Error**
Unable to download updater, please update manually.
```
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at RatScanner.RatScannerMain.UpdateRatScanner()
```
<details>
<summary>Log</summary>

```
[15:09:09.4644162] > [Info]  ----- RatScanner 3.3.1 -----
[15:09:09.4644246] > [Info]  Starting RatScanner...
[15:09:09.4644263] > [Info]  Checking for updates...
[15:09:09.4665460] > [Info]  Loading resource "RSClientVersion"...
[15:09:09.9761471] > [Info]  A new version is available: 3.3.3
[15:09:26.2258563] > [Warning] C:\Users\Marti\Documents\Rat Scanner\RatUpdater.exe could not be found!
[15:09:26.2258722] > [Info]  Loading resource "RSUpdaterLink"...
[15:09:26.3307172] > [Info]  Downloading file "https://github.com/RatScanner/RatUpdater/releases/latest/download/RatUpdater.exe"...
[15:09:27.4141052] > [Error] Unable to download updater, please update manually.
 -------------------- 
 System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at RatScanner.RatScannerMain.UpdateRatScanner()
[15:09:31.5712479] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Tracking in #391
