### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by vilim07** [RatScanner/RatScanner#397]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatStash.Item.GetHashCode()
   at System.Collections.Hashtable.get_Item(Object key)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange
```
<details>
<summary>Log</summary>

```
[21:56:28.2171975] > [Info]  ----- RatScanner 3.3.3 -----
[21:56:28.2182041] > [Info]  Starting RatScanner...
[21:56:28.2182084] > [Info]  Loading config...
[21:56:28.2256403] > [Info]  Setting temporary default item...
[21:56:28.2298135] > [Info]  Checking for item data updates...
[21:56:28.2383910] > [Info]  Loading resource "RSItemDataBundleVersion"...
[21:56:28.9904682] > [Info]  Initializing tarkov tracker database
[21:56:28.9906520] > [Info]  Initializing hotkey manager...
[21:56:28.9933774] > [Info]  UI Ready!
[21:56:30.0005539] > [Info]  Checking for updates...
[21:56:30.0010556] > [Info]  Loading resource "RSClientVersion"...
[21:56:30.1108483] > [Info]  Loading progress data...
[21:56:30.5607167] > [Info]  Loading price data...
[21:56:31.0770055] > [Info]  Loading TarkovTracker data...
[21:56:31.0770277] > [Info]  Initializing RatEye...
[21:56:31.3608076] > [Warning] Could not find item with uid: 123456789012345678901234
[21:56:37.7142710] > [Info]  Setting up timer routines...
[21:56:37.7143381] > [Info]  Setting default item...
[21:56:37.7354309] > [Info]  Enabling hotkeys...
[21:56:37.7354670] > [Info]  Ready!
[21:56:43.5613267] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatStash.Item.GetHashCode()
   at System.Collections.Hashtable.get_Item(Object key)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   at System.Windows.PropertyPath.ResolvePropertyName(String name, Object item, Type ownerType, Object context, Boolean throwOnError)
   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[21:57:04.2364963] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Tracking in https://github.com/RatScanner/RatScanner/issues/390, thanks for reporting.
