### ISSUE TITLE
Access to the path 'C:\Users\the one\Desktop\RatScanner\Log.txt' is denied.

### ISSUE THREAD

**Issue by TugAlgarvio** [RatScanner/RatScanner#400]
**Error**
Access to the path 'C:\Users\the one\Desktop\RatScanner\Log.txt' is denied.
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Access to the path 'C:\Users\the one\Desktop\RatScanner\Log.txt' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\the one\Desktop\RatScanner\Log.txt' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at RatScanner.Logger.Clear()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__8_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
```
<details>
<summary>Log</summary>

```
[19:47:36.3228847] > [Info]  ----- RatScanner 3.3.5 -----
[19:47:36.3228946] > [Info]  Starting RatScanner...
[19:47:36.3228960] > [Info]  Loading config...
[19:47:36.3247189] > [Info]  Setting temporary default item...
[19:47:36.3259056] > [Info]  Checking for item data updates...
[19:47:36.3280385] > [Info]  Loading resource "RSItemDataBundleVersion"...
[19:47:37.9355368] > [Info]  Initializing tarkov tracker database
[19:47:37.9356529] > [Info]  Initializing hotkey manager...
[19:47:37.9377813] > [Info]  UI Ready!
[19:47:38.9479115] > [Info]  Checking for updates...
[19:47:38.9480865] > [Info]  Loading resource "RSClientVersion"...
[19:47:39.5447931] > [Info]  Loading progress data...
[19:47:41.7401494] > [Info]  Loading price data...
[19:47:42.1694224] > [Info]  Loading TarkovTracker data...
[19:47:42.1694311] > [Info]  Initializing RatEye...
[19:47:45.1203838] > [Info]  Setting up timer routines...
[19:47:45.1204012] > [Info]  Setting default item...
[19:47:45.1241351] > [Info]  Enabling hotkeys...
[19:47:45.1241452] > [Info]  Ready!
[19:49:36.3253229] > [Info]  Loading resource "RSPatreonLink"...

```
</details>

**Comment by BelvedereHenrique** [comment]
Your user needs to have write permissions on this folder/file as well

**Comment by Blightbuster** [comment]
Will be tracked in https://github.com/RatScanner/RatScanner/issues/424
Thanks for reporting the issue non the less ❤️
