### ISSUE TITLE
Loading of resource "RSGithubLink" failed.

### ISSUE THREAD

**Issue by prozacl** [RatScanner/RatScanner#402]
**Error**
Loading of resource "RSGithubLink" failed.
```
System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetString(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
```
<details>
<summary>Log</summary>

```
[01:53:12.6543712] > [Info]  ----- RatScanner 3.3.5 -----
[01:53:12.6546138] > [Info]  Starting RatScanner...
[01:53:12.6546296] > [Info]  Loading config...
[01:53:12.6581426] > [Info]  Setting temporary default item...
[01:53:12.6596187] > [Info]  Checking for item data updates...
[01:53:12.6637171] > [Info]  Loading resource "RSItemDataBundleVersion"...
[01:54:34.4949193] > [Error] Loading of resource "RSItemDataBundleVersion" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetString(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
[01:54:37.7610172] > [Info]  Loading resource "RSGithubLink"...
[01:54:38.1829204] > [Error] Loading of resource "RSGithubLink" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetString(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)

```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting. Backend should be more stable now 👍
