### ISSUE TITLE
Сделана попытка доступа к сокету методом, запрещенным правами доступа. [::ffff:204.79.197.219]:443

### ISSUE THREAD

**Issue by Favoritexxx** [RatScanner/RatScanner#407]
**Error**
Сделана попытка доступа к сокету методом, запрещенным правами доступа. [::ffff:204.79.197.219]:443
```
System.Net.WebException: Сделана попытка доступа к сокету методом, запрещенным правами доступа. [::ffff:204.79.197.219]:443 (msedge.sf.dl.delivery.mp.microsoft.com:443)
 ---> System.Net.Http.HttpRequestException: Сделана попытка доступа к сокету методом, запрещенным правами доступа. [::ffff:204.79.197.219]:443 (msedge.sf.dl.delivery.mp.microsoft.com:443)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10013): Сделана попытка доступа к сокету методом, запрещенным правами доступа. [::ffff:204.79.197.219]:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
--- End of stack trace from previous location ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socke
```
<details>
<summary>Log</summary>

```
[08:31:10.2285570] > [Info]  ----- RatScanner 3.3.5 -----
[08:31:10.2287867] > [Info]  Starting RatScanner...
[08:31:10.2287895] > [Info]  Loading config...
[08:31:10.2299062] > [Info]  Setting temporary default item...
[08:31:10.2312977] > [Info]  Checking for item data updates...
[08:31:10.2336453] > [Info]  Loading resource "RSItemDataBundleVersion"...
[08:31:11.3075081] > [Info]  Initializing tarkov tracker database
[08:31:11.3077498] > [Info]  Initializing hotkey manager...
[08:31:11.3100819] > [Info]  UI Ready!
[08:31:12.3165965] > [Info]  Checking for updates...
[08:31:12.3169143] > [Info]  Loading resource "RSClientVersion"...
[08:31:12.4364998] > [Info]  Loading progress data...
[08:31:12.8158962] > [Info]  Loading price data...
[08:31:13.3840178] > [Info]  Loading TarkovTracker data...
[08:31:13.3840301] > [Info]  Initializing RatEye...
[08:31:22.4414768] > [Info]  Setting up timer routines...
[08:31:22.4415034] > [Info]  Setting default item...
[08:31:22.4464862] > [Info]  Enabling hotkeys...
[08:31:22.4465029] > [Info]  Ready!
[08:36:22.4563956] > [Info]  Refreshing TarkovTracker DB...
[08:41:22.4695851] > [Info]  Refreshing TarkovTracker DB...
[08:46:22.4755422] > [Info]  Refreshing TarkovTracker DB...
[08:51:22.4785582] > [Info]  Refreshing TarkovTracker DB...
[08:56:22.4886150] > [Info]  Refreshing TarkovTracker DB...
[09:01:22.4524663] > [Info]  Refreshing Market DB...
[09:01:22.4962341] > [Info]  Refreshing TarkovTracker DB...
[09:06:22.5137562] > [Info]  Refreshing TarkovTracker DB...
[09:11:22.5290373] > [Info]  Refreshing TarkovTracker DB...
[09:16:22.5383679] > [Info]  Refreshing TarkovTracker DB...
[09:21:22.5389022] > [Info]  Refreshing TarkovTracker DB...
[09:26:22.5385513] > [Info]  Refreshing TarkovTracker DB...
[09:31:22.5405415] > [Info]  Refreshing TarkovTracker DB...
[09:31:23.2783584] > [Info]  Refreshing Market DB...
[09:36:22.5452927] > [Info]  Refreshing TarkovTracker DB...
[09:41:22.5473106] > [Info]  Refreshing TarkovTracker DB...
[09:46:22.5549092] > [Info]  Refreshing TarkovTracker DB...
[09:51:22.5570207] > [Info]  Refreshing TarkovTracker DB...
[09:56:22.5697025] > [Info]  Refreshing TarkovTracker DB...
[10:01:22.5759364] > [Info]  Refreshing TarkovTracker DB...
[10:01:24.0444109] > [Info]  Refreshing Market DB...
[10:06:22.5838910] > [Info]  Refreshing TarkovTracker DB...
[10:11:22.5992258] > [Info]  Refreshing TarkovTracker DB...
[10:16:22.6142881] > [Info]  Refreshing TarkovTracker DB...
[10:21:22.6196270] > [Info]  Refreshing TarkovTracker DB...
[10:26:22.6338652] > [Info]  Refreshing TarkovTracker DB...
[10:31:22.6477926] > [Info]  Refreshing TarkovTracker DB...
[10:31:24.8811058] > [Info]  Refreshing Market DB...
[10:36:22.6507041] > [Info]  Refreshing TarkovTracker DB...
[10:41:22.6593136] > [Info]  Refreshing TarkovTracker DB...
[10:46:22.6707970] > [Info]  Refreshing TarkovTracker DB...
[10:51:22.6799081] > [Info]  Refreshing TarkovTracker DB...
[10:56:22.6800855] > [Info]  Refreshing TarkovTracker
```
</details>

**Comment by Blightbuster** [comment]
Tracked in #448 
Thanks for submitting the issue ❤️
