### ISSUE TITLE
Системе не удается найти указанный путь. (0x80070003)

### ISSUE THREAD

**Issue by FasterGood34** [RatScanner/RatScanner#409]
**Error**
Системе не удается найти указанный путь. (0x80070003)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Системе не удается найти указанный путь. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebVie
```
<details>
<summary>Log</summary>

```
[11:49:32.3986022] > [Warning] Config version (-1) is not supported!
[11:49:32.4087396] > [Info]  Detected 1920x1080 Resolution.

You can adjust this inside the settings.
[11:49:35.2011697] > [Error] Системе не удается найти указанный путь. (0x80070003)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Системе не удается найти указанный путь. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[11:49:40.3447969] > [Info]  Loading resource "RSFAQLink"...
[11:49:44.9920269] > [Info]  Loading resource "RSGithubLink"...
[11:50:42.5734822] > [Error] Системе не удается найти указанный путь. (0x80070003)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Системе не удается найти указанный путь. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKi
```
</details>

**Comment by Blightbuster** [comment]
Hey, please try uninstalling the `WebView2 Runtime` in windows and the manually install it from: https://go.microsoft.com/fwlink/p/?LinkId=2124703

After it is installed, start RatScanner again.

**Comment by Blightbuster** [comment]
Please comment if the issue persists and I'll re-open the issue.
