### ISSUE TITLE
Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.

### ISSUE THREAD

**Issue by DrArsehole** [RatScanner/RatScanner#415]
**Error**
Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.
```
Newtonsoft.Json.JsonSerializationException: Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.
 ---> System.ArgumentException: Requested value 'factory4_day' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Po
```
<details>
<summary>Log</summary>

```
[01:32:02.0579291] > [Info]  ----- RatScanner 2.7.0 -----
[01:32:02.0630697] > [Info]  Starting RatScanner...
[01:32:02.0631287] > [Info]  Loading config...
[01:32:02.0899919] > [Info]  Loading item data...
[01:32:02.0967547] > [Info]  Loading resource "RSItemDataVersion"...
[01:32:04.0987387] > [Error] Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.
 -------------------- 
 Newtonsoft.Json.JsonSerializationException: Error converting value "factory4_day" to type 'RatStash.Location'. Path '5672cb724bdc2dc2088b456b._props.AllowSpawnOnLocations[1]', line 1, position 395495.
 ---> System.ArgumentException: Requested value 'factory4_day' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsof
```
</details>

**Comment by Blightbuster** [comment]
Hey, please download the latest version to fix this issue: https://github.com/RatScanner/RatScanner/releases/tag/v3.3.5
