### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.

### ISSUE THREAD

**Issue by lofilake** [RatScanner/RatScanner#417]
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.
```
System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetBytes(String url, String bearerToken)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
```
<details>
<summary>Log</summary>

```
[18:47:04.9040956] > [Info]  ----- RatScanner 3.3.5 -----
[18:47:04.9043992] > [Info]  Starting RatScanner...
[18:47:04.9044039] > [Info]  Loading config...
[18:47:04.9084207] > [Info]  Setting temporary default item...
[18:47:04.9102368] > [Info]  Checking for item data updates...
[18:47:04.9129327] > [Info]  Loading resource "RSItemDataBundleVersion"...
[18:47:05.6085266] > [Info]  A new item data bundle is available: 20220822
[18:47:05.6085665] > [Info]  Loading resource "RSItemDataBundleLink"...
[18:47:05.7454053] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip"...
[18:47:06.3636390] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetBytes(String url, String bearerToken)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)

```
</details>

**Comment by LDzonis** [comment]
same

**Comment by Blightbuster** [comment]
Should be fixed now seems like the backend was overloaded.
