### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.

### ISSUE THREAD

**Issue by Floah1011** [RatScanner/RatScanner#418]
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.
```
System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetBytes(String url, String bearerToken)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
```
<details>
<summary>Log</summary>

```
[18:59:07.9392943] > [Info]  ----- RatScanner 3.3.5 -----
[18:59:07.9394696] > [Info]  Starting RatScanner...
[18:59:07.9394726] > [Info]  Loading config...
[18:59:07.9414394] > [Info]  Setting temporary default item...
[18:59:07.9426284] > [Info]  Checking for item data updates...
[18:59:07.9449799] > [Info]  Loading resource "RSItemDataBundleVersion"...
[18:59:08.3874724] > [Info]  A new item data bundle is available: 20220822
[18:59:08.3874823] > [Info]  Loading resource "RSItemDataBundleLink"...
[18:59:08.4345777] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip"...
[18:59:09.0418992] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetBytes(String url, String bearerToken)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)

```
</details>

**Comment by Blightbuster** [comment]
Should be fixed now seems like the backend was overloaded.
