### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.

### ISSUE THREAD

**Issue by godxxy5453** [RatScanner/RatScanner#419]
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.
```
System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetBytes(String url, String bearerToken)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
```
<details>
<summary>Log</summary>

```
[19:12:43.4357585] > [Info]  ----- RatScanner 3.3.6 -----
[19:12:43.4360078] > [Info]  Starting RatScanner...
[19:12:43.4360123] > [Info]  Loading config...
[19:12:43.4382544] > [Info]  Setting temporary default item...
[19:12:43.4400874] > [Info]  Checking for item data updates...
[19:12:43.4434275] > [Info]  Loading resource "RSItemDataBundleVersion"...
[19:12:44.3323540] > [Info]  A new item data bundle is available: 20220822
[19:12:44.3323760] > [Info]  Loading resource "RSItemDataBundleLink"...
[19:12:44.5635581] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip"...
[19:12:45.2873233] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetBytes(String url, String bearerToken)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
[19:12:59.6850158] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting. Backend should be more stable now 👍
