### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SoleGossamer** [RatScanner/RatScanner#422]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[05:03:52.2343116] > [Info]  ----- RatScanner 3.3.6 -----
[05:03:52.2344957] > [Info]  Starting RatScanner...
[05:03:52.2344984] > [Info]  Loading config...
[05:03:52.2360740] > [Info]  Setting temporary default item...
[05:03:52.2372653] > [Info]  Checking for item data updates...
[05:03:52.2396069] > [Info]  Loading resource "RSItemDataBundleVersion"...
[05:03:52.9681528] > [Info]  A new item data bundle is available: 20220822
[05:03:52.9681649] > [Info]  Loading resource "RSItemDataBundleLink"...
[05:03:53.0838220] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip"...
[05:04:17.4018592] > [Info]  Successfully updated to the latest item data bundle
[05:04:17.4018794] > [Info]  Initializing tarkov tracker database
[05:04:17.4021779] > [Info]  Initializing hotkey manager...
[05:04:17.4046858] > [Info]  UI Ready!
[05:04:18.4185149] > [Info]  Checking for updates...
[05:04:18.4189152] > [Info]  Loading resource "RSClientVersion"...
[05:04:18.5343300] > [Info]  A new version is available: 3.3.8
[05:04:18.5343446] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[05:04:42.3349336] > [Info]  Saving config...
[05:04:42.3491740] > [Info]  Config saved!
[05:04:43.4157989] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[05:04:48.2753490] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[05:04:50.1400472] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[05:04:50.9944951] > [Info]  Loading resource "RSFAQLink"...
[05:04:51.0411160] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameS
```
</details>

**Comment by Blightbuster** [comment]
Hey, could you tell me the steps to reproduce the error?
From the log file it seems like you just edited something in the settings, saved and it crashes but I cant reproduce that behaviour.

**Comment by SoleGossamer** [comment]
Hello. Already working, restarting helped. Only here's what's interesting,
when demonstrating the game (the game in windowed mode without frames) in
Discord, with the scanner running, the broadcast picture is static. Is this
a known problem?

сб, 27 авг. 2022 г. в 22:21, Blightbuster ***@***.***>:

**Comment by Blightbuster** [comment]
Yes the discord screen sharing issue is tracked inside #155

If this issue ever appears again and you got some more tips on how to reproduce it, please don't hesitate to report it again.
