### ISSUE TITLE
Access to the path 'C:\Users\Juan\Desktop\rat scanner\Log.txt' is denied.

### ISSUE THREAD

**Issue by mrlotux** [RatScanner/RatScanner#424]
**Error**
Access to the path 'C:\Users\Juan\Desktop\rat scanner\Log.txt' is denied.
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Access to the path 'C:\Users\Juan\Desktop\rat scanner\Log.txt' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Juan\Desktop\rat scanner\Log.txt' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, F
```
<details>
<summary>Log</summary>

```
[23:37:09.9745354] > [Info]  ----- RatScanner 3.3.8 -----
[23:37:09.9745488] > [Info]  Starting RatScanner...
[23:37:09.9745517] > [Info]  Loading config...
[23:37:09.9770364] > [Info]  Setting temporary default item...
[23:37:09.9787255] > [Info]  Checking for item data updates...
[23:37:09.9828496] > [Info]  Loading resource "RSItemDataBundleVersion"...
[23:37:10.4064113] > [Info]  Initializing tarkov tracker database
[23:37:10.4066493] > [Info]  Initializing hotkey manager...
[23:37:10.4097215] > [Info]  UI Ready!
[23:37:11.4104742] > [Info]  Checking for updates...
[23:37:11.4107770] > [Info]  Loading resource "RSClientVersion"...
[23:37:11.4503490] > [Info]  Loading progress data...
[23:37:11.7135209] > [Info]  Loading price data...
[23:37:11.9889739] > [Info]  Loading TarkovTracker data...
[23:37:11.9889867] > [Info]  Initializing RatEye...
[23:37:17.8308383] > [Info]  Setting up timer routines...
[23:37:17.8308737] > [Info]  Setting default item...
[23:37:17.8359821] > [Info]  Enabling hotkeys...
[23:37:17.8359997] > [Info]  Ready!
[23:38:17.7215816] > [Info]  Saving config...
[23:38:17.7265459] > [Info]  Config saved!
[23:38:47.0335198] > [Info]  Saving config...
[23:38:47.0391897] > [Info]  Config saved!
[23:42:17.8433270] > [Info]  Refreshing TarkovTracker DB...
[23:47:17.8587609] > [Info]  Refreshing TarkovTracker DB...
[23:52:17.8596375] > [Info]  Refreshing TarkovTracker DB...
[23:57:17.8747259] > [Info]  Refreshing TarkovTracker DB...
[00:02:17.8747545] > [Info]  Refreshing TarkovTracker DB...
[00:07:17.8456928] > [Info]  Refreshing Market DB...
[00:07:17.8804607] > [Info]  Refreshing TarkovTracker DB...
[00:12:17.8935911] > [Info]  Refreshing TarkovTracker DB...
[00:17:17.9062888] > [Info]  Refreshing TarkovTracker DB...
[00:22:17.9065272] > [Info]  Refreshing TarkovTracker DB...
[00:27:17.9204208] > [Info]  Refreshing TarkovTracker DB...
[00:32:17.9215130] > [Info]  Refreshing TarkovTracker DB...
[00:37:17.9223784] > [Info]  Refreshing TarkovTracker DB...
[00:37:18.3600317] > [Info]  Refreshing Market DB...
[00:42:17.9361929] > [Info]  Refreshing TarkovTracker DB...
[00:47:17.9363868] > [Info]  Refreshing TarkovTracker DB...
[00:52:17.9523792] > [Info]  Refreshing TarkovTracker DB...
[00:57:17.9679872] > [Info]  Refreshing TarkovTracker DB...
[01:02:17.9829967] > [Info]  Refreshing TarkovTracker DB...
[01:07:17.9828872] > [Info]  Refreshing TarkovTracker DB...
[01:07:18.7492081] > [Info]  Refreshing Market DB...
[01:12:17.9825653] > [Info]  Refreshing TarkovTracker DB...
[01:17:17.9831058] > [Info]  Refreshing TarkovTracker DB...
[01:22:17.9835746] > [Info]  Refreshing TarkovTracker DB...
[01:27:17.9991038] > [Info]  Refreshing TarkovTracker DB...
[01:32:18.0140738] > [Info]  Refreshing TarkovTracker DB...
[01:37:18.0145678] > [Info]  Refreshing TarkovTracker DB...
[01:37:19.0988480] > [Info]  Refreshing Market DB...
[01:42:18.0298632] > [Info]  Refreshing TarkovTracker DB...
[01:47:18.0298555] > [Info]  Refreshing TarkovTracker D
```
</details>

**Comment by Blightbuster** [comment]
Did you try to delete/modify the log file while rat scanner was still running or did this happen out of the blue?

**Comment by mrlotux** [comment]
when i first download it works ,  the second time i open the program gives
me this error and wont worka anymore. what can i do?

**Comment by Blightbuster** [comment]
In the task manager, make sure all instances of Rat Scanner are closed and then try again please. I believe the issue is caused by multiple instance of rat scanner trying to access the same log file.

**Comment by jondavidjohn** [comment]
Also having this issue.  Just installed it and popped up first run.

**Comment by jondavidjohn** [comment]
Was able to resolve by running rat scanner as administrator.

**Comment by mrlotux** [comment]
Thank you boss you are great hope you have a great day.

**Comment by DysektAI** [comment]
Closing as **completed** / resolved via user workaround.

Comments indicate this was caused by file-locking (multiple instances) / permissions on `Log.txt`, and was resolved by ensuring a single instance and/or running with appropriate permissions. No ongoing reproduction reported since 2023.
