### ISSUE TITLE
Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.

### ISSUE THREAD

**Issue by vanucci** [RatScanner/RatScanner#426]
**Error**
Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
```
System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, 
```
<details>
<summary>Log</summary>

```
[20:00:15.5340554] > [Info]  ----- RatScanner 3.3.5 -----
[20:00:15.5340704] > [Info]  Starting RatScanner...
[20:00:15.5340721] > [Info]  Loading config...
[20:00:15.5368715] > [Info]  Setting temporary default item...
[20:00:15.5383729] > [Info]  Checking for item data updates...
[20:00:15.5416485] > [Info]  Loading resource "RSItemDataBundleVersion"...
[20:00:16.1776116] > [Info]  A new item data bundle is available: 20220822
[20:00:16.1776331] > [Info]  Loading resource "RSItemDataBundleLink"...
[20:00:16.2794942] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip"...
[20:00:29.0731446] > [Info]  Successfully updated to the latest item data bundle
[20:00:29.0731703] > [Info]  Initializing tarkov tracker database
[20:00:29.0734343] > [Info]  Initializing hotkey manager...
[20:00:29.0773663] > [Info]  UI Ready!
[20:00:30.0876745] > [Info]  Checking for updates...
[20:00:30.0879883] > [Info]  Loading resource "RSClientVersion"...
[20:00:30.1935788] > [Info]  A new version is available: 3.3.8
[20:00:30.1935954] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[20:00:49.6149349] > [Error] Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
 -------------------- 
 System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadCo
```
</details>

**Comment by vanucci** [comment]
Just downloaded the latest version instead

**Comment by Blightbuster** [comment]
Seems like it was an issue with either you trying to run it from within the zip file, not extracting all of the files from the zip or some antivirus of yours removing some files.
