### ISSUE TITLE
Access to the path 'C:\Users\capnd\Desktop\RATSCANNER\RatScanner\Log.txt' is denied.

### ISSUE THREAD

**Issue by LeftOfLeftField** [RatScanner/RatScanner#427]
**Error**
Access to the path 'C:\Users\capnd\Desktop\RATSCANNER\RatScanner\Log.txt' is denied.
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Access to the path 'C:\Users\capnd\Desktop\RATSCANNER\RatScanner\Log.txt' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\capnd\Desktop\RATSCANNER\RatScanner\Log.txt' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode
```
<details>
<summary>Log</summary>

```
[18:56:05.1845273] > [Info]  ----- RatScanner 3.3.8 -----
[18:56:05.1845649] > [Info]  Starting RatScanner...
[18:56:05.1845699] > [Info]  Loading config...
[18:56:05.1916977] > [Info]  Setting temporary default item...
[18:56:05.1971561] > [Info]  Checking for item data updates...
[18:56:05.2069452] > [Info]  Loading resource "RSItemDataBundleVersion"...
[18:56:06.0714608] > [Info]  Initializing tarkov tracker database
[18:56:06.0718071] > [Info]  Initializing hotkey manager...
[18:56:06.0879383] > [Info]  UI Ready!
[18:56:07.0925906] > [Info]  Checking for updates...
[18:56:07.0936418] > [Info]  Loading resource "RSClientVersion"...
[18:56:07.1656667] > [Info]  Loading progress data...
[18:56:07.6432390] > [Info]  Loading price data...
[18:56:08.0588351] > [Info]  Loading TarkovTracker data...
[18:56:08.0588723] > [Info]  Initializing RatEye...
[18:56:21.1520596] > [Info]  Setting up timer routines...
[18:56:21.1521485] > [Info]  Setting default item...
[18:56:21.1743497] > [Info]  Enabling hotkeys...
[18:56:21.1744132] > [Info]  Ready!
[18:56:30.5468025] > [Info]  Saving config...
[18:56:30.5585154] > [Info]  Config saved!
[18:56:32.0005906] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:32.0011672] > [Debug] NameScan:273 -> Name scanning at: (1022, 270)
[18:56:34.6689459] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:34.6692853] > [Debug] NameScan:273 -> Name scanning at: (1050, 371)
[18:56:35.9292097] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:35.9295544] > [Debug] NameScan:273 -> Name scanning at: (1063, 457)
[18:56:40.6999952] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:40.7003116] > [Debug] NameScan:273 -> Name scanning at: (1132, 557)
[18:56:40.7133335] > [Debug] StartListening:241 -> Started listening for input
[18:56:43.0402856] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:43.0405720] > [Debug] NameScan:273 -> Name scanning at: (1086, 625)
[18:56:43.0437045] > [Info]  Saving config...
[18:56:43.0738665] > [Info]  Config saved!
[18:56:44.5814758] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:44.5817984] > [Debug] NameScan:273 -> Name scanning at: (1022, 267)
[18:56:45.3506120] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:45.3508795] > [Debug] NameScan:273 -> Name scanning at: (1085, 364)
[18:56:46.6715289] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:46.6719248] > [Debug] NameScan:273 -> Name scanning at: (1093, 480)
[18:56:48.2142904] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:48.2147313] > [Debug] NameScan:273 -> Name scanning at: (1108, 396)
[18:56:51.2506809] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:51.2509909] > [Debug] NameScan:273 -> Name scanning at: (1081, 622)
[18:56:52.4003255] > [Info]  Saving config...
[18:56:52.4093108] > [Info]  Config saved!
[18:56:53.9942783] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:53.9946233] > [Debug] NameScan:273 -> Name scanning at: (1017, 266)
[18:56:54.9714449] > [Debug] OnKeyUp:100 -> Pressed: Left
[18:56:54.9717717] > [Debug] NameScan:273 -> Name scanning at: (1078, 376)
[18
```
</details>

**Comment by Blightbuster** [comment]
Will be tracked in #424
Thanks for reporting the issue non the less ❤️
