### ISSUE TITLE
Access to the path 'C:\Users\Juan\Desktop\rat scanner\Log.txt' is denied.

### ISSUE THREAD

**Issue by mrlotux** [RatScanner/RatScanner#429]
**Error**
Access to the path 'C:\Users\Juan\Desktop\rat scanner\Log.txt' is denied.
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Access to the path 'C:\Users\Juan\Desktop\rat scanner\Log.txt' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Juan\Desktop\rat scanner\Log.txt' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, F
```
<details>
<summary>Log</summary>

```
[01:05:59.3230910] > [Info]  ----- RatScanner 3.3.8 -----
[01:05:59.3231094] > [Info]  Starting RatScanner...
[01:05:59.3231137] > [Info]  Loading config...
[01:05:59.3262633] > [Info]  Setting temporary default item...
[01:05:59.3282801] > [Info]  Checking for item data updates...
[01:05:59.3332454] > [Info]  Loading resource "RSItemDataBundleVersion"...
[01:05:59.8106309] > [Info]  Initializing tarkov tracker database
[01:05:59.8108329] > [Info]  Initializing hotkey manager...
[01:05:59.8144334] > [Info]  UI Ready!
[01:06:00.8152937] > [Info]  Checking for updates...
[01:06:00.8155849] > [Info]  Loading resource "RSClientVersion"...
[01:06:00.8567061] > [Info]  Loading progress data...
[01:06:01.3046698] > [Info]  Loading price data...
[01:06:01.5539467] > [Info]  Loading TarkovTracker data...
[01:06:01.5539612] > [Info]  Initializing RatEye...
[01:06:09.1578188] > [Info]  Setting up timer routines...
[01:06:09.1578487] > [Info]  Setting default item...
[01:06:09.1640062] > [Info]  Enabling hotkeys...
[01:06:09.1640296] > [Info]  Ready!
[01:06:15.2097550] > [Info]  Saving config...
[01:06:15.2185139] > [Info]  Config saved!
[01:11:09.1344311] > [Info]  Refreshing TarkovTracker DB...
[01:13:26.2650446] > [Info]  Saving config...
[01:13:26.2711656] > [Info]  Config saved!
[01:16:09.1120853] > [Info]  Refreshing TarkovTracker DB...
[01:19:51.0964962] > [Info]  Saving config...
[01:19:51.1024881] > [Info]  Config saved!
[01:21:09.0884436] > [Info]  Refreshing TarkovTracker DB...
[01:26:09.0649339] > [Info]  Refreshing TarkovTracker DB...
[01:31:09.0473824] > [Info]  Refreshing TarkovTracker DB...
[01:36:09.0328282] > [Info]  Refreshing Market DB...
[01:36:09.0357356] > [Info]  Refreshing TarkovTracker DB...
[01:41:09.0272940] > [Info]  Refreshing TarkovTracker DB...
[01:46:09.0297648] > [Info]  Refreshing TarkovTracker DB...
[01:51:09.0267618] > [Info]  Refreshing TarkovTracker DB...
[01:56:09.0138364] > [Info]  Refreshing TarkovTracker DB...

```
</details>

**Comment by Blightbuster** [comment]
Will be tracked in #424
Thanks for reporting the issue non the less ❤️
