### ISSUE TITLE
Could not find a part of the path 'C:\Users\Baobab\AppData\Roaming\Battlestate Games\Escape From Tarkov\Settings\Graphics.ini'.

### ISSUE THREAD

**Issue by XYUd** [RatScanner/RatScanner#431]
**Error**
Could not find a part of the path 'C:\Users\Baobab\AppData\Roaming\Battlestate Games\Escape From Tarkov\Settings\Graphics.ini'.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Baobab\AppData\Roaming\Battlestate Games\Escape From Tarkov\Settings\Graphics.ini'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptio
```
<details>
<summary>Log</summary>

```
[16:45:42.6262748] > [Warning] Config version (-1) is not supported!
[16:45:42.6400290] > [Error] Could not find a part of the path 'C:\Users\Baobab\AppData\Roaming\Battlestate Games\Escape From Tarkov\Settings\Graphics.ini'.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Baobab\AppData\Roaming\Battlestate Games\Escape From Tarkov\Settings\Graphics.ini'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
[16:45:45.1925598] > [Info]  Loading resource "RSGithubLink"...
[16:48:07.2089786] > [Warning] Config version (-1) is not supported!
[16:48:07.2216089] > [Error] Could not find a part of the path 'C:\Users\Baobab\AppData\Roaming\Battlestate Games\Escape From Tarkov\Settings\Graphics.ini'.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Baobab\AppData\Roaming\Battlestate Games\Escape From Tarkov\Settings\Graphics.ini'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String pa
```
</details>

**Comment by Blightbuster** [comment]
Did you ever start tarkov on that PC?
