### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Gwynbleidd112** [RatScanner/RatScanner#432]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
```
<details>
<summary>Log</summary>

```
[15:10:06.9349410] > [Warning] Config version (-1) is not supported!
[15:10:06.9700158] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
[15:10:10.8035807] > [Info]  Loading resource "RSGithubLink"...
[15:13:02.6959204] > [Warning] Config version (-1) is not supported!
[15:13:02.7312628] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()

```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting, this is fixed in v3.3.10.
