### ISSUE TITLE
The system cannot find the path specified. (0x80070003)

### ISSUE THREAD

**Issue by JoShMiQueL** [RatScanner/RatScanner#435]
**Error**
The system cannot find the path specified. (0x80070003)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebV
```
<details>
<summary>Log</summary>

```
[11:39:39.4823337] > [Info]  ----- RatScanner 3.3.9 -----
[11:39:39.4823489] > [Info]  Starting RatScanner...
[11:39:39.4823521] > [Info]  Loading config...
[11:39:39.4847829] > [Info]  Setting temporary default item...
[11:39:39.4863576] > [Info]  Checking for item data updates...
[11:39:39.4895875] > [Info]  Loading resource "RSItemDataBundleVersion"...
[11:39:40.1655970] > [Info]  A new item data bundle is available: 20220822
[11:39:40.1656121] > [Info]  Loading resource "RSItemDataBundleLink"...
[11:39:40.2865608] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/itemData-2022-08-22.zip"...
[11:40:04.0331052] > [Info]  Successfully updated to the latest item data bundle
[11:40:04.0331285] > [Info]  Initializing tarkov tracker database
[11:40:04.0333636] > [Info]  Initializing hotkey manager...
[11:40:04.0370905] > [Info]  UI Ready!
[11:40:04.1444155] > [Error] The system cannot find the path specified. (0x80070003)
 -------------------- 
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The system cannot find the path specified. (0x80070003))
 ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   --- End of inner exception stack trace ---
[11:40:05.0527805] > [Info]  Checking for updates...
[11:40:05.0530815] > [Info]  Loading resource "RSClientVersion"...
[11:40:05.1686510] > [Info]  Loading progress data...
[11:40:05.6195494] > [Info]  Loading price data...
[11:40:06.1531857] > [Info]  Loading TarkovTracker data...
[11:40:06.1532217] > [Info]  Initializing RatEye...
[11:40:13.1250348] > [Info]  Setting up timer routines...
[11:40:13.1250736] > [Info]  Setting default item...
[11:40:13.1333743] > [Info]  Enabling hotkeys...
[11:40
```
</details>

**Comment by Blightbuster** [comment]
Looks like your webview2 installation is corrupt. Please manually uninstall webview2, restart your pc, install it again and then try starting rat scanner.
