### ISSUE TITLE
Cannot start process because a file name has not been provided.

### ISSUE THREAD

**Issue by ctmpete** [RatScanner/RatScanner#439]
**Error**
Cannot start process because a file name has not been provided.
```
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at RatRazor.Pages.App.Index.OpenURL(String url) in D:\a\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 116
   at RatRazor.Pages.App.Index.OpenTarkovDev() in D:\a\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 105
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
<details>
<summary>Log</summary>

```
[19:22:31.4990718] > [Info]  ----- RatScanner 3.3.10 -----
[19:22:31.4993332] > [Info]  Starting RatScanner...
[19:22:31.4993394] > [Info]  Loading config...
[19:22:31.5015269] > [Info]  Setting temporary default item...
[19:22:31.5029128] > [Info]  Checking for item data updates...
[19:22:31.5057349] > [Info]  Loading resource "RSItemDataBundleVersion"...
[19:22:31.8912477] > [Info]  Initializing tarkov tracker database
[19:22:31.8914010] > [Info]  Initializing hotkey manager...
[19:22:31.8937273] > [Info]  UI Ready!
[19:22:32.9022577] > [Info]  Checking for updates...
[19:22:32.9026017] > [Info]  Loading resource "RSClientVersion"...
[19:22:32.9528722] > [Info]  Loading progress data...
[19:22:33.1436564] > [Info]  Loading price data...
[19:22:33.4148870] > [Info]  Loading TarkovTracker data...
[19:22:33.4149056] > [Info]  Initializing RatEye...
[19:22:33.9725896] > [Error] Cannot start process because a file name has not been provided.
 -------------------- 
 System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at RatRazor.Pages.App.Index.OpenURL(String url) in D:\a\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 116
   at RatRazor.Pages.App.Index.OpenTarkovDev() in D:\a\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 105
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[19:22:36.9227034] > [Info]  Loading resource "RSFAQLink"...
[19:22:38.2286942] > [Info]  Setting up timer routines...
[19:22:38.2287346] > [Info]  Setting default item...
[19:22:38.2349888] > [Info]  Enabling hotkeys...
[19:22:38.2350147] > [Info]  Ready!
[19:22:39.6418768] > [Debug] OnKeyUp:100 -> Pressed: Left
[19:22:39.6432036] > [Debug] NameScan:273 -> Name scanning at: (1006, 591)

```
</details>

**Comment by Blightbuster** [comment]
Hey, it looks like your trying to build rat scanner from source. Is that correct?

If you just want to use rat scanner, there are pre-compiled version available here:
https://github.com/RatScanner/RatScanner/releases

**Comment by Blightbuster** [comment]
Tracked in #452 
Thanks for reporting ❤️

**Comment by ctmpete** [comment]
I did not do this. I did not authorize this. My account has been
compromised.
