### ISSUE TITLE
Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.

### ISSUE THREAD

**Issue by Beasly36** [RatScanner/RatScanner#440]
**Error**
Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
```
Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)
   at RatEye.Processing.Inspection.GetTesseractEngine()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9
```
<details>
<summary>Log</summary>

```
[15:14:16.9524760] > [Info]  ----- RatScanner 3.3.10 -----
[15:14:16.9524881] > [Info]  Starting RatScanner...
[15:14:16.9524901] > [Info]  Loading config...
[15:14:16.9526282] > [Warning] Config version (-1) is not supported!
[15:14:16.9544584] > [Info]  Setting temporary default item...
[15:14:16.9555607] > [Info]  Checking for item data updates...
[15:14:16.9573372] > [Info]  Loading resource "RSItemDataBundleVersion"...
[15:14:17.6382396] > [Info]  Initializing tarkov tracker database
[15:14:17.6383875] > [Info]  Initializing hotkey manager...
[15:14:17.6401250] > [Info]  UI Ready!
[15:14:18.6471629] > [Info]  Checking for updates...
[15:14:18.6478858] > [Info]  Loading resource "RSClientVersion"...
[15:14:18.7896556] > [Info]  Loading progress data...
[15:14:19.1738767] > [Info]  Loading price data...
[15:14:19.7759454] > [Info]  Loading TarkovTracker data...
[15:14:19.7759604] > [Info]  Initializing RatEye...
[15:14:21.9892019] > [Info]  Setting up timer routines...
[15:14:21.9892204] > [Info]  Setting default item...
[15:14:21.9930468] > [Info]  Enabling hotkeys...
[15:14:21.9930716] > [Info]  Ready!
[15:14:22.5260064] > [Error] Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
 -------------------- 
 Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)
   at RatEye.Processing.Inspection.GetTesseractEngine()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[15:14:24.9307122] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Please create a log file of the tesseract output as described [here ](https://github.com/charlesw/tesseract/wiki/Error-1#example-systemdiagnostics-configuration)and upload it.

**Comment by Blightbuster** [comment]
This has been fixed in a later release.
