### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by shinev01** [RatScanner/RatScanner#441]
**Error**
Sequence contains no elements
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at RatScanner.ViewModel.MenuVM.get_LastItemScan()
   at RatRazor.Pages.App.Index.get_item() in D:\a\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 91
   at RatRazor.Pages.App.Index.<BuildRenderTree>b__0_18(RenderTreeBuilder __builder4) in D:\a\RatScanner\RatScanner\RatRazor\Pages\App\Index.razor:line 60
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuild
```
<details>
<summary>Log</summary>

```
[16:51:05.4690577] > [Info]  ----- RatScanner 3.3.10 -----
[16:51:05.4692609] > [Info]  Starting RatScanner...
[16:51:05.4692633] > [Info]  Loading config...
[16:51:05.4717255] > [Info]  Setting temporary default item...
[16:51:05.4742452] > [Info]  Checking for item data updates...
[16:51:05.4768090] > [Info]  Loading resource "RSItemDataBundleVersion"...
[16:51:06.0917723] > [Info]  Initializing tarkov tracker database
[16:51:06.0922477] > [Info]  Initializing hotkey manager...
[16:51:06.0948868] > [Info]  UI Ready!
[16:51:07.1008712] > [Info]  Checking for updates...
[16:51:07.1022806] > [Info]  Loading resource "RSClientVersion"...
[16:51:07.2136795] > [Info]  Loading progress data...
[16:51:07.8985716] > [Info]  Loading price data...
[16:51:08.4151494] > [Info]  Loading TarkovTracker data...
[16:51:08.4151610] > [Info]  Initializing RatEye...
[16:51:13.7167161] > [Info]  Setting up timer routines...
[16:51:13.7168922] > [Info]  Setting default item...
[16:51:13.7310344] > [Info]  Enabling hotkeys...
[16:51:13.7313628] > [Info]  Ready!
[16:51:24.2497971] > [Info]  Saving config...
[16:51:24.3478963] > [Info]  Config saved!
[16:53:12.7063354] > [Info]  Saving config...
[16:53:12.7303235] > [Info]  Config saved!
[16:53:20.3472471] > [Info]  Saving config...
[16:53:20.3637829] > [Info]  Config saved!
[16:53:42.0713433] > [Info]  Saving config...
[16:53:42.0889333] > [Info]  Config saved!
[16:56:13.7307145] > [Info]  Refreshing TarkovTracker DB...

```
</details>

**Comment by Blightbuster** [comment]
Tracked in #405 
Thanks for submitting the issue ❤️
