### ISSUE TITLE
型 'System.Windows.Controls.UIElementCollection' のコレクションに値を追加しているときに例外がスローされました。

### ISSUE THREAD

**Issue by marinaris** [RatScanner/RatScanner#453]
**Error**
型 'System.Windows.Controls.UIElementCollection' のコレクションに値を追加しているときに例外がスローされました。
```
System.Windows.Markup.XamlParseException: 型 'System.Windows.Controls.UIElementCollection' のコレクションに値を追加しているときに例外がスローされました。
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXaml
```
<details>
<summary>Log</summary>

```
[04:43:27.0819396] > [Info]  ----- RatScanner 3.4.0 -----
[04:43:27.0819526] > [Info]  Starting RatScanner...
[04:43:27.0819604] > [Info]  Loading config...
[04:43:27.0833719] > [Info]  Setting temporary default item...
[04:43:27.0841810] > [Info]  Checking for item data updates...
[04:43:27.0856079] > [Info]  Loading resource "RSItemDataBundleVersion"...
[04:43:27.9243224] > [Info]  Initializing tarkov tracker database
[04:43:27.9244332] > [Info]  Initializing hotkey manager...
[04:43:27.9260486] > [Info]  UI Ready!
[04:43:28.9302934] > [Info]  Checking for updates...
[04:43:28.9306158] > [Info]  Loading resource "RSClientVersion"...
[04:43:29.1155064] > [Info]  A new version is available: 3.3.10
[04:43:29.1155178] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[04:43:52.7362695] > [Error] 型 'System.Windows.Controls.UIElementCollection' のコレクションに値を追加しているときに例外がスローされました。
 -------------------- 
 System.Windows.Markup.XamlParseException: 型 'System.Windows.Controls.UIElementCollection' のコレクションに値を追加しているときに例外がスローされました。
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RatScanner.PageSwitcher.InitializeComponent()
   at RatScanner.PageSwitcher..ctor()
[04:43:54.7654645] > [Info]  Loading resource "RSGithubLink"...
[04:44:39.2432356] > [Error] 型 'System.Windows.Controls.UIElementCollection' のコレクションに値を追加しているときに例外がスローされました。
 -------------------- 
 System.Windows.Markup.XamlParseExcept
```
</details>

**Comment by Blightbuster** [comment]
Will be tracked in #449 
Thanks for reporting the issue non the less ❤️
