### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mariocostaPT** [RatScanner/RatScanner#454]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[08:37:33.2748334] > [Info]  ----- RatScanner 3.4.0 -----
[08:37:33.2748586] > [Info]  Starting RatScanner...
[08:37:33.2748623] > [Info]  Loading config...
[08:37:33.2815615] > [Info]  Setting temporary default item...
[08:37:33.2835935] > [Info]  Checking for item data updates...
[08:37:33.2859764] > [Info]  Loading resource "RSItemDataBundleVersion"...
[08:37:37.8820093] > [Info]  Initializing tarkov tracker database
[08:37:37.8821594] > [Info]  Initializing hotkey manager...
[08:37:37.8845888] > [Info]  UI Ready!
[08:37:38.8960196] > [Info]  Checking for updates...
[08:37:38.8965078] > [Info]  Loading resource "RSClientVersion"...
[08:37:39.0187461] > [Info]  A new version is available: 3.3.10
[08:37:39.0187633] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[08:38:17.0609207] > [Info]  Saving config...
[08:38:17.0863233] > [Info]  Config saved!
[08:38:23.7633532] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[08:38:34.2149089] > [Info]  Loading resource "RSFAQLink"...
[08:38:34.2615642] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)

```
</details>

**Comment by Blightbuster** [comment]
Will be tracked in #457 
Thanks for reporting the issue non the less ❤️
