### ISSUE TITLE
RatConfig.get_GameScale() causing null ptr exception

### ISSUE THREAD

**Issue by Fortifier42** [RatScanner/RatScanner#457]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[09:28:41.4418252] > [Info]  ----- RatScanner 3.4.1 -----
[09:28:41.4421031] > [Info]  Starting RatScanner...
[09:28:41.4421061] > [Info]  Loading config...
[09:28:41.4454131] > [Info]  Screen Info: 2560x1440 at 100%
[09:28:41.4454330] > [Info]  Setting temporary default item...
[09:28:41.4497327] > [Info]  Checking for item data updates...
[09:28:41.4615632] > [Info]  Loading resource "RSItemDataBundleVersion"...
[09:28:42.7378995] > [Info]  Initializing tarkov tracker database
[09:28:42.7381742] > [Info]  Initializing hotkey manager...
[09:28:42.7416291] > [Info]  UI Ready!
[09:28:43.7457817] > [Info]  Checking for updates...
[09:28:43.7463221] > [Info]  Loading resource "RSClientVersion"...
[09:28:43.9742202] > [Info]  Loading progress data...
[09:28:48.2703497] > [Info]  Loading price data...
[09:28:48.9744654] > [Info]  Saving config...
[09:28:48.9992637] > [Info]  Config saved!
[09:28:49.2890592] > [Info]  Loading TarkovTracker data...
[09:28:49.2890742] > [Info]  Loading TarkovTracker...
[09:28:50.2392611] > [Info]  Initializing RatEye...
[09:28:51.5517800] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__9_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[09:28:56.9490986] > [Info]  Setting up timer routines...
[09:28:56.9491276] > [Info]  Setting default item...
[09:28:56.9553712] > [Info]  Enabling hotkeys...
[09:28:56.9553915] > [Info]  Ready!

```
</details>

**Comment by FriedEngineer** [comment]
Try running it as admin once.

**Comment by Blightbuster** [comment]
Will be tracked in #398
Thanks for reporting the issue non the less ❤️
