### ISSUE TITLE
3.5.4 Something is still wrong with the Tracking

### ISSUE THREAD

**Issue by Ryuichiro** [RatScanner/RatScanner#468]
**Describe the bug**
For some reason, I still get some FIR tracking for my teammate, for an item that is not needed FIR for any quest.
You could argue that 2 are needed to finish quests, but then it should show 2 none-FIR for both me and my teammate.

**To Reproduce**
1. Have a Teammate in TarkovTracker
2. Link Ratscanner to TarkovTracker using an API key
3. Search for a `March Tactical 3-24x42 FFP 30mm riflescope`.

**Expected behavior**
The same amount is needed by you and your teammate.

**Screenshots**
![RatScanner_2023-01-17_21-10-21](https://user-images.githubusercontent.com/4333206/213002111-7aaaa039-6d3d-4c53-b185-51ff3f1cc810.png)
![image](https://user-images.githubusercontent.com/4333206/213002166-e99d30a5-f96d-4d4d-8cd9-9dad03c02009.png)

**Log file content**
```
[21:09:57.6116832] > [Info]  ----- RatScanner 3.5.4 -----
[21:09:57.6122274] > [Info]  Starting RatScanner...
[21:09:57.6122306] > [Info]  Loading config...
[21:09:57.6141768] > [Info]  Screen Info: 2560x1440 at 100%
[21:09:57.6141868] > [Info]  Setting temporary default item...
[21:09:57.6156055] > [Info]  Initializing tarkov tracker database
[21:09:57.6157537] > [Info]  Initializing hotkey manager...
[21:09:57.6183600] > [Info]  UI Ready!
[21:09:58.6225844] > [Info]  Checking for updates...
[21:09:58.6245727] > [Info]  Loading resource "RSClientVersion"...
[21:09:59.0853617] > [Info]  Loading item data...
[21:10:02.0899775] > [Info]  Loading price data...
[21:10:02.6800318] > [Info]  Loading TarkovTracker data...
[21:10:02.6800576] > [Info]  Loading TarkovTracker...
[21:10:04.0356514] > [Info]  Initializing RatEye...
[21:10:06.4923388] > [Info]  Setting up timer routines...
[21:10:06.4923774] > [Info]  Setting default item...
[21:10:06.4952275] > [Info]  Enabling hotkeys...
[21:10:06.4952509] > [Info]  Ready!
[21:15:06.5012468] > [Info]  Refreshing TarkovTracker DB...
[21:20:07.2817504] > [Info]  Refreshing TarkovTracker DB...
[21:25:08.0360732] > [Info]  Refreshing TarkovTracker DB...
[21:30:08.6138320] > [Info]  Refreshing TarkovTracker DB...
[21:35:09.2179897] > [Info]  Refreshing TarkovTracker DB...
[21:40:06.4991609] > [Info]  Refreshing Market DB...
[21:40:09.8534166] > [Info]  Refreshing TarkovTracker DB...
[21:45:10.5705435] > [Info]  Refreshing TarkovTracker DB...
[21:50:11.1384145] > [Info]  Refreshing TarkovTracker DB...
[21:55:12.0572380] > [Info]  Refreshing TarkovTracker DB...
[22:00:12.7643587] > [Info]  Refreshing TarkovTracker DB...
[22:05:13.5517685] > [Info]  Refreshing TarkovTracker DB...
[22:10:07.3545928] > [Info]  Refreshing Market DB...
[22:10:14.2242756] > [Info]  Refreshing TarkovTracker DB...
[22:15:14.9579786] > [Info]  Refreshing TarkovTracker DB...
[22:20:15.6322571] > [Info]  Refreshing TarkovTracker DB...
[22:25:16.2587805] > [Info]  Refreshing TarkovTracker DB...
[22:30:17.0223800] > [Info]  Refreshing TarkovTracker DB...
[22:35:17.8016694] > [Info]  Refreshing TarkovTracker DB...
[22:40:08.2526157] > [Info]  Refreshing Market DB...
[22:40:18.6801029] > [Info]  Refreshing TarkovTracker DB...
[22:45:19.2583088] > [Info]  Refreshing TarkovTracker DB...
[22:50:20.1816206] > [Info]  Refreshing TarkovTracker DB...
[22:55:21.3765073] > [Info]  Refreshing TarkovTracker DB...
[23:00:22.1960599] > [Info]  Refreshing TarkovTracker DB...
[23:05:22.9327642] > [Info]  Refreshing TarkovTracker DB...
[23:10:09.1648361] > [Info]  Refreshing Market DB...
[23:10:23.9851260] > [Info]  Refreshing TarkovTracker DB...
[23:15:24.6869904] > [Info]  Refreshing TarkovTracker DB...
[23:20:25.4772710] > [Info]  Refreshing TarkovTracker DB...
[23:25:26.4994899] > [Info]  Refreshing TarkovTracker DB...
[23:30:27.7502392] > [Info]  Refreshing TarkovTracker DB...
[23:35:28.4691504] > [Info]  Refreshing TarkovTracker DB...
[23:40:10.0307909] > [Info]  Refreshing Market DB...
[23:40:29.1468602] > [Info]  Refreshing TarkovTracker DB...
[05:09:23.8640722] > [Info]  Refreshing TarkovTracker DB...
[13:55:06.0469665] > [Warning] Unable to capture screenshot
[13:55:06.0909400] > System.ComponentModel.Win32Exception (6): The handle is invalid.
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at RatScanner.RatScannerMain.GetScreenshot(Vector2 vector2, Size size)
[13:58:59.0344880] > [Info]  Refreshing TarkovTracker DB...
[14:03:59.9365890] > [Info]  Refreshing TarkovTracker DB...
[14:09:00.5179578] > [Info]  Refreshing TarkovTracker DB...
[14:14:01.2893962] > [Info]  Refreshing TarkovTracker DB...
[14:18:39.2077653] > [Info]  Refreshing Market DB...
[14:19:02.0901044] > [Info]  Refreshing TarkovTracker DB...
[14:24:02.6824670] > [Info]  Refreshing TarkovTracker DB...
[14:29:03.4396060] > [Info]  Refreshing TarkovTracker DB...
[14:34:04.2248089] > [Info]  Refreshing TarkovTracker DB...
[14:39:05.0937195] > [Info]  Refreshing TarkovTracker DB...
[14:44:05.8819834] > [Info]  Refreshing TarkovTracker DB...
[14:48:40.2995241] > [Info]  Refreshing Market DB...
[14:49:06.4800951] > [Info]  Refreshing TarkovTracker DB...
[14:54:07.5115061] > [Info]  Refreshing TarkovTracker DB...
[14:59:10.0971921] > [Info]  Refreshing TarkovTracker DB...
[15:04:10.8302851] > [Info]  Refreshing TarkovTracker DB...
[15:09:11.5737833] > [Info]  Refreshing TarkovTracker DB...
[15:14:12.3559734] > [Info]  Refreshing TarkovTracker DB...
[15:18:41.4252702] > [Info]  Refreshing Market DB...
[15:19:13.1427694] > [Info]  Refreshing TarkovTracker DB...
[15:24:13.8633776] > [Info]  Refreshing TarkovTracker DB...
[15:29:15.1763099] > [Info]  Refreshing TarkovTracker DB...
[15:34:16.0657690] > [Info]  Refreshing TarkovTracker DB...
[15:39:16.7886717] > [Info]  Refreshing TarkovTracker DB...
[15:44:18.0096128] > [Info]  Refreshing TarkovTracker DB...
[15:48:42.2843843] > [Info]  Refreshing Market DB...
[15:49:18.9324756] > [Info]  Refreshing TarkovTracker DB...
[15:54:19.8142888] > [Info]  Refreshing TarkovTracker DB...
[15:59:20.6392213] > [Info]  Refreshing TarkovTracker DB...
[16:04:21.3449804] > [Info]  Refreshing TarkovTracker DB...
[16:09:22.1109832] > [Info]  Refreshing TarkovTracker DB...
[16:14:22.7465114] > [Info]  Refreshing TarkovTracker DB...
[16:18:43.2405988] > [Info]  Refreshing Market DB...
[16:19:23.5108536] > [Info]  Refreshing TarkovTracker DB...
[16:24:24.2701855] > [Info]  Refreshing TarkovTracker DB...
[16:29:25.1112795] > [Info]  Refreshing TarkovTracker DB...
[16:34:25.7518775] > [Info]  Refreshing TarkovTracker DB...
[16:39:26.5307036] > [Info]  Refreshing TarkovTracker DB...
[16:44:27.1356287] > [Info]  Refreshing TarkovTracker DB...
[16:48:44.2078340] > [Info]  Refreshing Market DB...
[16:49:27.7419538] > [Info]  Refreshing TarkovTracker DB...
[16:54:28.3134655] > [Info]  Refreshing TarkovTracker DB...
[16:59:28.9081920] > [Info]  Refreshing TarkovTracker DB...
[17:04:29.5697433] > [Info]  Refreshing TarkovTracker DB...
[17:09:30.3503386] > [Info]  Refreshing TarkovTracker DB...
[17:14:31.5952808] > [Info]  Refreshing TarkovTracker DB...
[17:18:45.0566900] > [Info]  Refreshing Market DB...
[17:19:32.4442903] > [Info]  Refreshing TarkovTracker DB...
[17:24:33.1330778] > [Info]  Refreshing TarkovTracker DB...
[17:29:34.0840458] > [Info]  Refreshing TarkovTracker DB...
[17:34:34.7678812] > [Info]  Refreshing TarkovTracker DB...
[17:39:35.5506563] > [Info]  Refreshing TarkovTracker DB...
[17:44:36.3214594] > [Info]  Refreshing TarkovTracker DB...
[17:48:45.9147929] > [Info]  Refreshing Market DB...
[17:49:36.9706235] > [Info]  Refreshing TarkovTracker DB...
[17:54:37.5464843] > [Info]  Refreshing TarkovTracker DB...
[17:59:38.7666742] > [Info]  Refreshing TarkovTracker DB...
[18:04:39.4659123] > [Info]  Refreshing TarkovTracker DB...
[18:09:40.0509653] > [Info]  Refreshing TarkovTracker DB...
[18:14:40.7806402] > [Info]  Refreshing TarkovTracker DB...
[18:18:46.9227434] > [Info]  Refreshing Market DB...
[18:19:41.5819575] > [Info]  Refreshing TarkovTracker DB...
[18:24:42.2016209] > [Info]  Refreshing TarkovTracker DB...
[18:29:42.9902508] > [Info]  Refreshing TarkovTracker DB...
[18:34:43.6494899] > [Info]  Refreshing TarkovTracker DB...
[18:39:44.4571739] > [Info]  Refreshing TarkovTracker DB...
[18:44:45.1804739] > [Info]  Refreshing TarkovTracker DB...
[18:48:48.1862008] > [Info]  Refreshing Market DB...
[18:49:45.8185345] > [Info]  Refreshing TarkovTracker DB...
[18:54:46.7103742] > [Info]  Refreshing TarkovTracker DB...
[18:59:47.5033742] > [Info]  Refreshing TarkovTracker DB...
[19:04:48.0824872] > [Info]  Refreshing TarkovTracker DB...
[19:09:48.9431855] > [Info]  Refreshing TarkovTracker DB...
[19:14:49.7028079] > [Info]  Refreshing TarkovTracker DB...
[19:18:49.0356973] > [Info]  Refreshing Market DB...
[19:19:50.3565396] > [Info]  Refreshing TarkovTracker DB...
[19:24:51.0541966] > [Info]  Refreshing TarkovTracker DB...
[19:29:51.8035529] > [Info]  Refreshing TarkovTracker DB...
[19:34:52.4681432] > [Info]  Refreshing TarkovTracker DB...
[19:39:53.1209423] > [Info]  Refreshing TarkovTracker DB...
[19:44:53.6821468] > [Info]  Refreshing TarkovTracker DB...
[19:48:50.1237608] > [Info]  Refreshing Market DB...
[19:49:54.2743097] > [Info]  Refreshing TarkovTracker DB...
[19:54:55.4142332] > [Info]  Refreshing TarkovTracker DB...
[19:59:56.1373917] > [Info]  Refreshing TarkovTracker DB...
[20:04:56.6930204] > [Info]  Refreshing TarkovTracker DB...
[20:09:57.4705973] > [Info]  Refreshing TarkovTracker DB...
```

**Comment by Ryuichiro** [comment]
I just didn't see my own tracking, because I expected my name to be listed. 🤦
