### ISSUE TITLE
Could not find a part of the path 'C:\Users\fires\AppData\Local\Temp\Rar$EXa19444.33030\Data\icons\correlation.json'.

### ISSUE THREAD

**Issue by Questionmarkl** [RatScanner/RatScanner#473]
**Error**
Could not find a part of the path 'C:\Users\fires\AppData\Local\Temp\Rar$EXa19444.33030\Data\icons\correlation.json'.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fires\AppData\Local\Temp\Rar$EXa19444.33030\Data\icons\correlation.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at RatEye
```
<details>
<summary>Log</summary>

```
[20:04:19.1972736] > [Info]  Loading price data...
[20:04:19.3503418] > [Info]  Loading TarkovTracker data...
[20:04:19.3503538] > [Info]  Initializing RatEye...
[20:04:19.3649949] > [Error] Could not find a part of the path 'C:\Users\fires\AppData\Local\Temp\Rar$EXa19444.33030\Data\icons\correlation.json'.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fires\AppData\Local\Temp\Rar$EXa19444.33030\Data\icons\correlation.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at RatEye.IconManager.ReadFileNonBlocking(String path)
   at RatEye.IconManager.LoadStaticCorrelationData()
   at RatEye.IconManager.LoadStaticIcons()
   at RatEye.IconManager..ctor(Config config)
   at RatEye.RatEyeEngine..ctor(Config config, Database itemDatabase)
   at RatScanner.RatScannerMain.SetupRatEye()
   at RatScanner.RatScannerMain.<.ctor>b__18_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[20:04:22.4102997] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Hey, please unzip RatScanner, before trying to execute it.
