### ISSUE TITLE
Specified cast is not valid.

### ISSUE THREAD

**Issue by xXNoKXx** [RatScanner/RatScanner#474]
**Error**
Specified cast is not valid.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Settings3.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3
```
<details>
<summary>Log</summary>

```
[01:59:25.5678215] > [Info]  ----- RatScanner 3.5.4 -----
[01:59:25.5678412] > [Info]  Starting RatScanner...
[01:59:25.5678420] > [Info]  Loading config...
[01:59:25.5689244] > [Info]  Screen Info: 1920x1080 at 125%
[01:59:25.5689317] > [Info]  Setting temporary default item...
[01:59:25.5702163] > [Info]  Initializing tarkov tracker database
[01:59:25.5703174] > [Info]  Initializing hotkey manager...
[01:59:25.5721658] > [Info]  UI Ready!
[01:59:26.5834709] > [Info]  Checking for updates...
[01:59:26.5869738] > [Info]  Loading resource "RSClientVersion"...
[01:59:27.4097201] > [Info]  Loading item data...
[01:59:29.8515791] > [Info]  Loading price data...
[01:59:30.5132019] > [Info]  Loading TarkovTracker data...
[01:59:30.5132154] > [Info]  Initializing RatEye...
[01:59:32.6427090] > [Info]  Setting up timer routines...
[01:59:32.6427332] > [Info]  Setting default item...
[01:59:32.6449485] > [Info]  Enabling hotkeys...
[01:59:32.6449710] > [Info]  Ready!
[01:59:49.9659973] > [Error] Specified cast is not valid.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Settings3.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.set_AreBrowserAcceleratorKeysEnabled(Boolean value)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, V
```
</details>

**Comment by Blightbuster** [comment]
To fix this, uninstall webview2 and install it again.
