### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Heliox66** [RatScanner/RatScanner#479]
**Error**
Object reference not set to an instance of an object.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.TarkovDevAPI.GetNeededItems(Int64 ttl)
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, Boolean firOnly, UserProgress progress)
   at RatScanner.ViewModel.MenuVM.get_TaskRemaining()
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(RenderTreeBuilder __builder5)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass11_0.<No
```
<details>
<summary>Log</summary>

```
[22:59:41.0696767] > [Info]  ----- RatScanner 3.5.4 -----
[22:59:41.0696868] > [Info]  Starting RatScanner...
[22:59:41.0696873] > [Info]  Loading config...
[22:59:41.0713976] > [Info]  Screen Info: 1920x1080 at 100%
[22:59:41.0714018] > [Info]  Setting temporary default item...
[22:59:41.0722114] > [Info]  Initializing tarkov tracker database
[22:59:41.0722992] > [Info]  Initializing hotkey manager...
[22:59:41.0741311] > [Info]  UI Ready!
[22:59:41.7841040] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.TarkovDevAPI.GetNeededItems(Int64 ttl)
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, Boolean firOnly, UserProgress progress)
   at RatScanner.ViewModel.MenuVM.get_TaskRemaining()
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(RenderTreeBuilder __builder5)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass11_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[22:59:42.0754164] > [Info]  Checking for updates...
[22:59:42.0768093] > [Info]  Loading resource "RSClientVersion"...
[22:59:42.1885257] > [Info]  Loading item data...

```
</details>

**Comment by Blightbuster** [comment]
Currently having some trouble with the backend will be back to normal very soon, sorry for the trouble.

**Comment by Heliox66** [comment]
okay thank you
just got confused worked for a min then that happened

**Comment by snorrka** [comment]
> Currently having some trouble with the backend will be back to normal very soon, sorry for the trouble.
thanks was wondering why it wasnt working
