### ISSUE TITLE
A task was canceled.

### ISSUE THREAD

**Issue by godxxy5453** [RatScanner/RatScanner#480]
**Error**
A task was canceled.
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (A task was canceled.))
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.TarkovDevAPI.Get(String query)
   at RatScanner.TarkovDevAPI.GetNeededItems(Int64 ttl)
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, Boolean firOnly, UserProgress progress)
   at RatScanner.ViewModel.MenuVM.get_Tas
```
<details>
<summary>Log</summary>

```
[09:27:32.1689455] > [Info]  ----- RatScanner 3.5.4 -----
[09:27:32.1691991] > [Info]  Starting RatScanner...
[09:27:32.1692011] > [Info]  Loading config...
[09:27:32.1725189] > [Info]  Screen Info: 2544x1353 at 100%
[09:27:32.1725264] > [Info]  Setting temporary default item...
[09:27:32.1744659] > [Info]  Initializing tarkov tracker database
[09:27:32.1745605] > [Info]  Initializing hotkey manager...
[09:27:32.1767428] > [Info]  UI Ready!
[09:27:33.3119988] > [Info]  Checking for updates...
[09:27:33.3161229] > [Info]  Loading resource "RSClientVersion"...
[09:27:34.2756813] > [Info]  Loading item data...
[09:27:37.8141279] > [Info]  Loading price data...
[09:27:38.7187624] > [Info]  Loading TarkovTracker data...
[09:27:38.7187746] > [Info]  Initializing RatEye...
[09:27:48.5190244] > [Info]  Setting up timer routines...
[09:27:48.5190434] > [Info]  Setting default item...
[09:27:48.5213469] > [Info]  Enabling hotkeys...
[09:27:48.5213616] > [Info]  Ready!
[09:29:20.4239011] > [Error] A task was canceled.
 -------------------- 
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (A task was canceled.))
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.TarkovDevAPI.Get(String query)
   at RatScanner.TarkovDevAPI.GetNeededItems(Int64 ttl)
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, Boolean firOnly, UserProgress progress)
   at RatScanner.ViewModel.MenuVM.get_TaskRemaining()
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(RenderTreeBuilder __builder5)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at System.Runtime.CompilerServices.A
```
</details>

**Comment by Blightbuster** [comment]
Fixed, thanks for reporting.
