### ISSUE TITLE
The system cannot find the path specified. (0x80070003)

### ISSUE THREAD

**Issue by PlayLikeMilk** [RatScanner/RatScanner#483]
**Error**
The system cannot find the path specified. (0x80070003)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebV
```
<details>
<summary>Log</summary>

```
[12:52:11.1738610] > [Debug] OnKeyUp:100 -> Pressed: Left
[12:52:11.1740346] > [Debug] NameScan:256 -> Name scanning at: (1659, 1068)
[12:52:11.4562353] > [Debug] NameScanScreen:306 -> Name scanning screen
[12:52:12.5176740] > [Debug] OnKeyUp:100 -> Pressed: Left
[12:52:12.5178548] > [Debug] NameScan:256 -> Name scanning at: (1679, 957)
[12:52:12.8013593] > [Debug] NameScanScreen:306 -> Name scanning screen
[12:52:13.9737690] > [Debug] OnKeyUp:100 -> Pressed: Left
[12:52:13.9739382] > [Debug] NameScan:256 -> Name scanning at: (1628, 1002)
[12:52:14.2355255] > [Debug] NameScanScreen:306 -> Name scanning screen
[12:52:14.4937086] > [Debug] OnKeyUp:100 -> Pressed: Left
[12:52:14.4938611] > [Debug] NameScan:256 -> Name scanning at: (1629, 1012)
[12:52:14.6217930] > [Debug] OnKeyUp:100 -> Pressed: Left
[12:52:14.6221393] > [Debug] NameScan:256 -> Name scanning at: (1629, 1012)
[12:52:16.1417303] > [Debug] OnKeyUp:100 -> Pressed: Left
[12:52:16.1418858] > [Debug] NameScan:256 -> Name scanning at: (776, 1065)
[12:52:16.4165173] > [Debug] NameScanScreen:306 -> Name scanning screen
[12:53:15.4698039] > [Debug] OnKeyUp:100 -> Pressed: Left
[12:53:15.4699882] > [Debug] NameScan:256 -> Name scanning at: (1757, 638)
[12:53:15.5855147] > [Warning] Config version (-1) is not supported!
[12:53:15.7439759] > [Debug] OnKeyUp:100 -> Pressed: Left
[12:53:15.7441879] > [Debug] NameScan:256 -> Name scanning at: (1757, 638)
[12:53:15.8062752] > [Error] The system cannot find the path specified. (0x80070003)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorUI.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoke
```
</details>

**Comment by Blightbuster** [comment]
https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#the-system-cannot-find-the-file-specified
