### ISSUE TITLE
Access to the path 'C:\Users\81907\Desktop\RatScanner\Log.txt' is denied.

### ISSUE THREAD

**Issue by sonetti-jp** [RatScanner/RatScanner#484]
**Error**
Access to the path 'C:\Users\81907\Desktop\RatScanner\Log.txt' is denied.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\81907\Desktop\RatScanner\Log.txt' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at RatScanner.Logger.Clear()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__12_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Re
```
<details>
<summary>Log</summary>

```
[17:16:59.1865149] > [Info]  ----- RatScanner 3.5.4 -----
[17:16:59.1865336] > [Info]  Starting RatScanner...
[17:16:59.1865343] > [Info]  Loading config...
[17:16:59.1887797] > [Info]  Screen Info: 1920x1080 at 100%
[17:16:59.1887926] > [Info]  Setting temporary default item...
[17:16:59.1903049] > [Info]  Initializing tarkov tracker database
[17:16:59.1905466] > [Info]  Initializing hotkey manager...
[17:16:59.1936063] > [Info]  UI Ready!
[17:17:00.1989906] > [Info]  Checking for updates...
[17:17:00.2011245] > [Info]  Loading resource "RSClientVersion"...
[17:17:00.9092444] > [Info]  Loading item data...
[17:17:03.8745674] > [Info]  Loading price data...
[17:17:04.5859367] > [Info]  Loading TarkovTracker data...
[17:17:04.5859539] > [Info]  Initializing RatEye...
[17:17:07.3937227] > [Info]  Setting up timer routines...
[17:17:07.3937533] > [Info]  Setting default item...
[17:17:07.3962988] > [Info]  Enabling hotkeys...
[17:17:07.3963248] > [Info]  Ready!
[17:17:41.0345127] > [Info]  Saving config...
[17:17:41.0414172] > [Info]  Config saved!
[17:20:36.8982794] > [Info]  Saving config...
[17:20:36.9031996] > [Info]  Config saved!
[17:22:07.4005146] > [Info]  Refreshing TarkovTracker DB...
[17:22:11.0964755] > [Info]  Saving config...
[17:22:11.1012960] > [Info]  Config saved!
[17:27:07.4120542] > [Info]  Refreshing TarkovTracker DB...
[17:32:07.4173817] > [Info]  Refreshing TarkovTracker DB...
[17:37:07.4257366] > [Info]  Refreshing TarkovTracker DB...
[17:42:07.4400391] > [Info]  Refreshing TarkovTracker DB...
[17:47:07.3972967] > [Info]  Refreshing Market DB...
[17:47:07.4400327] > [Info]  Refreshing TarkovTracker DB...
[17:52:07.4413169] > [Info]  Refreshing TarkovTracker DB...
[17:57:07.4571489] > [Info]  Refreshing TarkovTracker DB...
[18:02:07.4579769] > [Info]  Refreshing TarkovTracker DB...
[18:07:07.4692275] > [Info]  Refreshing TarkovTracker DB...
[18:12:07.4769046] > [Info]  Refreshing TarkovTracker DB...
[18:17:07.4869176] > [Info]  Refreshing TarkovTracker DB...
[18:17:08.9741760] > [Info]  Refreshing Market DB...
[18:22:07.4865545] > [Info]  Refreshing TarkovTracker DB...
[18:27:07.4890648] > [Info]  Refreshing TarkovTracker DB...
[18:32:07.4892507] > [Info]  Refreshing TarkovTracker DB...
[18:37:07.4896468] > [Info]  Refreshing TarkovTracker DB...
[18:42:07.4974172] > [Info]  Refreshing TarkovTracker DB...
[18:47:07.5079938] > [Info]  Refreshing TarkovTracker DB...
[18:47:10.3936817] > [Info]  Refreshing Market DB...
[18:52:07.5086041] > [Info]  Refreshing TarkovTracker DB...
[18:57:07.5154029] > [Info]  Refreshing TarkovTracker DB...
[19:02:07.5209022] > [Info]  Refreshing TarkovTracker DB...
[19:07:07.5266137] > [Info]  Refreshing TarkovTracker DB...
[19:12:07.5298152] > [Info]  Refreshing TarkovTracker DB...
[19:17:07.5314817] > [Info]  Refreshing TarkovTracker DB...
[19:17:11.9177913] > [Info]  Refreshing Market DB...
[19:22:07.5345783] > [Info]  Refreshing TarkovTracker DB...
[19:27:07.5457728] > [Info]  Refreshing TarkovTr
```
</details>

**Comment by Blightbuster** [comment]
Try starting as admin and makle sure your desktop is not a onedrive folder.
