### ISSUE TITLE
Specified cast is not valid.

### ISSUE THREAD

**Issue by thsqorms1** [RatScanner/RatScanner#486]
**Error**
Specified cast is not valid.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Settings3.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3
```
<details>
<summary>Log</summary>

```
[08:29:46.8300990] > [Error] Specified cast is not valid.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Settings3.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.set_AreBrowserAcceleratorKeysEnabled(Boolean value)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[08:29:58.3004351] > [Error] Specified cast is not valid.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedExce
```
</details>

**Comment by Blightbuster** [comment]
You probably have a broken WebView2 installation.

In windows, try to uninstall WebView2. If you cant for some reason do the steps below.

Search in windows for regedit and delete these two entries (or make sure they dont exist):
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
HKEY_CURRENT_USER\Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}

After you've uninstalled it (or did the regedit stuff), you should be able to install WebView2 from the link below.
https://go.microsoft.com/fwlink/p/?LinkId=2124703
