### ISSUE TITLE
Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by Sintonx** [RatScanner/RatScanner#487]
**Error**
Exception has been thrown by the target of an invocation.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at InteropDotNet.LibraryLoader.InternalLoadLibrary(String baseDirectory, String platformName, String fileName)
   at InteropDotNet.LibraryLoader.CheckExecutingAssemblyDomain(String fileName, String platformName)
   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)
   at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
 
```
<details>
<summary>Log</summary>

```
[20:58:23.4775258] > [Info]  Saving config...
[20:58:23.5994638] > [Info]  Config saved!
[20:58:28.2588133] > [Error] Exception has been thrown by the target of an invocation.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at InteropDotNet.LibraryLoader.InternalLoadLibrary(String baseDirectory, String platformName, String fileName)
   at InteropDotNet.LibraryLoader.CheckExecutingAssemblyDomain(String fileName, String platformName)
   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)
   at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at InteropDotNet.InteropRuntimeImplementer.CreateInstance[T]()
   at Tesseract.Interop.LeptonicaApi.Initialize()
   at Tesseract.Interop.LeptonicaApi.get_Native()
   at Tesseract.Pix.Create(Int32 width, Int32 height, Int32 depth)
   at Tesseract.BitmapToPixConverter.Convert(Bitmap img)
   at Tesseract.PixConverter.ToPix(Bitmap img)
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatScanner.Scan.ItemNameScan..ctor(Inspection inspection, Vector2 toolTipPosition, Int32 duration)
   at RatScanner.RatScannerMain.NameScanScreen(Object _)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__10_0()
   at RatScanner.HotkeyManager.Wrap(Action action)

```
</details>

**Comment by Blightbuster** [comment]
Package throwing the exception is no longer in use hence im gonna close the issue.
