### ISSUE TITLE
Error on scanning

### ISSUE THREAD

**Issue by david-klm** [RatScanner/RatScanner#490]
**Error**
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
```
System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1682_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMeth
```
<details>
<summary>Log</summary>

```
[16:34:34.8859457] > [Info]  ----- RatScanner 3.5.4 -----
[16:34:34.8861697] > [Info]  Starting RatScanner...
[16:34:34.8861728] > [Info]  Loading config...
[16:34:34.8897368] > [Info]  Screen Info: 2560x1440 at 100%
[16:34:34.8897493] > [Info]  Setting temporary default item...
[16:34:34.8912568] > [Info]  Initializing tarkov tracker database
[16:34:34.8914871] > [Info]  Initializing hotkey manager...
[16:34:34.8945124] > [Info]  UI Ready!
[16:34:35.8964965] > [Info]  Checking for updates...
[16:34:35.8986187] > [Info]  Loading resource "RSClientVersion"...
[16:34:36.3266787] > [Info]  Loading item data...
[16:34:39.3407945] > [Info]  Loading price data...
[16:34:39.7943767] > [Info]  Loading TarkovTracker data...
[16:34:39.7943898] > [Info]  Initializing RatEye...
[16:34:43.0025968] > [Info]  Setting up timer routines...
[16:34:43.0026201] > [Info]  Setting default item...
[16:34:43.0049057] > [Info]  Enabling hotkeys...
[16:34:43.0049234] > [Info]  Ready!
[16:35:00.5413409] > [Error] One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 -------------------- 
 System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1682_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at OpenCvSharp.Mat.MatchTemplate(InputArray templ, TemplateMatchModes method, InputAr
```
</details>

**Comment by Infinitay** [comment]
I've had this happen numerous times as well ever since updating to the latest version. The image below is my scanning options, with using CTRL + Left Click to scan.
![image](https://user-images.githubusercontent.com/6964154/218367817-b426c5a0-6698-40e7-9a77-3a14fccd8005.png)

I feel like the crash happens most of the time when I CTRL + Left Click to scan but also alt-tab at the same time. I say this because IIRC that is what I was doing while scanning barter items in my stash and alt-tabbing once I initiate the scan to search for the item on tarkov.dev. I'll try and reproduce if I can remember tomorrow.
