### ISSUE TITLE
Access to the path 'C:\Games\rat\Log.txt' is denied.

### ISSUE THREAD

**Issue by BABUL14ka** [RatScanner/RatScanner#494]
**Error**
Access to the path 'C:\Games\rat\Log.txt' is denied.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Games\rat\Log.txt' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at RatScanner.Logger.Clear()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__12_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite
```
<details>
<summary>Log</summary>

```
[18:58:48.6694772] > [Info]  ----- RatScanner 3.5.4 -----
[18:58:48.6694892] > [Info]  Starting RatScanner...
[18:58:48.6694899] > [Info]  Loading config...
[18:58:48.6709752] > [Info]  Screen Info: 1920x1080 at 100%
[18:58:48.6709831] > [Info]  Setting temporary default item...
[18:58:48.6719817] > [Info]  Initializing tarkov tracker database
[18:58:48.6720848] > [Info]  Initializing hotkey manager...
[18:58:48.6741884] > [Info]  UI Ready!
[18:58:49.6784401] > [Info]  Checking for updates...
[18:58:49.6799542] > [Info]  Loading resource "RSClientVersion"...
[18:58:50.1248637] > [Info]  Loading item data...
[18:58:53.0446464] > [Info]  Loading price data...
[18:58:53.5340991] > [Info]  Loading TarkovTracker data...
[18:58:53.5341143] > [Info]  Initializing RatEye...
[18:58:56.2870798] > [Info]  Setting up timer routines...
[18:58:56.2871108] > [Info]  Setting default item...
[18:58:56.2925739] > [Info]  Enabling hotkeys...
[18:58:56.2926084] > [Info]  Ready!
[18:59:27.5689764] > [Info]  Saving config...
[18:59:27.5825077] > [Info]  Config saved!
[18:59:41.1873981] > [Info]  Saving config...
[18:59:41.2069586] > [Info]  Config saved!
[19:00:14.3244719] > [Info]  Saving config...
[19:00:14.3367458] > [Info]  Config saved!
[19:00:33.5040887] > [Info]  Saving config...
[19:00:33.5202651] > [Info]  Config saved!
[19:00:46.1833877] > [Info]  Saving config...
[19:00:46.1980520] > [Info]  Config saved!

```
</details>

**Comment by Blightbuster** [comment]
Hey, please try starting rat scanner as admin or move the rat scanner folder to a different location which isnt protected.
