### ISSUE TITLE
The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by e-slave** [RatScanner/RatScanner#497]
**Error**
The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
```
System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.core_Mat_new2(Int32 rows, Int32 cols, Int32 type, IntPtr& returnValue)
   at OpenCvSharp.Mat..ctor(Int32 rows, Int32 cols, MatType type)
   at OpenCvSharp.Extensions.BitmapConverter.ToMat(Bitmap src)
   at RatEye.Extensions.Rescale(Bitmap image, Single scale)
   at RatEye.Processing.Inspection.GetScaledMarker()
   at RatEye.Processing.Inspection.SearchMarker()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_
```
<details>
<summary>Log</summary>

```
[01:26:02.2291306] > [Info]  ----- RatScanner 3.5.4 -----
[01:26:02.2291586] > [Info]  Starting RatScanner...
[01:26:02.2291704] > [Info]  Loading config...
[01:26:02.2341667] > [Info]  Screen Info: 1920x1080 at 100%
[01:26:02.2341945] > [Info]  Setting temporary default item...
[01:26:02.2370974] > [Info]  Initializing tarkov tracker database
[01:26:02.2374745] > [Info]  Initializing hotkey manager...
[01:26:02.2428590] > [Info]  UI Ready!
[01:26:03.2461896] > [Info]  Checking for updates...
[01:26:03.2493802] > [Info]  Loading resource "RSClientVersion"...
[01:26:04.9864539] > [Info]  Loading item data...
[01:26:15.3244523] > [Info]  Loading price data...
[01:26:16.9233115] > [Info]  Loading TarkovTracker data...
[01:26:16.9233430] > [Info]  Initializing RatEye...
[01:26:17.4728538] > [Info]  Setting up timer routines...
[01:26:17.4728876] > [Info]  Setting default item...
[01:26:17.4781284] > [Info]  Enabling hotkeys...
[01:26:17.4781683] > [Info]  Ready!
[01:26:25.5210952] > [Error] The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 -------------------- 
 System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.core_Mat_new2(Int32 rows, Int32 cols, Int32 type, IntPtr& returnValue)
   at OpenCvSharp.Mat..ctor(Int32 rows, Int32 cols, MatType type)
   at OpenCvSharp.Extensions.BitmapConverter.ToMat(Bitmap src)
   at RatEye.Extensions.Rescale(Bitmap image, Single scale)
   at RatEye.Processing.Inspection.GetScaledMarker()
   at RatEye.Processing.Inspection.SearchMarker()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_MarkerConfidence()
   at RatEye.Processing.Inspection.get_ContainsMarker()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__10_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[01:28:27.0684085] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Did you start rat scanner from within the zip archive? You need to extract the folder first.

**Comment by e-slave** [comment]
:) extracted but same it's about game mode settings disabled for now. 0 error atm.
