### ISSUE TITLE
Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.

### ISSUE THREAD

**Issue by vladyslav-yeremenko** [RatScanner/RatScanner#499]
**Error**
Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
```
Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)
   at RatEye.Processing.Inspection.GetTesseractEngine()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__1
```
<details>
<summary>Log</summary>

```
[12:59:16.1247664] > [Info]  ----- RatScanner 3.5.4 -----
[12:59:16.1247871] > [Info]  Starting RatScanner...
[12:59:16.1247880] > [Info]  Loading config...
[12:59:16.1250667] > [Warning] Config version (-1) is not supported!
[12:59:16.1320374] > [Info]  Screen Info: 2560x1439 at 100%
[12:59:16.1320504] > [Info]  Setting temporary default item...
[12:59:16.1340368] > [Info]  Initializing tarkov tracker database
[12:59:16.1342783] > [Info]  Initializing hotkey manager...
[12:59:16.1386242] > [Info]  UI Ready!
[12:59:17.1468586] > [Info]  Checking for updates...
[12:59:17.1500170] > [Info]  Loading resource "RSClientVersion"...
[12:59:17.6474031] > [Info]  Loading item data...
[12:59:23.0685591] > [Info]  Loading price data...
[12:59:23.6301643] > [Info]  Loading TarkovTracker data...
[12:59:23.6301853] > [Info]  Initializing RatEye...
[12:59:24.1870928] > [Info]  Setting up timer routines...
[12:59:24.1871262] > [Info]  Setting default item...
[12:59:24.1914226] > [Info]  Enabling hotkeys...
[12:59:24.1914580] > [Info]  Ready!
[12:59:29.4699906] > [Error] Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
 -------------------- 
 Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)
   at RatEye.Processing.Inspection.GetTesseractEngine()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__10_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[12:59:37.3164323] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by DysektAI** [comment]
### Duplicate cleanup

Additional open reports of `TesseractException: Failed to initialise tesseract engine` during name-scan OCR were closed as duplicates of this issue (earliest open report):

| Closed as duplicate |
| --- |
| #620 |
| #738 |

**Comment by DysektAI** [comment]
### v4.x.x Beta available

A `v4.x.x Beta` is currently being tested which fixes and addresses this and many other issues.

- It's a Work In Progress and still likely has other issues that will be addressed as more updates are made, so expect changes.
- It will be migrated over to the RatScanner/RatScanner repo once fully stable. Until then, this is the best option to avoid pushing unfinished/unstable work to everyone.
- **Read the release details — being a beta, it does come with some risks that can't be accounted for.**

**You can find the beta here: https://github.com/tarkovtracker-org/RatScanner/releases/tag/v4.0.0-beta**
*It should auto-update when more updates are released.

---
_This comment was posted with AI assistance using GLM-5.2 High and may not be 100% accurate. Please verify the information before relying on it._
