### ISSUE TITLE
Could not find a part of the path 'C:\Users\nelson\AppData\Local\Temp\Rar$EXa13368.37467\Data\items.json'.

### ISSUE THREAD

**Issue by NelsonGranados** [RatScanner/RatScanner#503]
**Error**
Could not find a part of the path 'C:\Users\nelson\AppData\Local\Temp\Rar$EXa13368.37467\Data\items.json'.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\nelson\AppData\Local\Temp\Rar$EXa13368.37467\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at RatStash.Database
```
<details>
<summary>Log</summary>

```
[08:50:11.0818345] > [Info]  Checking for updates...
[08:50:11.0839798] > [Info]  Loading resource "RSClientVersion"...
[08:50:11.7017444] > [Info]  Loading item data...
[08:50:11.7115040] > [Error] Could not find a part of the path 'C:\Users\nelson\AppData\Local\Temp\Rar$EXa13368.37467\Data\items.json'.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\nelson\AppData\Local\Temp\Rar$EXa13368.37467\Data\items.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at RatStash.Database.FromFile(String itemPath, Boolean cleanStrings, String localePath)
   at RatScanner.RatScannerMain.GetRatStashDatabase()
   at RatScanner.RatScannerMain.<.ctor>b__18_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[08:50:18.1028927] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
You need to extract the zip first before running ratscanner
