### ISSUE TITLE
Specified cast is not valid.

### ISSUE THREAD

**Issue by Esquired25** [RatScanner/RatScanner#506]
**Error**
Specified cast is not valid.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Settings3.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3
```
<details>
<summary>Log</summary>

```
[17:37:12.6294375] > [Warning] Config version (-1) is not supported!
[17:37:13.5712154] > [Error] Specified cast is not valid.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Settings3.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.get__nativeICoreWebView2Settings3()
   at Microsoft.Web.WebView2.Core.CoreWebView2Settings.set_AreBrowserAcceleratorKeysEnabled(Boolean value)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[17:37:30.6016813] > [Error] Specified cast is not valid.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been th
```
</details>

Reinstalling WebView2 doesn't help to solve that

**Comment by Esquired25** [comment]
Somehow this problem disappeared without any actions. Very strange
