### ISSUE TITLE
Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.

### ISSUE THREAD

**Issue by Aiur4k** [RatScanner/RatScanner#508]
**Error**
Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
```
System.Windows.Markup.XamlParseException: Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo,
```
<details>
<summary>Log</summary>

```
[13:55:01.1010737] > [Error] Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
 -------------------- 
 System.Windows.Markup.XamlParseException: Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RatScanner.PageSwitcher.InitializeComponent()
   at RatScanner.PageSwitcher..ctor()
[13:55:03.7958224] > [Info]  Loading resource "RSGithubLink"...
[13:55:23.8775639] > [Error] Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
 -------------------- 
 System.Windows.Markup.XamlParseException: Добавление значения в коллекцию типа "System.Windows.Controls.UIElementCollection" вызвало исключение.
 ---> System.DllNotFoundException: Dll was not found.
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.
```
</details>

**Comment by Blightbuster** [comment]
https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#rat-scanner-is-not-starting
