### ISSUE TITLE
ISSUE: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.

### ISSUE THREAD

**Issue by kruppstahl1337** [RatScanner/RatScanner#513]
Hello!!! :)

Here is my error, anyone can tell me what is wrong?

**Error**
Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at RatScanner.FetchModels.TarkovDev.ObjectiveConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerialize
```
<details>
<summary>Log</summary>

```
[14:41:33.7588773] > [Info]  ----- RatScanner 3.5.4 -----
[14:41:33.7590656] > [Info]  Starting RatScanner...
[14:41:33.7590674] > [Info]  Loading config...
[14:41:33.7606439] > [Info]  Screen Info: 1920x1080 at 100%
[14:41:33.7606503] > [Info]  Setting temporary default item...
[14:41:33.7615465] > [Info]  Initializing tarkov tracker database
[14:41:33.7616433] > [Info]  Initializing hotkey manager...
[14:41:33.7634492] > [Info]  UI Ready!
[14:41:34.7745590] > [Info]  Checking for updates...
[14:41:34.7759263] > [Info]  Loading resource "RSClientVersion"...
[14:41:35.1000493] > [Error] Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at RatScanner.FetchModels.TarkovDev.ObjectiveConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonPropert
```
</details>

**Comment by kruppstahl1337** [comment]
Solved itself by running Tarkov and Starting... :D

**Comment by kruppstahl1337** [comment]
D
