### ISSUE TITLE
Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.

### ISSUE THREAD

**Issue by boulayb** [RatScanner/RatScanner#515]
**Error**
Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at RatScanner.FetchModels.TarkovDev.ObjectiveConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerialize
```
<details>
<summary>Log</summary>

```
[15:23:19.4639752] > [Info]  ----- RatScanner 3.5.4 -----
[15:23:19.4640894] > [Info]  Starting RatScanner...
[15:23:19.4640906] > [Info]  Loading config...
[15:23:19.4649872] > [Info]  Screen Info: 3840x2160 at 150%
[15:23:19.4649921] > [Info]  Setting temporary default item...
[15:23:19.4654528] > [Info]  Initializing tarkov tracker database
[15:23:19.4655046] > [Info]  Initializing hotkey manager...
[15:23:19.4667160] > [Info]  UI Ready!
[15:23:20.3673468] > [Error] Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'data.tasks[315].objectives[1]', line 1, position 437663.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at RatScanner.FetchModels.TarkovDev.ObjectiveConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft
```
</details>

**Comment by BelvedereHenrique** [comment]
Try it today, it should work.

**Comment by boulayb** [comment]
It does
