### ISSUE TITLE
An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by Ryuichiro** [RatScanner/RatScanner#516]
Based on the log I assume it's TarkovTracker that closes the connection, but RatScanner should probably handle this better than just closing.

**Error**
An existing connection was forcibly closed by the remote host.
```
System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodB
```
<details>
<summary>Log</summary>

```
[09:41:29.1592958] > [Info]  ----- RatScanner 3.5.4 -----
[09:41:29.1594884] > [Info]  Starting RatScanner...
[09:41:29.1594904] > [Info]  Loading config...
[09:41:29.1610081] > [Info]  Screen Info: 2560x1440 at 100%
[09:41:29.1610145] > [Info]  Setting temporary default item...
[09:41:29.1618111] > [Info]  Initializing tarkov tracker database
[09:41:29.1619233] > [Info]  Initializing hotkey manager...
[09:41:29.1643411] > [Info]  UI Ready!
[09:41:30.1685632] > [Info]  Checking for updates...
[09:41:30.1702235] > [Info]  Loading resource "RSClientVersion"...
[09:41:30.6275096] > [Info]  Loading item data...
[09:41:33.1721377] > [Info]  Loading price data...
[09:41:33.8278862] > [Info]  Loading TarkovTracker data...
[09:41:33.8279020] > [Info]  Loading TarkovTracker...
[09:41:33.8887412] > [Error] An existing connection was forcibly closed by the remote host.
 -------------------- 
 System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationTo
```
</details>

**Comment by DysektAI** [comment]
### Duplicate cleanup

#707 was closed as a duplicate of this issue (Chinese-localized title for the same remote host forcibly closed / SSL connection reset stack).

**Comment by DysektAI** [comment]
### v4.x.x Beta available

A `v4.x.x Beta` is currently being tested which fixes and addresses this and many other issues.

- It's a Work In Progress and still likely has other issues that will be addressed as more updates are made, so expect changes.
- It will be migrated over to the RatScanner/RatScanner repo once fully stable. Until then, this is the best option to avoid pushing unfinished/unstable work to everyone.
- **Read the release details — being a beta, it does come with some risks that can't be accounted for.**

**You can find the beta here: https://github.com/tarkovtracker-org/RatScanner/releases/tag/v4.0.0-beta**
*It should auto-update when more updates are released.

---
_This comment was posted with AI assistance using GLM-5.2 High and may not be 100% accurate. Please verify the information before relying on it._
