### ISSUE TITLE
..................0No such host is known.

### ISSUE THREAD

**Issue by marksterxxx** [RatScanner/RatScanner#519]
**Error**
No such host is known.
```
System.AggregateException: One or more errors occurred. (No such host is known. (tarkovtracker.io:443))
 ---> System.Net.Http.HttpRequestException: No such host is known. (tarkovtracker.io:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHos
```
<details>
<summary>Log</summary>

```
[22:06:49.3135029] > [Info]  ----- RatScanner 3.5.4 -----
[22:06:49.3138006] > [Info]  Starting RatScanner...
[22:06:49.3138021] > [Info]  Loading config...
[22:06:49.3161624] > [Info]  Screen Info: 1920x1080 at 100%
[22:06:49.3161781] > [Info]  Setting temporary default item...
[22:06:49.3176181] > [Info]  Initializing tarkov tracker database
[22:06:49.3177932] > [Info]  Initializing hotkey manager...
[22:06:49.3199904] > [Info]  UI Ready!
[22:06:50.3231872] > [Info]  Checking for updates...
[22:06:50.3249628] > [Info]  Loading resource "RSClientVersion"...
[22:06:51.4586391] > [Info]  Loading item data...
[22:06:54.2156366] > [Info]  Loading price data...
[22:06:55.3895796] > [Info]  Loading TarkovTracker data...
[22:06:55.3895953] > [Info]  Loading TarkovTracker...
[22:06:56.2239944] > [Info]  Initializing RatEye...
[22:06:58.6197252] > [Info]  Setting up timer routines...
[22:06:58.6197526] > [Info]  Setting default item...
[22:06:58.6228666] > [Info]  Enabling hotkeys...
[22:06:58.6228947] > [Info]  Ready!
[22:11:58.6335341] > [Info]  Refreshing TarkovTracker DB...
[22:16:59.1213714] > [Info]  Refreshing TarkovTracker DB...
[22:21:59.7206875] > [Info]  Refreshing TarkovTracker DB...
[22:27:00.2827635] > [Info]  Refreshing TarkovTracker DB...
[22:32:00.7233795] > [Info]  Refreshing TarkovTracker DB...
[22:36:58.6250686] > [Info]  Refreshing Market DB...
[22:37:01.2333793] > [Info]  Refreshing TarkovTracker DB...
[22:42:01.8022243] > [Info]  Refreshing TarkovTracker DB...
[22:47:02.7537569] > [Info]  Refreshing TarkovTracker DB...
[22:52:03.2291715] > [Info]  Refreshing TarkovTracker DB...
[22:57:03.7352224] > [Info]  Refreshing TarkovTracker DB...
[22:59:06.3430413] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3431959] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3433263] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3434256] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3435053] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3435831] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3441127] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3441976] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3442723] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3443265] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3443769] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3444259] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3444755] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3445269] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3445920] > [Warning] Could not find item with uid: 5cdeb229d7f00c000e7ce174
[22:59:06.3446616] > [Warning]
```
</details>

**Comment by Blightbuster** [comment]
Is this a one of error you got? The only possible explanation I can come up with would be you having a firewall blocking internet access for rat scanner or you loosing internet connection for some period.

**Comment by DysektAI** [comment]
### Duplicate cleanup

Additional open reports of DNS resolution failure for TarkovTracker hosts (`No such host is known` / localized `Der angegebene Host ist unbekannt`) were closed as duplicates of this issue:

| Closed as duplicate | Notes |
| --- | --- |
| #691 | tarkovtracker.io |
| #708 | German localization, same error |
| #753 | tarkovtracker.org |

**Comment by DysektAI** [comment]
### v4.x.x Beta available

A `v4.x.x Beta` is currently being tested which fixes and addresses this and many other issues.

- It's a Work In Progress and still likely has other issues that will be addressed as more updates are made, so expect changes.
- It will be migrated over to the RatScanner/RatScanner repo once fully stable. Until then, this is the best option to avoid pushing unfinished/unstable work to everyone.
- **Read the release details — being a beta, it does come with some risks that can't be accounted for.**

**You can find the beta here: https://github.com/tarkovtracker-org/RatScanner/releases/tag/v4.0.0-beta**
*It should auto-update when more updates are released.

---
_This comment was posted with AI assistance using GLM-5.2 High and may not be 100% accurate. Please verify the information before relying on it._
