### ISSUE TITLE
Rectangle '{X=813,Y=24,Width=0,Height=21}' cannot have a width or height equal to 0.

### ISSUE THREAD

**Issue by godxxy1229** [RatScanner/RatScanner#520]
**Error**
Rectangle '{X=813,Y=24,Width=0,Height=21}' cannot have a width or height equal to 0.
```
System.ArgumentException: Rectangle '{X=813,Y=24,Width=0,Height=21}' cannot have a width or height equal to 0.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__10_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[09:02:49.6571449] > [Info]  ----- RatScanner 3.5.4 -----
[09:02:49.6574978] > [Info]  Starting RatScanner...
[09:02:49.6575005] > [Info]  Loading config...
[09:02:49.6627068] > [Info]  Screen Info: 2544x1353 at 100%
[09:02:49.6627166] > [Info]  Setting temporary default item...
[09:02:49.6648169] > [Info]  Initializing tarkov tracker database
[09:02:49.6649288] > [Info]  Initializing hotkey manager...
[09:02:49.6672787] > [Info]  UI Ready!
[09:02:50.6762111] > [Info]  Checking for updates...
[09:02:50.6777102] > [Info]  Loading resource "RSClientVersion"...
[09:02:51.4205670] > [Info]  Loading item data...
[09:02:54.4803379] > [Info]  Loading price data...
[09:02:55.3626756] > [Info]  Loading TarkovTracker data...
[09:02:55.3626877] > [Info]  Initializing RatEye...
[09:02:58.2779805] > [Info]  Setting up timer routines...
[09:02:58.2780080] > [Info]  Setting default item...
[09:02:58.2800923] > [Info]  Enabling hotkeys...
[09:02:58.2801064] > [Info]  Ready!
[09:07:58.2845818] > [Info]  Refreshing TarkovTracker DB...
[09:12:58.2854819] > [Info]  Refreshing TarkovTracker DB...
[09:17:58.2919964] > [Info]  Refreshing TarkovTracker DB...
[09:22:58.2997205] > [Info]  Refreshing TarkovTracker DB...
[09:27:58.3127888] > [Info]  Refreshing TarkovTracker DB...
[09:32:58.2865375] > [Info]  Refreshing Market DB...
[09:32:58.3170650] > [Info]  Refreshing TarkovTracker DB...
[09:37:58.3197717] > [Info]  Refreshing TarkovTracker DB...
[09:42:58.3321174] > [Info]  Refreshing TarkovTracker DB...
[09:47:58.3359633] > [Info]  Refreshing TarkovTracker DB...
[09:52:58.3500946] > [Info]  Refreshing TarkovTracker DB...
[09:57:58.3605433] > [Info]  Refreshing TarkovTracker DB...
[10:02:58.3645352] > [Info]  Refreshing TarkovTracker DB...
[10:02:59.6320595] > [Info]  Refreshing Market DB...
[10:26:51.2778904] > [Info]  Refreshing TarkovTracker DB...
[10:31:51.2811668] > [Info]  Refreshing TarkovTracker DB...
[10:36:51.2945468] > [Info]  Refreshing TarkovTracker DB...
[10:41:51.3015635] > [Info]  Refreshing TarkovTracker DB...
[10:46:51.3131543] > [Info]  Refreshing TarkovTracker DB...
[10:51:51.3201169] > [Info]  Refreshing TarkovTracker DB...
[10:51:53.8810176] > [Info]  Refreshing Market DB...
[10:56:51.3261434] > [Info]  Refreshing TarkovTracker DB...
[11:01:51.3409185] > [Info]  Refreshing TarkovTracker DB...
[11:06:51.3538194] > [Info]  Refreshing TarkovTracker DB...
[11:11:51.3541502] > [Info]  Refreshing TarkovTracker DB...
[11:16:51.3663857] > [Info]  Refreshing TarkovTracker DB...
[11:21:51.3717308] > [Info]  Refreshing TarkovTracker DB...
[11:21:55.2841289] > [Info]  Refreshing Market DB...
[11:26:51.3720124] > [Info]  Refreshing TarkovTracker DB...
[11:31:51.3753987] > [Info]  Refreshing TarkovTracker DB...
[11:36:51.3832064] > [Info]  Refreshing TarkovTracker DB...
[11:41:51.3979335] > [Info]  Refreshing TarkovTracker DB...
[11:46:51.4122905] > [Info]  Refreshing TarkovTracker DB...
[11:51:51.4132545] > [Info]  Refreshing TarkovTracker DB...
[11:51:56.62249
```
</details>

**Comment by Blightbuster** [comment]
Tracked in #521
