### ISSUE TITLE
Value does not fall within the expected range.

### ISSUE THREAD

**Issue by Michou-G** [RatScanner/RatScanner#524]
**Error**
Value does not fall within the expected range.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller2.set_DefaultBackgroundColor(COREWEBVIEW2_COLOR backgroundColor)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_DefaultBackgroundColor(Color value)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebVie
```
<details>
<summary>Log</summary>

```
[19:03:20.0773025] > [Warning] Config version (-1) is not supported!
[19:03:20.1365810] > [Warning] Unable to query Escape From Tarkov graphic settings.
[19:03:20.1525937] > System.ArgumentException: Accessed JArray values with invalid key value: "0". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at RatScanner.RatConfig.GetTarkovScreenConfig()
[19:03:20.1705247] > [Info]  Detected 3440x1440 Resolution at 1 Scale.

You can adjust this inside the settings.
[19:03:21.7969992] > [Error] Value does not fall within the expected range.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller2.set_DefaultBackgroundColor(COREWEBVIEW2_COLOR backgroundColor)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_DefaultBackgroundColor(Color value)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass12_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[19:03:25.1294535] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Do you have some software installed, which messes with other applications layouts?

**Comment by Michou-G** [comment]
Yeah, I got "Mica For Everyone" installed, I already tried to disable it for ratscanner and I've also tried to disable it completely but the result was the same.

**Comment by DysektAI** [comment]
Closing as **not planned** (environment/layout software).

Stack is WebView2 `DefaultBackgroundColor`/controller init failing. Reporter confirmed theming software (`Mica For Everyone`). No further reproduction without layout/theming tools in ~3 years. Reopen if it still happens on a clean Windows install with stock WebView2 and the latest RatScanner release.
