### ISSUE TITLE
Loading of resource "RSClientVersion" failed

### ISSUE THREAD

**Issue by Tsukengnek** [RatScanner/RatScanner#527]
When I launch RatScannet is says this:

**Loading of resource "RSClientVersion" failed.

The FAQ will probably help with that.
Do you want to open it now?**

_(The FAQ didn't help me)_

![image](https://github.com/RatScanner/RatScanner/assets/21665503/8a4f5dac-3a4c-449a-8612-d292139c07c9)

Clicking the "yes" button does nothing. RatScanner remains interactive for some time, you can go into the settings, for example, change them, but it doesn’t do its job, it doesn’t scan items and doesn’t show their price. And after another 20 seconds the entire computer freezes for a second and RatScanner closes.
After clicking on the “no” button, a proposal appears to create an issue on GitHub, but when you click on “yes” everything is the same as above. The "no" button just closes everything immediatly.

![image](https://github.com/RatScanner/RatScanner/assets/21665503/083a0f98-6d08-4c62-a801-2017b95b81d9)

I tried restarting the computer, reinstalling the program, run it as administrator. Nothing changed.

While I was creating this GitHub request, I tried to run the application about 40 times. And for some reason it started once normally. Last week it worked perfectly. 

```
[14:19:43.3180677] > [Info]  ----- RatScanner 3.6.2 -----
[14:19:43.3182785] > [Info]  Screen Info: 1920x1080 at 100%
[14:19:43.3182807] > [Info]  Setting temporary default item...
[14:19:43.3193037] > [Info]  Initializing tarkov tracker database
[14:19:43.3194207] > [Info]  Initializing hotkey manager...
[14:19:43.3229187] > [Info]  UI Ready!
[14:19:44.3366189] > [Info]  Checking for updates...
[14:19:44.3381269] > [Info]  Loading resource "RSClientVersion"...
[14:20:05.5208948] > [Error] Loading of resource "RSClientVersion" failed.
 -------------------- 
 System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера..
 ---> System.Net.Sockets.SocketException (10060): Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetString(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
[14:20:13.3159725] > [Info]  Loading resource "RSFAQLink"...

```
[Log.txt](https://github.com/RatScanner/RatScanner/files/12750547/Log.txt)

**Comment by Tsukengnek** [comment]
I just ran and closed it 10 times in a row and it launched perfectly every time.
Works in the game too, scans as it should.
I did nothing special, so I have no idea why is it working now.

**Comment by Blightbuster** [comment]
Most likely an issue with your firewall / VPN / ISP.
Thanks for updating me on the fact that it got resolved by itself ❤️
