### ISSUE TITLE
Out of memory.

### ISSUE THREAD

**Issue by patlinGER** [RatScanner/RatScanner#528]
**Error**
Out of memory.
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[06:13:42.6775777] > [Info]  ----- RatScanner 3.6.2 -----
[06:13:42.6777091] > [Info]  Screen Info: 3840x1600 at 100%
[06:13:42.6777106] > [Info]  Setting temporary default item...
[06:13:42.6781575] > [Info]  Initializing tarkov tracker database
[06:13:42.6782135] > [Info]  Initializing hotkey manager...
[06:13:42.6802888] > [Info]  UI Ready!
[06:13:43.6937923] > [Info]  Checking for updates...
[06:13:43.6950200] > [Info]  Loading resource "RSClientVersion"...
[06:13:44.0498053] > [Info]  Loading item data...
[06:13:44.9163496] > [Info]  Loading price data...
[06:13:45.3676329] > [Info]  Loading TarkovTracker data...
[06:13:45.3676440] > [Info]  Loading TarkovTracker...
[06:13:46.0766621] > [Info]  Initializing RatEye...
[06:13:46.3434874] > [Info]  Setting up timer routines...
[06:13:46.3435052] > [Info]  Setting default item...
[06:13:46.3446551] > [Info]  Enabling hotkeys...
[06:13:46.3446855] > [Info]  Ready!
[06:18:46.3541870] > [Info]  Refreshing TarkovTracker DB...
[06:23:47.0038987] > [Info]  Refreshing TarkovTracker DB...
[06:28:47.7456798] > [Info]  Refreshing TarkovTracker DB...
[06:33:48.3475636] > [Info]  Refreshing TarkovTracker DB...
[06:38:48.8681293] > [Info]  Refreshing TarkovTracker DB...
[06:43:46.3552908] > [Info]  Refreshing Market DB...
[06:43:49.3996025] > [Info]  Refreshing TarkovTracker DB...
[06:48:49.9863358] > [Info]  Refreshing TarkovTracker DB...
[06:53:50.6576204] > [Info]  Refreshing TarkovTracker DB...
[06:58:51.1747383] > [Info]  Refreshing TarkovTracker DB...
[07:03:51.6458429] > [Info]  Refreshing TarkovTracker DB...
[07:08:52.1500320] > [Info]  Refreshing TarkovTracker DB...
[07:13:47.0079309] > [Info]  Refreshing Market DB...
[07:13:52.8208111] > [Info]  Refreshing TarkovTracker DB...
[07:18:53.3490799] > [Info]  Refreshing TarkovTracker DB...
[07:23:53.9670550] > [Info]  Refreshing TarkovTracker DB...
[07:28:55.2546172] > [Info]  Refreshing TarkovTracker DB...
[07:33:55.7548445] > [Info]  Refreshing TarkovTracker DB...
[07:38:56.2953172] > [Info]  Refreshing TarkovTracker DB...
[07:43:47.7174159] > [Info]  Refreshing Market DB...
[07:43:56.8043309] > [Info]  Refreshing TarkovTracker DB...
[07:48:57.4132820] > [Info]  Refreshing TarkovTracker DB...
[07:53:57.9218431] > [Info]  Refreshing TarkovTracker DB...
[07:58:58.6175233] > [Info]  Refreshing TarkovTracker DB...
[08:03:59.1285465] > [Info]  Refreshing TarkovTracker DB...
[08:08:59.9081994] > [Info]  Refreshing TarkovTracker DB...
[08:13:48.3984074] > [Info]  Refreshing Market DB...
[08:14:00.9855709] > [Info]  Refreshing TarkovTracker DB...
[08:19:01.5108942] > [Info]  Refreshing TarkovTracker DB...
[08:24:01.9691049] > [Info]  Refreshing TarkovTracker DB...
[08:29:02.4795718] > [Info]  Refreshing TarkovTracker DB...
[08:34:03.0391353] > [Info]  Refreshing TarkovTracker DB...
[08:39:03.5975269] > [Info]  Refreshing TarkovTracker DB...
[08:43:49.1034907] > [Info]  Refreshing Market DB...
[08:44:04.1569862] > [Info]  Refreshing TarkovTracker DB...
[08:49:
```
</details>

**Comment by Blightbuster** [comment]
How much RAM does your PC have?

**Comment by patlinGER** [comment]
Hi Moritz

64,0 GB (63,8 GB usable)

Best regards
Patrick

**Comment by Blightbuster** [comment]
Do you have the debug mode enabled? It may have memory leaks.

**Comment by DysektAI** [comment]
### Duplicate cleanup

Several open auto-reported OOM issues were reviewed and closed as duplicates of this issue (the earliest open report with maintainer discussion).

**Same failure class:** `System.OutOfMemoryException` (or OpenCV failed-to-allocate) during name scan, stack typically in `RatEye.Processing.Inspection.ScanTitle` / `Bitmap.Clone` / `Crop`, or multi-inspection template matching.

| Closed as duplicate | Version (log) | Resolution | Author notes |
| --- | --- | --- | --- |
| #570 | 3.6.2 | 2560x1440 @ 100% | — |
| #682 | 3.8.2 | 3840x1600 @ 100% | OpenCV `Failed to allocate ~49MB` in multi-inspection |
| #683 | 3.8.2 | 3840x1600 @ 100% | same reporter as #682/#685/#687/#716 |
| #685 | 3.8.2 | 3840x1600 @ 100% | — |
| #687 | 3.8.2 | 3840x1600 @ 100% | — |
| #688 | 3.8.2 | 1920x1080 @ 100% | +1 confirmation in comments |
| #716 | 3.8.5 | 3840x1600 @ 100% | 64GB RAM; game not running (launcher only) |
| #725 | 3.9.0 | 2560x1440 @ 125% | — |
| #735 | 3.9.0 | 2560x1440 @ 100% | concurrent tarkov.dev API failures |

Keeping this issue open as the single tracker for OOM-during-name-scan.

**Comment by DysektAI** [comment]
### Follow-up duplicate cleanup

Additional open memory-pressure / allocation-failure reports during name scan were closed as duplicates of this issue:

| Closed as duplicate | Notes |
| --- | --- |
| #686 | OpenCV `Failed to allocate` in multi-inspection |
| #745 | OpenCV `Failed to allocate` in multi-inspection |
| #791 | GDI+ `Bitmap.Clone`/`Crop` in `ScanTitle` (memory/invalid input wording) |

**Comment by DysektAI** [comment]
### v4.x.x Beta available

A `v4.x.x Beta` is currently being tested which fixes and addresses this and many other issues.

- It's a Work In Progress and still likely has other issues that will be addressed as more updates are made, so expect changes.
- It will be migrated over to the RatScanner/RatScanner repo once fully stable. Until then, this is the best option to avoid pushing unfinished/unstable work to everyone.
- **Read the release details — being a beta, it does come with some risks that can't be accounted for.**

**You can find the beta here: https://github.com/tarkovtracker-org/RatScanner/releases/tag/v4.0.0-beta**
*It should auto-update when more updates are released.

---
_This comment was posted with AI assistance using GLM-5.2 High and may not be 100% accurate. Please verify the information before relying on it._
