### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by JustusWW** [RatScanner/RatScanner#532]
**Error**
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatScanner.Tarko
```
<details>
<summary>Log</summary>

```
[15:59:37.3776598] > [Info]  ----- RatScanner 3.6.2 -----
[15:59:37.3780140] > [Info]  Screen Info: 2560x1440 at 125%
[15:59:37.3780170] > [Info]  Setting temporary default item...
[15:59:37.3785314] > [Info]  Initializing tarkov tracker database
[15:59:37.3786139] > [Info]  Initializing hotkey manager...
[15:59:37.3813660] > [Info]  UI Ready!
[15:59:38.3887584] > [Info]  Checking for updates...
[15:59:38.3899443] > [Info]  Loading resource "RSClientVersion"...
[15:59:38.7976589] > [Info]  Loading item data...
[15:59:39.7145734] > [Info]  Loading price data...
[15:59:40.1546829] > [Info]  Loading TarkovTracker data...
[15:59:40.1546935] > [Info]  Loading TarkovTracker...
[15:59:40.2757483] > [Error] Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
 -------------------- 
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RatScanner.TarkovTrackerDB.GetToken(String custom_token)
   at RatScanner.TarkovTrackerDB.UpdateToken()
   at RatScanner.TarkovTrackerDB.ValidToken()
   at RatScanner.TarkovTrackerDB.Init()
   at RatScanner.RatScannerMain.<.ctor>b__18_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

```
</details>

**Comment by DysektAI** [comment]
Closing as a duplicate of https://github.com/RatScanner/RatScanner/issues/706.

Same `JsonReaderException: Unexpected character encountered while parsing value: <` while deserializing TarkovTracker responses (typically non-JSON/HTML returned for token or progress). #706 is the best-documented open report for this class.
