### ISSUE TITLE
A task was canceled.

### ISSUE THREAD

**Issue by 406395647** [RatScanner/RatScanner#534]
**Error**
A task was canceled.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.TarkovDevAPI.Get(String query)
   at RatScanner.TarkovDevAPI.GetNeededItems(Int64 ttl)
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, UserProgress progress)
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(RenderTreeBuilder __builder5)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBl
```
<details>
<summary>Log</summary>

```
[07:41:31.3713309] > [Info]  ----- RatScanner 3.6.2 -----
[07:41:31.3715462] > [Info]  Screen Info: 2560x1440 at 100%
[07:41:31.3715484] > [Info]  Setting temporary default item...
[07:41:31.3791077] > [Info]  Initializing tarkov tracker database
[07:41:31.3792046] > [Info]  Initializing hotkey manager...
[07:41:31.3823152] > [Info]  UI Ready!
[07:41:32.3910180] > [Info]  Checking for updates...
[07:41:32.3923722] > [Info]  Loading resource "RSClientVersion"...
[07:41:35.9776025] > [Info]  Loading item data...
[07:41:37.0721433] > [Info]  Loading price data...
[07:44:51.5598370] > [Error] A task was canceled.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.TarkovDevAPI.Get(String query)
   at RatScanner.TarkovDevAPI.GetNeededItems(Int64 ttl)
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, UserProgress progress)
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(RenderTreeBuilder __builder5)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateM
```
</details>

**Comment by Blightbuster** [comment]
Hey, please add google dns or a similar one like cloudflare in windows to get around the region block.
[Here is a tutorial to setup google dns in windows.](https://www.my-private-network.co.uk/kbhome/how-to-set-google-dns-on-your-windows-computer/)
