### ISSUE TITLE
Удаленный хост принудительно разорвал существующее подключение.

### ISSUE THREAD

**Issue by Sterlyndarr** [RatScanner/RatScanner#552]
**Error**
Удаленный хост принудительно разорвал существующее подключение.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Error while copying content to a stream.)
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение..
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ReceiveAsync(Memory`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.Rea
```
<details>
<summary>Log</summary>

```
[14:05:58.2581675] > [Info]  ----- RatScanner 3.6.2 -----
[14:05:58.2587211] > [Info]  Screen Info: 1920x1080 at 100%
[14:05:58.2587296] > [Info]  Setting temporary default item...
[14:05:58.2602802] > [Info]  Initializing tarkov tracker database
[14:05:58.2604015] > [Info]  Initializing hotkey manager...
[14:05:58.2656754] > [Info]  UI Ready!
[14:05:59.2682630] > [Info]  Checking for updates...
[14:05:59.2699676] > [Info]  Loading resource "RSClientVersion"...
[14:05:59.4744446] > [Error] Удаленный хост принудительно разорвал существующее подключение.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Error while copying content to a stream.)
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение..
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ReceiveAsync(Memory`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ChunkedE
```
</details>

**Comment by Sterlyndarr** [comment]
I can open it https://api.ratscanner.com/v3/all from the browser

**Comment by Sterlyndarr** [comment]
The installation of google DNS addresses 8.8.8.8
and 8.8.4.4 helped me

**Comment by Blightbuster** [comment]
Thansk for letting me know, I appreciate it a lot ❤️
