### ISSUE TITLE
Удаленный хост принудительно разорвал существующее подключение.

### ISSUE THREAD

**Issue by nikii228** [RatScanner/RatScanner#555]
**Error**
Удаленный хост принудительно разорвал существующее подключение.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Error while copying content to a stream.)
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение..
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   a
```
<details>
<summary>Log</summary>

```
[09:37:30.4270884] > [Info]  ----- RatScanner 3.6.2 -----
[09:37:30.4272915] > [Info]  Screen Info: 2560x1440 at 100%
[09:37:30.4272932] > [Info]  Setting temporary default item...
[09:37:30.4280304] > [Info]  Initializing tarkov tracker database
[09:37:30.4281372] > [Info]  Initializing hotkey manager...
[09:37:30.4310449] > [Info]  UI Ready!
[09:37:31.4439595] > [Info]  Checking for updates...
[09:37:31.4454173] > [Info]  Loading resource "RSClientVersion"...
[09:37:31.6396037] > [Error] Удаленный хост принудительно разорвал существующее подключение.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Error while copying content to a stream.)
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение..
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cancella
```
</details>

**Comment by Blightbuster** [comment]
Hey, please add google dns or a similar one like cloudflare in windows to get around the region block.
[Here is a tutorial to setup google dns in windows.](https://www.my-private-network.co.uk/kbhome/how-to-set-google-dns-on-your-windows-computer/)
