### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by bitpushr** [RatScanner/RatScanner#570]
**Error**
Out of memory.
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.Scan.ItemNameScan..ctor(Inspection inspection, Vector2 toolTipPosition, Int32 duration)
   at RatScanner.RatScannerMain.NameScanScreen(Object _)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[10:23:22.0639964] > [Info]  ----- RatScanner 3.6.2 -----
[10:23:22.0643097] > [Info]  Screen Info: 2560x1440 at 100%
[10:23:22.0643118] > [Info]  Setting temporary default item...
[10:23:22.0648584] > [Info]  Initializing tarkov tracker database
[10:23:22.0649772] > [Info]  Initializing hotkey manager...
[10:23:22.0674492] > [Info]  UI Ready!
[10:23:23.0740855] > [Info]  Checking for updates...
[10:23:23.0753395] > [Info]  Loading resource "RSClientVersion"...
[10:23:23.6970620] > [Info]  Loading item data...
[10:23:24.4741308] > [Info]  Loading price data...
[10:23:25.5587892] > [Info]  Loading TarkovTracker data...
[10:23:25.5587997] > [Info]  Loading TarkovTracker...
[10:23:27.0200905] > [Info]  Initializing RatEye...
[10:23:27.3224179] > [Info]  Setting up timer routines...
[10:23:27.3224369] > [Info]  Setting default item...
[10:23:27.3236004] > [Info]  Enabling hotkeys...
[10:23:27.3236320] > [Info]  Ready!
[10:28:27.3346018] > [Info]  Refreshing TarkovTracker DB...
[10:33:28.3138519] > [Info]  Refreshing TarkovTracker DB...
[10:38:29.3942142] > [Info]  Refreshing TarkovTracker DB...
[10:43:30.4753269] > [Info]  Refreshing TarkovTracker DB...
[10:48:31.4567434] > [Info]  Refreshing TarkovTracker DB...
[10:53:08.7312469] > [Error] Out of memory.
 -------------------- 
 System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.Scan.ItemNameScan..ctor(Inspection inspection, Vector2 toolTipPosition, Int32 duration)
   at RatScanner.RatScannerMain.NameScanScreen(Object _)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[10:53:17.1095271] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by DysektAI** [comment]
Closing as a duplicate of https://github.com/RatScanner/RatScanner/issues/528.

This report shows the same `System.OutOfMemoryException` during name scan in `RatEye.Processing.Inspection.ScanTitle` (often via `Bitmap.Clone` / `Crop`, or related OpenCV allocation during multi-inspection). Issue #528 is the earliest open report with maintainer discussion and is being kept as the canonical tracker for this class of OOM reports.
