### ISSUE TITLE
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)

### ISSUE THREAD

**Issue by Adrop121** [RatScanner/RatScanner#588]
**Error**
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
```
System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1682_0(ErrorCode status, String funcName, String err
```
<details>
<summary>Log</summary>

```
[12:14:37.9235242] > [Info]  ----- RatScanner 3.6.4 -----
[12:14:37.9237182] > [Info]  Screen Info: 2560x1440 at 100%
[12:14:37.9237197] > [Info]  Setting temporary default item...
[12:14:37.9244849] > [Info]  Initializing tarkov tracker database
[12:14:37.9245961] > [Info]  Initializing hotkey manager...
[12:14:37.9278445] > [Info]  UI Ready!
[12:14:38.9360267] > [Info]  Checking for updates...
[12:14:38.9376262] > [Info]  Loading resource "RSClientVersion"...
[12:14:39.4571175] > [Info]  Loading item data...
[12:14:40.8444851] > [Info]  Loading price data...
[12:14:41.6390505] > [Info]  Loading TarkovTracker data...
[12:14:41.6390612] > [Info]  Initializing RatEye...
[12:14:43.4677103] > [Info]  Setting up timer routines...
[12:14:43.4677269] > [Info]  Setting default item...
[12:14:43.4692680] > [Info]  Enabling hotkeys...
[12:14:43.4693055] > [Info]  Ready!
[12:19:42.4526416] > [Error] One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 -------------------- 
 System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1682_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at Rat
```
</details>

**Comment by mix3084** [comment]
**Error**
One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
```
System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1682_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at RatEye.Processing.Icon.<>c__DisplayClass42_0.<TemplateMatchSub>b__0(KeyValuePair`2 icon)
   at System.Threading.Tas
```
<details>
<summary>Log</summary>

```
[12:42:18.8597275] > [Info]  ----- RatScanner 3.6.4 -----
[12:42:18.8606597] > [Info]  Screen Info: 1920x1080 at 100%
[12:42:18.8606649] > [Info]  Setting temporary default item...
[12:42:18.8625118] > [Info]  Initializing tarkov tracker database
[12:42:18.8629463] > [Info]  Initializing hotkey manager...
[12:42:18.8695322] > [Info]  UI Ready!
[12:42:19.8773873] > [Info]  Checking for updates...
[12:42:19.8810077] > [Info]  Loading resource "RSClientVersion"...
[12:42:20.2701589] > [Info]  Loading item data...
[12:42:22.4988611] > [Info]  Loading price data...
[12:42:23.2561943] > [Info]  Loading TarkovTracker data...
[12:42:23.2562099] > [Info]  Initializing RatEye...
[12:42:26.2822959] > [Info]  Setting up timer routines...
[12:42:26.2823211] > [Info]  Setting default item...
[12:42:26.2840727] > [Info]  Enabling hotkeys...
[12:42:26.2841124] > [Info]  Ready!
[12:47:26.2952814] > [Info]  Refreshing TarkovTracker DB...
[12:52:26.3042045] > [Info]  Refreshing TarkovTracker DB...
[12:57:26.3052309] > [Info]  Refreshing TarkovTracker DB...
[13:02:26.3180572] > [Info]  Refreshing TarkovTracker DB...
[13:07:26.3186466] > [Info]  Refreshing TarkovTracker DB...
[13:12:26.2928746] > [Info]  Refreshing Market DB...
[13:12:26.3236792] > [Info]  Refreshing TarkovTracker DB...
[13:17:26.3300180] > [Info]  Refreshing TarkovTracker DB...
[13:22:26.3378199] > [Info]  Refreshing TarkovTracker DB...
[13:27:26.3416070] > [Info]  Refreshing TarkovTracker DB...
[13:29:26.9300909] > [Error] One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 -------------------- 
 System.AggregateException: One or more errors occurred. (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width)
 ---> OpenCvSharp.OpenCVException: _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1682_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at OpenCvSharp.Cv2.MatchTemplate(InputArray image, InputArray templ, OutputArray result, TemplateMatchModes method, InputArray mask)
   at RatEye.Processing.Icon.<>c__DisplayClass42_0.<TemplateMatchSub>b__0(KeyValuePair`2 icon)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack tr
```
</details>
