### ISSUE TITLE
Crashed when updating

### ISSUE THREAD

**Issue by SiliconWolf** [RatScanner/RatScanner#593]
**Error**
The system cannot find the path specified. (0x80070003)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebV
```
<details>
<summary>Log</summary>

```
[14:35:20.4212496] > [Error] The system cannot find the path specified. (0x80070003)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass13_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[14:35:24.4950803] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by chrion02** [comment]
Not sure if related, but WebView2 is in the error message: https://discord.com/channels/687549250435153930/687558810206076971/1068924668087644243

**Comment by SiliconWolf** [comment]
Your link doesnt work as i dont have access, but thanks!
