### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ProductLeadsCantCode** [RatScanner/RatScanner#596]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[18:33:47.0688593] > [Info]  ----- RatScanner 3.6.2 -----
[18:33:47.0691598] > [Info]  Screen Info: 5120x1440 at 100%
[18:33:47.0691635] > [Info]  Setting temporary default item...
[18:33:47.0698253] > [Info]  Initializing tarkov tracker database
[18:33:47.0699219] > [Info]  Initializing hotkey manager...
[18:33:47.0724481] > [Info]  UI Ready!
[18:33:48.0816501] > [Info]  Checking for updates...
[18:33:48.0830056] > [Info]  Loading resource "RSClientVersion"...
[18:33:48.3596952] > [Info]  A new version is available: 3.6.5
[18:33:48.3597090] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[18:34:12.4823967] > [Info]  Saving config...
[18:34:12.5217884] > [Info]  Config saved!
[18:34:13.2567882] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.get_GameScale()
   at RatScanner.RatConfig.NameScan.get_MarkerScanSize()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[18:34:17.9012947] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by DysektAI** [comment]
Closing as **not planned** / stale unreproduced race.

`NullReferenceException` in `RatConfig.get_GameScale()` during name scan (2024), no comments and no new reports of this exact stack. Scale/config loading has changed across releases since. Reopen with a log from the latest release if it still reproduces.
