### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by adundarov** [RatScanner/RatScanner#600]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.HotkeyManager.<>c.<OnCloseInteractableOverlayHotkey>b__14_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[06:45:02.5499504] > [Info]  ----- RatScanner 3.6.2 -----
[06:45:02.5507725] > [Info]  Screen Info: 3440x1440 at 100%
[06:45:02.5507813] > [Info]  Setting temporary default item...
[06:45:02.5523030] > [Info]  Initializing tarkov tracker database
[06:45:02.5524435] > [Info]  Initializing hotkey manager...
[06:45:02.5561944] > [Info]  UI Ready!
[06:45:03.5699660] > [Info]  Checking for updates...
[06:45:03.5719491] > [Info]  Loading resource "RSClientVersion"...
[06:45:03.9191187] > [Info]  A new version is available: 3.6.5
[06:45:03.9191370] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[06:59:36.4376758] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.HotkeyManager.<>c.<OnCloseInteractableOverlayHotkey>b__14_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[07:02:43.9833413] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by DysektAI** [comment]
Closing as **not planned** / stale unreproduced race.

`NullReferenceException` closing the interactable overlay hotkey before init finished (2024). No comments and no recurrence. If still hit on a current release, reopen with version + steps (hotkey immediately on startup).
