### ISSUE TITLE
Rectangle '{X=866,Y=16,Width=0,Height=22}' cannot have a width or height equal to 0.

### ISSUE THREAD

**Issue by zachsamuels** [RatScanner/RatScanner#617]
**Error**
Rectangle '{X=866,Y=16,Width=0,Height=22}' cannot have a width or height equal to 0.
```
System.ArgumentException: Rectangle '{X=866,Y=16,Width=0,Height=22}' cannot have a width or height equal to 0.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[21:36:37.5251490] > [Info]  ----- RatScanner 3.6.5 -----
[21:36:37.5252913] > [Info]  Screen Info: 2560x1440 at 100%
[21:36:37.5252925] > [Info]  Setting temporary default item...
[21:36:37.5258401] > [Info]  Initializing tarkov tracker database
[21:36:37.5259065] > [Info]  Initializing hotkey manager...
[21:36:37.5284636] > [Info]  UI Ready!
[21:36:38.5362129] > [Info]  Checking for updates...
[21:36:38.5371604] > [Info]  Loading resource "RSClientVersion"...
[21:36:38.7589322] > [Info]  Loading item data...
[21:36:39.9409542] > [Info]  Loading price data...
[21:36:40.2518832] > [Info]  Loading TarkovTracker data...
[21:36:40.2518959] > [Info]  Loading TarkovTracker...
[21:36:40.6879392] > [Info]  Initializing RatEye...
[21:36:41.1799629] > [Info]  Setting up timer routines...
[21:36:41.1799783] > [Info]  Setting default item...
[21:36:41.1812950] > [Info]  Enabling hotkeys...
[21:36:41.1813270] > [Info]  Ready!
[21:41:41.1910238] > [Info]  Refreshing TarkovTracker DB...
[21:46:41.3968217] > [Info]  Refreshing TarkovTracker DB...
[21:51:41.7285111] > [Info]  Refreshing TarkovTracker DB...
[21:56:42.0112091] > [Info]  Refreshing TarkovTracker DB...
[22:01:42.2483461] > [Info]  Refreshing TarkovTracker DB...
[22:06:41.1933722] > [Info]  Refreshing Market DB...
[22:06:42.6203729] > [Info]  Refreshing TarkovTracker DB...
[22:11:42.8473643] > [Info]  Refreshing TarkovTracker DB...
[22:16:43.1514867] > [Info]  Refreshing TarkovTracker DB...
[22:21:43.4347218] > [Info]  Refreshing TarkovTracker DB...

```
</details>

**Comment by Blightbuster** [comment]
Tracked in #521
