### ISSUE TITLE
Could not find icon folder at: C:\Users\Denis\AppData\Local\Temp\Rar$EXa13276.35596\Data\icons

### ISSUE THREAD

**Issue by SelenGer123** [RatScanner/RatScanner#618]
**Error**
Could not find icon folder at: C:\Users\Denis\AppData\Local\Temp\Rar$EXa13276.35596\Data\icons
```
System.IO.FileNotFoundException: Could not find icon folder at: C:\Users\Denis\AppData\Local\Temp\Rar$EXa13276.35596\Data\icons
   at RatEye.IconManager.LoadNewIcons(String folderPath, IconType iconType, Int32 retryCount)
   at RatEye.IconManager.LoadStaticIcons()
   at RatEye.IconManager..ctor(Config config)
   at RatEye.RatEyeEngine..ctor(Config config, Database itemDatabase)
   at RatScanner.RatScannerMain.SetupRatEye()
   at RatScanner.RatScannerMain.<.ctor>b__18_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```
<details>
<summary>Log</summary>

```
[08:14:51.0830837] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
You have to extract the zip before running the program
