### ISSUE TITLE
Out of memory.

### ISSUE THREAD

**Issue by JacksonDorschner** [RatScanner/RatScanner#619]
**Error**
Out of memory.
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[22:40:01.3818594] > [Info]  ----- RatScanner 3.6.4 -----
[22:40:01.3822154] > [Info]  Screen Info: 1920x1080 at 100%
[22:40:01.3822179] > [Info]  Setting temporary default item...
[22:40:01.3835367] > [Info]  Initializing tarkov tracker database
[22:40:01.3836813] > [Info]  Initializing hotkey manager...
[22:40:01.3893549] > [Info]  UI Ready!
[22:40:02.3910768] > [Info]  Checking for updates...
[22:40:02.3932206] > [Info]  Loading resource "RSClientVersion"...
[22:40:02.7816969] > [Info]  A new version is available: 3.6.5
[22:40:02.7817118] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[22:40:08.5613340] > [Info]  Loading item data...
[22:40:10.9975856] > [Info]  Loading price data...
[22:40:11.6156796] > [Info]  Loading TarkovTracker data...
[22:40:11.6156938] > [Info]  Initializing RatEye...
[22:40:12.0302624] > [Info]  Setting up timer routines...
[22:40:12.0302940] > [Info]  Setting default item...
[22:40:12.0343484] > [Info]  Enabling hotkeys...
[22:40:12.0344272] > [Info]  Ready!
[22:45:12.0438042] > [Info]  Refreshing TarkovTracker DB...
[22:50:12.0485203] > [Info]  Refreshing TarkovTracker DB...
[22:55:12.8876556] > [Info]  Refreshing TarkovTracker DB...
[22:59:03.9742739] > [Error] Out of memory.
 -------------------- 
 System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)

```
</details>

**Comment by Blightbuster** [comment]
Hmm perhaps a memory leak because the bitmaps in the cropping call dont get disposed properly.
