### ISSUE TITLE
Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.

### ISSUE THREAD

**Issue by NukuTa86** [RatScanner/RatScanner#620]
**Error**
Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
```
Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)
   at RatEye.Processing.Inspection.GetTesseractEngine()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__1
```
<details>
<summary>Log</summary>

```
[08:24:36.7316458] > [Info]  ----- RatScanner 3.6.5 -----
[08:24:36.7316773] > [Info]  Screen Info: 1920x1080 at 100%
[08:24:36.7316800] > [Info]  Setting temporary default item...
[08:24:36.7326057] > [Info]  Initializing tarkov tracker database
[08:24:36.7327091] > [Info]  Initializing hotkey manager...
[08:24:36.7362017] > [Info]  UI Ready!
[08:24:37.7370744] > [Info]  Checking for updates...
[08:24:37.7386157] > [Info]  Loading resource "RSClientVersion"...
[08:24:38.3459416] > [Info]  Loading item data...
[08:24:40.1847228] > [Info]  Loading price data...
[08:24:41.0142158] > [Info]  Loading TarkovTracker data...
[08:24:41.0142267] > [Info]  Initializing RatEye...
[08:24:41.2281267] > [Info]  Setting up timer routines...
[08:24:41.2281435] > [Info]  Setting default item...
[08:24:41.2298572] > [Info]  Enabling hotkeys...
[08:24:41.2298898] > [Info]  Ready!
[08:24:42.3278967] > [Error] Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
 -------------------- 
 Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)
   at RatEye.Processing.Inspection.GetTesseractEngine()
   at RatEye.Processing.Inspection.OCR(Bitmap image)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatEye.Processing.Inspection.get_Item()
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)

```
</details>

**Comment by DysektAI** [comment]
Closing as a duplicate of https://github.com/RatScanner/RatScanner/issues/499.

Same `TesseractException: Failed to initialise tesseract engine` during name-scan OCR (`Inspection.GetTesseractEngine` / `ScanTitle`). Keeping the earliest open report #499 as the tracker.
