### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Gaugous** [RatScanner/RatScanner#644]
**Error**
Object reference not set to an instance of an object.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass13_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.
```
<details>
<summary>Log</summary>

```
[08:21:25.4909574] > [Info]  ----- RatScanner 3.6.5 -----
[08:21:25.4910440] > [Info]  Screen Info: 2560x1440 at 100%
[08:21:25.4910470] > [Info]  Setting temporary default item...
[08:21:25.4918598] > [Info]  Initializing tarkov tracker database
[08:21:25.4921406] > [Info]  Initializing hotkey manager...
[08:21:25.4953765] > [Info]  UI Ready!
[08:21:26.4964238] > [Info]  Checking for updates...
[08:21:26.4979054] > [Info]  Loading resource "RSClientVersion"...
[08:21:26.6088004] > [Info]  Loading item data...
[08:21:28.2707118] > [Info]  Loading price data...
[08:21:28.4957897] > [Info]  Loading TarkovTracker data...
[08:21:28.4958023] > [Info]  Initializing RatEye...
[08:21:28.8053672] > [Info]  Setting up timer routines...
[08:21:28.8053926] > [Info]  Setting default item...
[08:21:28.8076308] > [Info]  Enabling hotkeys...
[08:21:28.8076656] > [Info]  Ready!
[08:23:04.3328908] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass13_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[08:23:13.1021811] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullRefere
```
</details>

**Comment by Blightbuster** [comment]
Please reinstall webview2 to fix the issue.
