### ISSUE TITLE
Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')

### ISSUE THREAD

**Issue by jvs5327** [RatScanner/RatScanner#649]
**Error**
Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at RatScanner.Logger.AppendToLog(String content)
   at RatScanner.MarketDB.GetItemById(String uid)
   at RatScanner.ItemExtensions.GetMarketItem(Item item)
   at RatScanner.ItemExtensions.GetTraderPrice(Item item, String traderId)
   at RatScanner.ItemExtensions.GetBestTrader(Item item)
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_20(RenderTreeBuilder __builder6)
   at MudBlazor.Mu
```
<details>
<summary>Log</summary>

```
[13:06:27.3222888] > [Info]  ----- RatScanner 3.6.5 -----
[13:06:27.3224244] > [Info]  Screen Info: 2560x1440 at 100%
[13:06:27.3224257] > [Info]  Setting temporary default item...
[13:06:27.3229738] > [Info]  Initializing tarkov tracker database
[13:06:27.3230505] > [Info]  Initializing hotkey manager...
[13:06:27.3251951] > [Info]  UI Ready!
[13:06:28.3360410] > [Info]  Checking for updates...
[13:06:28.3369582] > [Info]  Loading resource "RSClientVersion"...
[13:06:28.5903540] > [Info]  Loading item data...
[13:06:29.6675113] > [Info]  Loading price data...
[13:06:30.0313679] > [Info]  Loading TarkovTracker data...
[13:06:30.0313793] > [Info]  Loading TarkovTracker...
[13:06:31.4045613] > [Info]  Initializing RatEye...
[13:06:31.6892345] > [Info]  Setting up timer routines...
[13:06:31.6892495] > [Info]  Setting default item...
[13:06:31.6902784] > [Info]  Enabling hotkeys...
[13:06:31.6903077] > [Info]  Ready!
[13:11:31.6921593] > [Info]  Refreshing TarkovTracker DB...
[13:16:32.6124991] > [Info]  Refreshing TarkovTracker DB...
[13:21:33.7332851] > [Info]  Refreshing TarkovTracker DB...
[13:26:34.9130117] > [Info]  Refreshing TarkovTracker DB...
[13:31:35.8242147] > [Info]  Refreshing TarkovTracker DB...
[13:36:31.6809682] > [Info]  Refreshing Market DB...
[13:36:36.8293420] > [Info]  Refreshing TarkovTracker DB...
[13:41:37.8048929] > [Info]  Refreshing TarkovTracker DB...
[13:46:39.1613306] > [Info]  Refreshing TarkovTracker DB...
[13:51:40.1058127] > [Info]  Refreshing TarkovTracker DB...
[13:56:41.1326764] > [Info]  Refreshing TarkovTracker DB...
[14:01:42.1239244] > [Info]  Refreshing TarkovTracker DB...
[14:06:32.1545781] > [Info]  Refreshing Market DB...
[14:06:43.6713466] > [Info]  Refreshing TarkovTracker DB...
[14:11:44.8206377] > [Info]  Refreshing TarkovTracker DB...
[14:16:45.8113598] > [Info]  Refreshing TarkovTracker DB...
[14:21:47.1691042] > [Info]  Refreshing TarkovTracker DB...
[14:26:48.0724043] > [Info]  Refreshing TarkovTracker DB...
[14:31:49.3713986] > [Info]  Refreshing TarkovTracker DB...
[14:36:32.7175170] > [Info]  Refreshing Market DB...
[14:36:50.6555050] > [Info]  Refreshing TarkovTracker DB...
[14:41:51.8457011] > [Info]  Refreshing TarkovTracker DB...
[14:46:53.5706829] > [Info]  Refreshing TarkovTracker DB...
[14:51:54.9334166] > [Info]  Refreshing TarkovTracker DB...
[14:56:56.2278407] > [Info]  Refreshing TarkovTracker DB...
[15:01:57.0342965] > [Info]  Refreshing TarkovTracker DB...
[15:06:33.1779678] > [Info]  Refreshing Market DB...
[15:06:57.9459720] > [Info]  Refreshing TarkovTracker DB...
[15:11:58.9418795] > [Info]  Refreshing TarkovTracker DB...
[15:16:59.9794164] > [Info]  Refreshing TarkovTracker DB...
[15:22:00.9380623] > [Info]  Refreshing TarkovTracker DB...
[15:27:01.8369116] > [Info]  Refreshing TarkovTracker DB...
[15:32:02.9197703] > [Info]  Refreshing TarkovTracker DB...
[15:36:33.5896834] > [Info]  Refreshing Market DB...
[15:37:03.9677592] > [Info]  Refreshing TarkovTracker DB...
[15:42:
```
</details>

**Comment by DysektAI** [comment]
### Duplicate cleanup

#356 was closed as a duplicate of this issue (same `Logger.AppendToLog` / `Queue.SetCapacity` overflow with `Source array was not long enough`). This issue's title better matches the failure mode.

**Comment by DysektAI** [comment]
### v4.x.x Beta available

A `v4.x.x Beta` is currently being tested which fixes and addresses this and many other issues.

- It's a Work In Progress and still likely has other issues that will be addressed as more updates are made, so expect changes.
- It will be migrated over to the RatScanner/RatScanner repo once fully stable. Until then, this is the best option to avoid pushing unfinished/unstable work to everyone.
- **Read the release details — being a beta, it does come with some risks that can't be accounted for.**

**You can find the beta here: https://github.com/tarkovtracker-org/RatScanner/releases/tag/v4.0.0-beta**
*It should auto-update when more updates are released.

---
_This comment was posted with AI assistance using GLM-5.2 High and may not be 100% accurate. Please verify the information before relying on it._
