### ISSUE TITLE
Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by gcatellani** [RatScanner/RatScanner#650]
**Error**
Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding, RatScanner'. Path 'data.tasks[355].objectives[0].$type', line 1, position 606363.
 ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName(StructMultiKey`2 typeNameKey)
   at Newtonsoft.Json.Serialization.DefaultSerialization
```
<details>
<summary>Log</summary>

```
[23:12:17.2231331] > [Info]  ----- RatScanner 3.6.5 -----
[23:12:17.2233935] > [Info]  Screen Info: 2560x1440 at 100%
[23:12:17.2233995] > [Info]  Setting temporary default item...
[23:12:17.2243845] > [Info]  Initializing tarkov tracker database
[23:12:17.2244929] > [Info]  Initializing hotkey manager...
[23:12:17.2275149] > [Info]  UI Ready!
[23:12:17.7282072] > [Error] Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding, RatScanner'. Path 'data.tasks[355].objectives[0].$type', line 1, position 606363.
 ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName(StructMultiKey`2 typeNameKey)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at 
```
</details>

**Comment by ZachRWL** [comment]
I'm having this issue too. Came out of nowhere.

**Comment by gcatellani** [comment]
@Blightbuster: woah, you're fast! Thank you for the dedication and hard work.
