### ISSUE TITLE
A task was canceled.

### ISSUE THREAD

**Issue by ThatGuyRade** [RatScanner/RatScanner#655]
**Error**
A task was canceled.
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (A task was canceled.))
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.TarkovDevAPI.Get(String query)
   at RatScanner.TarkovDevAPI.GetNeededItems(Int64 ttl)
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, UserProgress progress)
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(
```
<details>
<summary>Log</summary>

```
[08:50:23.0228404] > [Info]  ----- RatScanner 3.6.6 -----
[08:50:23.0231543] > [Info]  Screen Info: 2560x1440 at 100%
[08:50:23.0231576] > [Info]  Setting temporary default item...
[08:50:23.0243818] > [Info]  Initializing tarkov tracker database
[08:50:23.0245547] > [Info]  Initializing hotkey manager...
[08:50:23.0288508] > [Info]  UI Ready!
[08:50:24.0344943] > [Info]  Checking for updates...
[08:50:24.0372778] > [Info]  Loading resource "RSClientVersion"...
[08:50:24.7293378] > [Info]  Loading item data...
[08:50:28.1943994] > [Info]  Loading price data...
[08:50:29.1492708] > [Info]  Loading TarkovTracker data...
[08:50:29.1492968] > [Info]  Initializing RatEye...
[08:50:30.4565574] > [Info]  Setting up timer routines...
[08:50:30.4565871] > [Info]  Setting default item...
[08:50:30.4646883] > [Info]  Enabling hotkeys...
[08:50:30.4654461] > [Info]  Ready!
[08:53:43.3722146] > [Error] A task was canceled.
 -------------------- 
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (A task was canceled.))
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.TarkovDevAPI.Get(String query)
   at RatScanner.TarkovDevAPI.GetNeededItems(Int64 ttl)
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, UserProgress progress)
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(RenderTreeBuilder __builder5)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsof
```
</details>

**Comment by ThatGuyRade** [comment]
RatScanner starts but the window just gets stuck at "loading" for me, and after a while I get this error

**Comment by Blightbuster** [comment]
Should be fixed now. Tarkov.dev API is having some issues right now due to backend work thats being done.
