### ISSUE TITLE
Query not found in cache. Was InitializeCache called?

### ISSUE THREAD

**Issue by Jeezy00321** [RatScanner/RatScanner#656]
**Error**
Query not found in cache. Was InitializeCache called?
```
System.Exception: Query not found in cache. Was InitializeCache called?
   at RatScanner.TarkovDevAPI.GetCached[T](String query, Int64 ttl)
   at RatScanner.TarkovDevAPI.GetItems()
   at RatScanner.Scan.ItemNameScan..ctor(Inspection inspection, Vector2 toolTipPosition, Int32 duration)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[18:52:20.1051961] > [Info]  ----- RatScanner 3.7.1+bea7ea5c762b9538f89aa24d90d9318567de8f40 -----
[18:52:20.1073572] > [Info]  Screen Info: 1920x1080 at 100%
[18:52:20.1073698] > [Info]  Initializing TarkovDev API...
[18:52:20.1127567] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[18:52:20.1128815] > [Info]  Queueing request for query: "{   data: tasks {     id     ..."
[18:52:20.1470685] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[18:52:20.4247523] > [Info]  Refreshed cache in 311ms (106ms) for query: "{   data: hideoutStations {   ..."
[18:52:20.5463922] > [Info]  Refreshed cache in 433ms (222ms) for query: "{   data: tasks {     id     ..."
[18:52:21.8730364] > [Info]  Refreshed cache in 1725ms (1202ms) for query: "query{data:items(lang:en,gameMod..."
[18:52:21.8753640] > [Info]  Initializing tarkov tracker database
[18:52:21.8755127] > [Info]  Initializing hotkey manager...
[18:52:21.8809521] > [Info]  UI Ready!
[18:52:21.8809692] > [Info]  Initializing RatEye...
[18:52:23.1017324] > [Info]  Checking for updates...
[18:52:23.1032714] > [Info]  Loading resource "RSClientVersion"...
[18:52:23.2231069] > [Info]  A new version is available: 3.7.3
[18:52:23.2231176] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[18:52:24.9833936] > [Info]  Loading TarkovTracker data...
[18:52:24.9834126] > [Info]  Setting up timer routines...
[18:52:24.9834266] > [Info]  Enabling hotkeys...
[18:52:24.9834896] > [Info]  Ready!
[18:53:43.5859810] > [Info]  Saving config...
[18:53:43.6261593] > [Info]  Config saved!
[18:53:47.2009045] > [Info]  Saving config...
[18:53:47.2386365] > [Info]  Config saved!
[18:53:53.1334333] > [Info]  Saving config...
[18:53:53.1612638] > [Info]  Config saved!
[18:54:00.8865301] > [Error] Query not found in cache. Was InitializeCache called?
 -------------------- 
 System.Exception: Query not found in cache. Was InitializeCache called?
   at RatScanner.TarkovDevAPI.GetCached[T](String query, Int64 ttl)
   at RatScanner.TarkovDevAPI.GetItems()
   at RatScanner.Scan.ItemNameScan..ctor(Inspection inspection, Vector2 toolTipPosition, Int32 duration)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
[18:56:21.5634410] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Jeezy00321** [comment]
Ratscanner also takes around 15 seconds per name scan but takes less than a second for most icon scans and sometimes wont let me scan using names at all

**Comment by Jeezy00321** [comment]
Version 3.6.6 seems to work perfectly in both scanning methods

**Comment by Blightbuster** [comment]
Fixed in latest version.

**Comment by Blightbuster** [comment]
> Ratscanner also takes around 15 seconds per name scan but takes less than a second for most icon scans and sometimes wont let me scan using names at all

Working on a fix for this 👍
