### ISSUE TITLE
One or more errors occurred. (A task was canceled.)

### ISSUE THREAD

**Issue by Yveldi** [RatScanner/RatScanner#667]
**Error**
One or more errors occurred. (A task was canceled.)
```
System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MinimalMenu..ctor()
   at RatScanner.View.MinimalMenu.get_Instance()
   at RatScanner.PageSwitcher.ShowMinimalUI()
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInst
```
<details>
<summary>Log</summary>

```
[15:38:24.9901165] > [Info]  ----- RatScanner 3.7.4 -----
[15:38:24.9941183] > [Info]  Screen Info: 1920x1080 at 100%
[15:38:24.9941407] > [Info]  Initializing TarkovDev API...
[15:38:24.9996511] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[15:38:24.9997415] > [Info]  Queueing request for query: "{   data: tasks {     id     ..."
[15:38:25.0317861] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[15:38:25.5815914] > [Info]  Refreshed cache in 581ms (73ms) for query: "{   data: hideoutStations {   ..."
[15:38:27.6019393] > [Info]  Refreshed cache in 2570ms (1407ms) for query: "query{data:items(lang:en,gameMod..."
[15:40:05.0667247] > [Error] One or more errors occurred. (A task was canceled.)
 -------------------- 
 System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MinimalMenu..ctor()
   at RatScanner.View.MinimalMenu.get_Instance()
   at RatScanner.PageSwitcher.ShowMinimalUI()
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, P
```
</details>

**Comment by DysektAI** [comment]
Closing as **not planned** (stale transient auto-report).

`TaskCanceledException` during startup construction with no comments or reproduction. This class of failure is typically network timeout/cancellation rather than a durable product bug. Prefer tracking recurring, well-documented cases (e.g. newer network/startup threads) over multi-year silent auto-reports.
