### ISSUE TITLE
The group or resource is not in the correct state to perform the requested operation. (0x8007139F)

### ISSUE THREAD

**Issue by victordcp** [RatScanner/RatScanner#669]
**Error**
The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
 ---> System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Obj
```
<details>
<summary>Log</summary>

```
[15:07:59.3860660] > [Info]  ----- RatScanner 3.7.4 -----
[15:07:59.3899295] > [Info]  Screen Info: 1920x1080 at 100%
[15:07:59.3899371] > [Info]  Initializing TarkovDev API...
[15:07:59.3953327] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[15:07:59.3954493] > [Info]  Queueing request for query: "{   data: tasks {     id     ..."
[15:07:59.4237334] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[15:09:03.0604617] > [Info]  Refreshed cache in 63664ms (66ms) for query: "{   data: hideoutStations {   ..."
[15:09:03.1564491] > [Info]  Refreshed cache in 63760ms (96ms) for query: "{   data: tasks {     id     ..."
[15:09:05.3080540] > [Info]  Refreshed cache in 65884ms (1033ms) for query: "query{data:items(lang:en,gameMod..."
[15:09:05.3096628] > [Info]  Initializing tarkov tracker database
[15:09:05.3097530] > [Info]  Initializing hotkey manager...
[15:09:05.3125694] > [Info]  UI Ready!
[15:09:05.3125752] > [Info]  Initializing RatEye...
[15:09:05.6810228] > [Error] The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
 ---> System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND accessKind)
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2.SetVirtualHostNameToFolderMapping(String hostName, String folderPath, CoreWebView2HostResourceAccessKind accessKind)
   at RatScanner.View.BlazorOverlay.CoreWebView_Loaded(Object sender, CoreWebView2InitializationCompletedEventArgs e)
   at Microsoft.Web.WebView2.Wpf.WebView2Base.<>c__DisplayClass33_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass13_0.<<NavigateCore>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at 
```
</details>

**Comment by Blightbuster** [comment]
Please try reinstalling webview2 as described in the FAQ
