### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by FernandoMAndrade** [RatScanner/RatScanner#673]
Crashes at splash screen

**Error**
Object reference not set to an instance of an object.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, UserProgress progress)
   at RatScanner.ViewModel.MenuVM.get_TaskRemaining()
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(RenderTreeBuilder __builder5)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass12_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebVi
```
<details>
<summary>Log</summary>

```
[17:12:10.6169976] > [Info]  ----- RatScanner 3.7.5 -----
[17:12:10.6241440] > [Info]  Screen Info: 1920x1080 at 100%
[17:12:10.6241501] > [Info]  Initializing TarkovDev API...
[17:12:10.6360055] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[17:12:10.6664405] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[17:12:10.6666440] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[17:12:11.0258652] > [Info]  Refreshed cache in 359ms (34ms) [1ms] for query: "query{data:tasks(lang:en,gameMod..."
[17:12:11.0438763] > [Info]  Refreshed cache in 407ms (61ms) [0ms] for query: "{   data: hideoutStations {   ..."
[17:12:13.3663050] > [Info]  Refreshed cache in 2699ms (1641ms) [101ms] for query: "query{data:items(lang:en,gameMod..."
[17:12:13.3687988] > [Info]  Initializing tarkov tracker database
[17:12:13.3689129] > [Info]  Initializing hotkey manager...
[17:12:13.3729776] > [Info]  UI Ready!
[17:12:13.3729842] > [Info]  Initializing RatEye...
[17:12:13.9285235] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, UserProgress progress)
   at RatScanner.ViewModel.MenuVM.get_TaskRemaining()
   at RatScanner.Pages.App.Index.<BuildRenderTree>b__0_21(RenderTreeBuilder __builder5)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudPaper.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass12_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate call
```
</details>

**Comment by Blightbuster** [comment]
Fixed in v3.8.2
