### ISSUE TITLE
Could not find a part of the path 'C:\Users\Kevin Greb\AppData\Local\Temp\Rar$EXa23604.46521\Data\icons'.

### ISSUE THREAD

**Issue by zaGREB245** [RatScanner/RatScanner#676]
**Error**
Could not find a part of the path 'C:\Users\Kevin Greb\AppData\Local\Temp\Rar$EXa23604.46521\Data\icons'.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kevin Greb\AppData\Local\Temp\Rar$EXa23604.46521\Data\icons'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at RatEye.IconManager.LoadStaticCorrelationData()
   at RatEye.IconManager.LoadStaticIcons()
   at RatEye.IconManager..ctor(Config config)
   at R
```
<details>
<summary>Log</summary>

```
[13:29:26.3206604] > [Info]  Queueing request for query: "query{data:items(lang:de,gameMod..."
[13:29:26.3209017] > [Info]  Queueing request for query: "query{data:tasks(lang:de,gameMod..."
[13:29:26.3209851] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[13:29:26.5635339] > [Info]  Refreshed cache in 242ms (1ms) [0ms] for query: "{   data: hideoutStations {   ..."
[13:29:48.7644815] > [Info]  Refreshed cache in 22443ms (32ms) [4ms] for query: "query{data:tasks(lang:de,gameMod..."
[13:29:58.3467665] > [Info]  Refreshed cache in 32026ms (491ms) [63ms] for query: "query{data:items(lang:de,gameMod..."
[13:29:58.3512429] > [Error] Could not find a part of the path 'C:\Users\Kevin Greb\AppData\Local\Temp\Rar$EXa23604.46521\Data\icons'.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kevin Greb\AppData\Local\Temp\Rar$EXa23604.46521\Data\icons'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at RatEye.IconManager.LoadStaticCorrelationData()
   at RatEye.IconManager.LoadStaticIcons()
   at RatEye.IconManager..ctor(Config config)
   at RatEye.RatEyeEngine..ctor(Config config, Database itemDatabase)
   at RatScanner.RatScannerMain.SetupRatEye()
   at RatScanner.ViewModel.SettingsVM.SaveSettings()
   at RatScanner.Pages.App.Settings.SettingsSave.SaveSettings()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[13:30:04.5215416] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
You need to extract the zip before running rat scanner
