### ISSUE TITLE
App launches. Errors out when attempting to use. 

### ISSUE THREAD

**Issue by bauvdel** [RatScanner/RatScanner#677]
I am able to launch the app. It does "hang" for a bit, but eventually loads to the following:
<img width="261" alt="2024-09-03 21_28_07-RatScanner Overlay" src="https://github.com/user-attachments/assets/68a01327-e22f-44ff-84fa-0eb724fce9ec">
As soon as I click anywhere on the app, it crashes with:
<img width="357" alt="2024-09-03 21_28_15-RatScanner Overlay" src="https://github.com/user-attachments/assets/220af099-4fa9-46b5-979e-062967251a23">

Things I have tried:
Re downloading and unzipping.
Running as admin.
Removing WebView2 and re installing per FAQ.
Changed monitor scaling.

Any help would be greatly appreciated!

**Error**
The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed
   at Microsoft.Web.WebView2.Wpf.WebView2Base.get_CoreWebView2()
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass14_0.<<NotifyErrors>g__AwaitAndNotify|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass12_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher
```
<details>
<summary>Log</summary>

```
[01:28:01.5246852] > [Info]  ----- RatScanner 3.7.6 -----
[01:28:01.5261009] > [Info]  Screen Info: 3840x2160 at 150%
[01:28:01.5261057] > [Info]  Initializing TarkovDev API...
[01:28:01.5334432] > [Info]  Queueing request for query: "{   data: hideoutStations {   ..."
[01:28:01.5537560] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[01:28:01.5537632] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[01:28:01.8620519] > [Info]  Refreshed cache in 328ms (65ms) [4ms] for query: "{   data: hideoutStations {   ..."
[01:28:01.9806065] > [Info]  Refreshed cache in 426ms (145ms) [12ms] for query: "query{data:tasks(lang:en,gameMod..."
[01:28:03.5219867] > [Info]  Refreshed cache in 1968ms (1049ms) [89ms] for query: "query{data:items(lang:en,gameMod..."
[01:28:03.5237383] > [Info]  Initializing tarkov tracker database
[01:28:03.5238339] > [Info]  Initializing hotkey manager...
[01:28:03.5261562] > [Info]  UI Ready!
[01:28:03.5261625] > [Info]  Initializing RatEye...
[01:28:04.6383248] > [Info]  Checking for updates...
[01:28:04.6394025] > [Info]  Loading resource "RSClientVersion"...
[01:28:04.7601552] > [Info]  Loading TarkovTracker data...
[01:28:04.7601646] > [Info]  Setting up timer routines...
[01:28:04.7601704] > [Info]  Enabling hotkeys...
[01:28:04.7602010] > [Info]  Ready!
[01:28:12.7826258] > [Error] The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed
   at Microsoft.Web.WebView2.Wpf.WebView2Base.get_CoreWebView2()
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass14_0.<<NotifyErrors>g__AwaitAndNotify|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass12_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)

```
</details>

**Comment by Blightbuster** [comment]
Hm thats a new one for sure. Do you have some sort of special windows installation which claims to make windows "lightweight"?

**Comment by bauvdel** [comment]
Negative. Win 11 Pro. 23H2. Latest Windows Updates. I also tried fulling uninstalling an installing the WebView2 Offline Installer, with no change.

**Comment by Blightbuster** [comment]
Do you have some kind of other windows optimization / theming software maybe? Some kind of overlay? Its kinda hard for me to fix the issue since I am not able to reproduce it.

**Comment by DysektAI** [comment]
### Duplicate cleanup

#712 was closed as a duplicate of this issue (same WebView browser-process-crashed failure). This issue is kept because it already has maintainer troubleshooting discussion.

**Comment by DysektAI** [comment]
### v4.x.x Beta available

A `v4.x.x Beta` is currently being tested which fixes and addresses this and many other issues.

- It's a Work In Progress and still likely has other issues that will be addressed as more updates are made, so expect changes.
- It will be migrated over to the RatScanner/RatScanner repo once fully stable. Until then, this is the best option to avoid pushing unfinished/unstable work to everyone.
- **Read the release details — being a beta, it does come with some risks that can't be accounted for.**

**You can find the beta here: https://github.com/tarkovtracker-org/RatScanner/releases/tag/v4.0.0-beta**
*It should auto-update when more updates are released.

---
_This comment was posted with AI assistance using GLM-5.2 High and may not be 100% accurate. Please verify the information before relying on it._
