### ISSUE TITLE
Unsynchronized access of async cache update

### ISSUE THREAD

**Issue by cain27k** [RatScanner/RatScanner#678]
**Error**
Failed to fetch query response and no cache available.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Failed to fetch query response and no cache available.)
 ---> System.Exception: Failed to fetch query response and no cache available.
   at RatScanner.TarkovDevAPI.QueueRequest[T](String query, Int64 ttl)
   at RatScanner.TarkovDevAPI.InitializeCache()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__11_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgum
```
<details>
<summary>Log</summary>

```
[11:22:17.8118874] > [Info]  ----- RatScanner 3.8.0 -----
[11:22:17.8124670] > [Info]  Screen Info: 1920x1080 at 100%
[11:22:17.8124813] > [Info]  Initializing TarkovDev API...
[11:22:17.8410482] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[11:22:17.8410542] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[11:22:17.8410592] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[11:22:17.8456327] > [Warning] Failed to request query: "query{data:tasks(lang:en,gameMod...".
[11:22:17.8463193] > System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at RatScanner.TarkovDevAPI.QueueRequestInner[T](String query, Int64 ttl)
   at RatScanner.TarkovDevAPI.QueueRequest[T](String query, Int64 ttl)
[11:22:18.5210034] > [Info]  Refreshed cache in 679ms (152ms) [14ms] for query: "query{data:hideoutStations(lang:..."
[11:22:20.5778665] > [Info]  Refreshed cache in 2736ms (1643ms) [90ms] for query: "query{data:items(lang:en,gameMod..."
[11:22:20.5864294] > [Error] Failed to fetch query response and no cache available.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Failed to fetch query response and no cache available.)
 ---> System.Exception: Failed to fetch query response and no cache available.
   at RatScanner.TarkovDevAPI.QueueRequest[T](String query, Int64 ttl)
   at RatScanner.TarkovDevAPI.InitializeCache()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__11_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.Dependen
```
</details>

**Comment by Blightbuster** [comment]
Thanks for reporting, fixed in v3.8.1
