### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by maksatkartanbaev** [RatScanner/RatScanner#679]
**Error**
Object reference not set to an instance of an object.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.ItemExtensions.GetTaskRemaining(Item item, UserProgress progress)
   at RatScanner.Pages.InteractableOverlay.Index.<>c__DisplayClass0_0.<BuildRenderTree>b__10(RenderTreeBuilder __builder6)
   at MudBlazor.MudStack.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.WebView.IpcSender.<>c__DisplayClass12_0.<NotifyUnhandledException>b__1()
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.WebView.Wpf.WpfDispatcher.<>c.<.cctor>b__8_0(Excep
```
<details>
<summary>Log</summary>

```
[06:52:11.9015977] > [Info]  ----- RatScanner 3.8.2 -----
[06:52:11.9020790] > [Info]  Screen Info: 2560x1440 at 100%
[06:52:11.9020919] > [Info]  Initializing TarkovDev API...
[06:52:11.9276936] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[06:52:11.9276909] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[06:52:11.9276965] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[06:52:12.7948283] > [Info]  Refreshed cache in 867ms (152ms) [16ms] for query: "query{data:hideoutStations(lang:..."
[06:52:13.0910603] > [Info]  Refreshed cache in 1163ms (200ms) [8ms] for query: "query{data:tasks(lang:en,gameMod..."
[06:52:22.9786447] > [Info]  Refreshed cache in 11050ms (1105ms) [67ms] for query: "query{data:items(lang:en,gameMod..."
[06:52:22.9809516] > [Info]  Initializing tarkov tracker database
[06:52:22.9810614] > [Info]  Initializing hotkey manager...
[06:52:22.9839228] > [Info]  UI Ready!
[06:52:22.9839336] > [Info]  Initializing RatEye...
[06:52:26.0285123] > [Info]  Checking for updates...
[06:52:26.0300034] > [Info]  Loading resource "RSClientVersion"...
[06:52:26.7175804] > [Info]  Loading TarkovTracker data...
[06:52:26.7176013] > [Info]  Setting up timer routines...
[06:52:26.7176153] > [Info]  Enabling hotkeys...
[06:52:26.7176675] > [Info]  Ready!
[06:52:47.1652204] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[06:52:47.1652275] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[06:52:47.4205583] > [Info]  Refreshed cache in 255ms (37ms) [9ms] for query: "query{data:tasks(lang:en,gameMod..."
[06:52:49.2999287] > [Info]  Refreshed cache in 2134ms (16ms) [3ms] for query: "query{data:hideoutStations(lang:..."
[06:52:59.7934502] > [Info]  Refreshed cache in 12628ms (512ms) [88ms] for query: "query{data:items(lang:en,gameMod..."
[06:53:00.6886152] > [Info]  Saving config...
[06:53:00.7213120] > [Info]  Config saved!
[06:53:06.8737934] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[06:53:06.8738116] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[06:53:06.8738247] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[06:53:07.1259842] > [Info]  Refreshed cache in 252ms (39ms) [5ms] for query: "query{data:tasks(lang:en,gameMod..."
[06:53:07.2279737] > [Info]  Refreshed cache in 354ms (19ms) [8ms] for query: "query{data:hideoutStations(lang:..."
[06:53:16.6537981] > [Info]  Refreshed cache in 9779ms (517ms) [49ms] for query: "query{data:items(lang:en,gameMod..."
[06:53:16.6539609] > [Info]  Saving config...
[06:53:16.6859702] > [Info]  Config saved!
[06:53:45.0249473] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[06:53:45.0249656] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[06:53:45.2328537] > [Info]  Refreshed cache in 207ms (19ms) [3ms] for query: "query{data:hideo
```
</details>

**Comment by Blightbuster** [comment]
Were you searching for any specific item in the overlay? Any steps to reproduce this?

**Comment by jose-roca** [comment]
The same happens to me. Just by opening the program I don't have to take any other steps to reproduce it 😃
