### ISSUE TITLE
Latest patch - Unhandled exception in RatScanner 2.5.1 - keeps happening over and over.

### ISSUE THREAD

**Issue by Sleaker** [RatScanner/RatScanner#68]
**Error**
Unhandled exception in RatScanner 2.5.1
```
System.ArgumentException: Lock was not correctly acquired / released.
   at RatScanner.RatScannerMain.set_ScanLock(Boolean value)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
<details>
<summary>Log</summary>

```
[22:32:46.9108429] > [Info]  ----- RatScanner 2.5.1 -----
[22:32:46.9117174] > [Info]  Starting RatScanner...
[22:32:46.9118518] > [Info]  Loading config...
[22:32:46.9307100] > [Info]  Loading price data...
[22:32:47.9700568] > [Info]  Setting default item...
[22:32:47.9743968] > [Info]  Initializing name scan...
[22:32:47.9745753] > [Info]  Loading OCR data...
[22:32:48.0855822] > [Info]  Initializing icon scan...
[22:32:48.0874281] > [Info]  Loading static icons...
[22:32:48.2705593] > [Info]  Loaded 1197/1197 icons successfully.
[22:32:48.2728637] > [Info]  Loading static correlation data...
[22:32:48.3001448] > [Info]  Loading dynamic correlation data...
[22:32:48.3905970] > [Info]  Loading dynamic icons...
[22:32:48.6776860] > [Info]  Loaded 4598/4598 icons successfully.
[22:32:48.6841759] > [Info]  Initializing file watcher for icon cache...
[22:32:48.6863980] > [Info]  Prewarming name tool tip...
[22:32:48.7382827] > [Info]  Prewarming icon tool tip...
[22:32:48.7661626] > [Info]  Initializing hotkey manager...
[22:32:48.7683125] > [Info]  Checking for new updates...
[22:32:48.7695571] > [Info]  Loading resource "RSClientVersion"...
[22:32:49.0131222] > [Info]  Ready!
[22:32:49.0324173] > [Info]  Loading resource "RSPatreon"...
[22:32:49.2668132] > [Info]  Loading resource "RSDiscord"...
[22:32:49.5047523] > [Info]  Loading resource "RSGithub"...
[22:32:56.7112504] > [Warning] Could not find icon key for:
Uid: 5dfcd0e547101c39625f66f9
[22:33:41.6684791] > [Warning] Could not find icon key for:
Uid: 5dfcd0e547101c39625f66f9
[23:10:23.3051412] > [Warning] Could not find icon key for:
Uid: 5f60b34a41e30a4ab12a6947
[23:12:42.4525354] > [Info]  Loading dynamic correlation data...
[23:12:42.5149089] > [Info]  Loading dynamic icons...
[23:12:42.7604695] > [Info]  Loaded 4599/4599 icons successfully.
[23:12:42.7665486] > [Info]  Loading dynamic correlation data...
[23:12:42.7718563] > [Info]  Dynamic correlation data already up to date
[23:12:42.7719058] > [Info]  Loading dynamic correlation data...
[23:12:42.7903933] > [Info]  Dynamic correlation data already up to date
[23:12:42.7904706] > [Info]  Loading dynamic correlation data...
[23:12:42.7948531] > [Info]  Dynamic correlation data already up to date
[23:12:46.5124660] > [Info]  Loading dynamic correlation data...
[23:12:46.6004266] > [Info]  Loading dynamic icons...
[23:12:46.9122761] > [Info]  Loaded 4600/4600 icons successfully.
[23:12:46.9188963] > [Info]  Loading dynamic correlation data...
[23:12:46.9217553] > [Info]  Dynamic correlation data already up to date
[23:12:46.9218158] > [Info]  Loading dynamic correlation data...
[23:12:46.9250495] > [Info]  Dynamic correlation data already up to date
[23:12:46.9251066] > [Info]  Loading dynamic correlation data...
[23:12:46.9290759] > [Info]  Dynamic correlation data already up to date
[23:14:00.5088434] > [Info]  Loading dynamic correlation data...
[23:14:00.5898718] > [Info]  Loading dynamic icons...
[23:14:00.8456906] > [Info]  Loaded 
```
</details>

**Comment by jangforce08** [comment]
me too
