### ISSUE TITLE
Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by Arabart** [RatScanner/RatScanner#680]
**Error**
Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding, RatScanner'. Path 'data.tasks[393].objectives[0].$type', line 1, position 658082.
 ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName(StructMultiKey`2 typeNameKey)
   at Newtonsoft.Json.Serialization.DefaultSerialization
```
<details>
<summary>Log</summary>

```
[06:41:50.7350246] > [Info]  ----- RatScanner 3.6.5 -----
[06:41:50.7352501] > [Info]  Screen Info: 1920x1080 at 100%
[06:41:50.7352520] > [Info]  Setting temporary default item...
[06:41:50.7361258] > [Info]  Initializing tarkov tracker database
[06:41:50.7362807] > [Info]  Initializing hotkey manager...
[06:41:50.7401441] > [Info]  UI Ready!
[06:41:51.7469394] > [Info]  Checking for updates...
[06:41:51.7485733] > [Info]  Loading resource "RSClientVersion"...
[06:41:51.9137619] > [Error] Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding, RatScanner'. Path 'data.tasks[393].objectives[0].$type', line 1, position 658082.
 ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName(StructMultiKey`2 typeNameKey)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, J
```
</details>

**Comment by Blightbuster** [comment]
Hey, please update to the latest version by manually downloading it if RatScanner crashes before asking to auto-update.
