### ISSUE TITLE
Failed to allocate 49195528 bytes

### ISSUE THREAD

**Issue by salavatov** [RatScanner/RatScanner#682]
**Error**
Failed to allocate 49195528 bytes
```
OpenCvSharp.OpenCVException: Failed to allocate 49195528 bytes
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at RatEye.Processing.MultiInspection.GetMarkerPositions(Bitmap marker)
   at RatEye.Processing.MultiInspection.SearchMarker()
   at RatScanner.RatScannerMain.NameScanScreen(Object _)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[11:46:54.5173904] > [Info]  ----- RatScanner 3.8.2 -----
[11:46:54.5183554] > [Info]  Screen Info: 3840x1600 at 100%
[11:46:54.5183596] > [Info]  Initializing TarkovDev API...
[11:46:54.5356427] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[11:46:54.5356466] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[11:46:54.5356492] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[11:46:54.8926308] > [Info]  Refreshed cache in 356ms (105ms) [14ms] for query: "query{data:hideoutStations(lang:..."
[11:46:54.9747063] > [Info]  Refreshed cache in 439ms (130ms) [3ms] for query: "query{data:tasks(lang:en,gameMod..."
[11:47:01.9366214] > [Info]  Refreshed cache in 7400ms (1063ms) [51ms] for query: "query{data:items(lang:en,gameMod..."
[11:47:01.9381626] > [Info]  Initializing tarkov tracker database
[11:47:01.9382274] > [Info]  Initializing hotkey manager...
[11:47:01.9403436] > [Info]  UI Ready!
[11:47:01.9403523] > [Info]  Initializing RatEye...
[11:47:03.2141841] > [Info]  Checking for updates...
[11:47:03.2150343] > [Info]  Loading resource "RSClientVersion"...
[11:47:03.2782294] > [Info]  Loading TarkovTracker data...
[11:47:03.2782422] > [Info]  Loading TarkovTracker...
[11:47:03.7144366] > [Info]  Setting up timer routines...
[11:47:03.7144609] > [Info]  Enabling hotkeys...
[11:47:03.7144997] > [Info]  Ready!
[11:52:03.7168826] > [Info]  Refreshing TarkovTracker DB...
[11:57:04.1086808] > [Info]  Refreshing TarkovTracker DB...
[12:02:04.4519208] > [Info]  Refreshing TarkovTracker DB...
[12:07:05.1047878] > [Info]  Refreshing TarkovTracker DB...
[12:12:05.4102187] > [Info]  Refreshing TarkovTracker DB...
[12:17:05.9024244] > [Info]  Refreshing TarkovTracker DB...
[12:22:06.2973313] > [Info]  Refreshing TarkovTracker DB...
[12:27:06.6577290] > [Info]  Refreshing TarkovTracker DB...
[12:32:07.0833042] > [Info]  Refreshing TarkovTracker DB...
[12:37:07.4823946] > [Info]  Refreshing TarkovTracker DB...
[12:42:07.8222481] > [Info]  Refreshing TarkovTracker DB...
[12:47:02.4428872] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[12:47:08.1803161] > [Info]  Refreshing TarkovTracker DB...
[12:47:09.3412489] > [Info]  Refreshed cache in 6898ms (409ms) [84ms] for query: "query{data:items(lang:en,gameMod..."
[12:52:08.5615158] > [Info]  Refreshing TarkovTracker DB...
[12:57:08.8732758] > [Info]  Refreshing TarkovTracker DB...
[13:02:09.2526492] > [Info]  Refreshing TarkovTracker DB...
[13:07:09.9470713] > [Info]  Refreshing TarkovTracker DB...
[13:12:10.3511286] > [Info]  Refreshing TarkovTracker DB...
[13:17:10.6478559] > [Info]  Refreshing TarkovTracker DB...
[13:22:10.9437010] > [Info]  Refreshing TarkovTracker DB...
[13:27:11.1564793] > [Info]  Refreshing TarkovTracker DB...
[13:32:12.0204178] > [Info]  Refreshing TarkovTracker DB...
[13:37:12.3634134] > [Info]  Refreshing TarkovTracker DB...
[13:42:12.7155968] > [Info]  Refreshing TarkovTracker DB
```
</details>

**Comment by Blightbuster** [comment]
Looks like you ran out of memory aka. not enough RAM.

**Comment by DysektAI** [comment]
Closing as a duplicate of https://github.com/RatScanner/RatScanner/issues/528.

This report shows the same `System.OutOfMemoryException` during name scan in `RatEye.Processing.Inspection.ScanTitle` (often via `Bitmap.Clone` / `Crop`, or related OpenCV allocation during multi-inspection). Issue #528 is the earliest open report with maintainer discussion and is being kept as the canonical tracker for this class of OOM reports.
