### ISSUE TITLE
Failed to allocate 49195528 bytes

### ISSUE THREAD

**Issue by salavatov** [RatScanner/RatScanner#686]
**Error**
Failed to allocate 49195528 bytes
```
OpenCvSharp.OpenCVException: Failed to allocate 49195528 bytes
   at OpenCvSharp.Internal.NativeMethods.imgproc_matchTemplate(IntPtr image, IntPtr templ, IntPtr result, Int32 method, IntPtr mask)
   at RatEye.Processing.MultiInspection.GetMarkerPositions(Bitmap marker)
   at RatEye.Processing.MultiInspection.SearchMarker()
   at RatScanner.RatScannerMain.NameScanScreen(Object _)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[18:12:59.5604924] > [Info]  ----- RatScanner 3.8.2 -----
[18:12:59.5616905] > [Info]  Screen Info: 3840x1600 at 100%
[18:12:59.5616971] > [Info]  Initializing TarkovDev API...
[18:12:59.5863378] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[18:12:59.5863412] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[18:12:59.5863454] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[18:13:00.0367963] > [Info]  Refreshed cache in 450ms (89ms) [6ms] for query: "query{data:hideoutStations(lang:..."
[18:13:00.2343995] > [Info]  Refreshed cache in 648ms (121ms) [3ms] for query: "query{data:tasks(lang:en,gameMod..."
[18:13:10.5553707] > [Info]  Refreshed cache in 10969ms (960ms) [74ms] for query: "query{data:items(lang:en,gameMod..."
[18:13:10.5573556] > [Info]  Initializing tarkov tracker database
[18:13:10.5574362] > [Info]  Initializing hotkey manager...
[18:13:10.5594913] > [Info]  UI Ready!
[18:13:10.5594994] > [Info]  Initializing RatEye...
[18:13:11.8546807] > [Info]  Checking for updates...
[18:13:11.8586103] > [Info]  Loading resource "RSClientVersion"...
[18:13:11.9313728] > [Info]  Loading TarkovTracker data...
[18:13:11.9313855] > [Info]  Loading TarkovTracker...
[18:13:12.3012005] > [Info]  Setting up timer routines...
[18:13:12.3012203] > [Info]  Enabling hotkeys...
[18:13:12.3012500] > [Info]  Ready!
[18:18:12.3162948] > [Info]  Refreshing TarkovTracker DB...
[18:23:12.5841396] > [Info]  Refreshing TarkovTracker DB...
[18:28:12.8186810] > [Info]  Refreshing TarkovTracker DB...
[18:33:13.1900259] > [Info]  Refreshing TarkovTracker DB...
[18:38:13.6209970] > [Info]  Refreshing TarkovTracker DB...
[18:43:14.2723644] > [Info]  Refreshing TarkovTracker DB...
[18:48:14.5846696] > [Info]  Refreshing TarkovTracker DB...
[18:53:14.9780881] > [Info]  Refreshing TarkovTracker DB...
[18:58:15.3792585] > [Info]  Refreshing TarkovTracker DB...
[19:03:15.6734132] > [Info]  Refreshing TarkovTracker DB...
[19:08:16.1322359] > [Info]  Refreshing TarkovTracker DB...
[19:13:16.7611586] > [Info]  Refreshing TarkovTracker DB...
[19:14:18.5243168] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[19:14:25.4740044] > [Info]  Refreshed cache in 6949ms (323ms) [49ms] for query: "query{data:items(lang:en,gameMod..."
[19:18:17.1601799] > [Info]  Refreshing TarkovTracker DB...
[19:23:17.4418398] > [Info]  Refreshing TarkovTracker DB...
[19:28:17.8653320] > [Info]  Refreshing TarkovTracker DB...
[19:33:18.1539882] > [Info]  Refreshing TarkovTracker DB...
[19:38:18.7325782] > [Info]  Refreshing TarkovTracker DB...
[19:43:19.0176307] > [Info]  Refreshing TarkovTracker DB...
[19:48:19.3448075] > [Info]  Refreshing TarkovTracker DB...
[19:53:19.6157076] > [Info]  Refreshing TarkovTracker DB...
[19:58:19.9958803] > [Info]  Refreshing TarkovTracker DB...
[20:03:20.2958792] > [Info]  Refreshing TarkovTracker DB...
[20:08:20.5916435] > [Info]  Refreshing TarkovTracker DB..
```
</details>

**Comment by DysektAI** [comment]
Closing as a duplicate of https://github.com/RatScanner/RatScanner/issues/528.

Same memory-pressure class during name scan: OpenCV `Failed to allocate` in multi-inspection, or GDI+ `Bitmap.Clone`/`Crop` in `Inspection.ScanTitle` (wording may differ from pure `OutOfMemoryException`). Canonical tracker is #528.
