### ISSUE TITLE
Out of memory.

### ISSUE THREAD

**Issue by ghiki** [RatScanner/RatScanner#688]
**Error**
Out of memory.
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   at RatEye.Extensions.Crop(Bitmap image, Int32 x, Int32 y, Int32 width, Int32 height, Boolean ignoreBounds)
   at RatEye.Processing.Inspection.ScanTitle()
   at RatEye.Processing.Inspection.SatisfyState(State targetState)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<OnNameScanHotkey>b__11_0()
   at RatScanner.HotkeyManager.Wrap(Action action)
```
<details>
<summary>Log</summary>

```
[14:49:45.0494653] > [Info]  ----- RatScanner 3.8.2 -----
[14:49:45.0524150] > [Info]  Screen Info: 1920x1080 at 100%
[14:49:45.0524247] > [Info]  Initializing TarkovDev API...
[14:49:45.1739478] > [Info]  Queueing request for query: "query{data:tasks(lang:es,gameMod..."
[14:49:45.1739545] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[14:49:45.1739686] > [Info]  Queueing request for query: "query{data:items(lang:es,gameMod..."
[14:49:48.5782708] > [Info]  Refreshed cache in 3403ms (147ms) [5ms] for query: "query{data:hideoutStations(lang:..."
[14:49:48.6828759] > [Info]  Refreshed cache in 3508ms (205ms) [5ms] for query: "query{data:tasks(lang:es,gameMod..."
[14:50:02.2222725] > [Info]  Refreshed cache in 17048ms (1135ms) [54ms] for query: "query{data:items(lang:es,gameMod..."
[14:50:02.2243158] > [Info]  Initializing tarkov tracker database
[14:50:02.2244118] > [Info]  Initializing hotkey manager...
[14:50:02.2275924] > [Info]  UI Ready!
[14:50:02.2276017] > [Info]  Initializing RatEye...
[14:50:03.5687368] > [Info]  Checking for updates...
[14:50:03.5698986] > [Info]  Loading resource "RSClientVersion"...
[14:50:04.9851649] > [Info]  Loading TarkovTracker data...
[14:50:04.9851822] > [Info]  Loading TarkovTracker...
[14:50:05.8821548] > [Info]  Setting up timer routines...
[14:50:05.8821804] > [Info]  Enabling hotkeys...
[14:50:05.8822182] > [Info]  Ready!
[14:54:38.4619330] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:54:38.4629296] > [Debug] NameScan:197 -> Name scanning at: (1557, 811)
[14:54:41.2229884] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:54:41.2231459] > [Debug] NameScan:197 -> Name scanning at: (1639, 105)
[14:55:05.8902854] > [Info]  Refreshing TarkovTracker DB...
[14:56:43.1896884] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:56:43.1898856] > [Debug] NameScan:197 -> Name scanning at: (1712, 1070)
[14:56:44.7336768] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:56:44.7338847] > [Debug] NameScan:197 -> Name scanning at: (558, 586)
[14:56:45.7897200] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:56:45.7899194] > [Debug] NameScan:197 -> Name scanning at: (553, 540)
[14:56:46.5336780] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:56:46.5338855] > [Debug] NameScan:197 -> Name scanning at: (514, 476)
[14:56:47.6136340] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:56:47.6138354] > [Debug] NameScan:197 -> Name scanning at: (1120, 812)
[14:56:53.0540974] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:56:53.0542705] > [Debug] NameScan:197 -> Name scanning at: (1391, 764)
[14:56:57.6854688] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:56:57.6856321] > [Debug] NameScan:197 -> Name scanning at: (577, 217)
[14:57:01.9734791] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:57:01.9736603] > [Debug] NameScan:197 -> Name scanning at: (1843, 1039)
[14:57:02.7654852] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:57:02.7656770] > [Debug] NameScan:197 -> Name scanning at: (863, 574)
[14:57:04.0374500] > [Debug] OnKeyUp:89 -> Pressed: Left
[14:57:04.0376286] > [
```
</details>

**Comment by wrenparismoe** [comment]
Same issue here.

**Comment by DysektAI** [comment]
Closing as a duplicate of https://github.com/RatScanner/RatScanner/issues/528.

This report shows the same `System.OutOfMemoryException` during name scan in `RatEye.Processing.Inspection.ScanTitle` (often via `Bitmap.Clone` / `Crop`, or related OpenCV allocation during multi-inspection). Issue #528 is the earliest open report with maintainer discussion and is being kept as the canonical tracker for this class of OOM reports.
