### ISSUE TITLE
Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by Vobeno** [RatScanner/RatScanner#689]
**Error**
Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding, RatScanner'. Path 'data.tasks[410].objectives[0].$type', line 1, position 807924.
 ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName(StructMultiKey`2 typeNameKey)
   at Newtonsoft.Json.Serialization.DefaultSerialization
```
<details>
<summary>Log</summary>

```
[09:35:58.8281019] > [Info]  ----- RatScanner 3.6.5 -----
[09:35:58.8546745] > [Info]  Screen Info: 2560x1440 at 100%
[09:35:58.8546891] > [Info]  Setting temporary default item...
[09:35:58.8849547] > [Info]  Initializing tarkov tracker database
[09:35:58.9012600] > [Info]  Initializing hotkey manager...
[09:35:58.9052982] > [Info]  UI Ready!
[09:35:59.9111244] > [Info]  Checking for updates...
[09:35:59.9127715] > [Info]  Loading resource "RSClientVersion"...
[09:36:00.6879325] > [Info]  A new version is available: 3.8.2
[09:36:00.6879489] > [Info]  Loading resource "RSClientForceUpdateVersions"...
[09:36:02.8740755] > [Error] Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding, RatScanner'. Path 'data.tasks[410].objectives[0].$type', line 1, position 807924.
 ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'RatScanner.FetchModels.TarkovDev.TaskObjectiveTraderStanding' in assembly 'RatScanner, Version=3.6.5.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName(StructMultiKey`2 typeNameKey)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   
```
</details>

**Comment by Blightbuster** [comment]
Please update ratscanner to fix the issue.
