### ISSUE TITLE
Unhandled exception in RatScanner 2.5.1

### ISSUE THREAD

**Issue by PISTOLCUPCAKES** [RatScanner/RatScanner#69]
**Error**
Unhandled exception in RatScanner 2.5.1
```
System.ArgumentException: Lock was not correctly acquired / released.
   at RatScanner.RatScannerMain.set_ScanLock(Boolean value)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
<details>
<summary>Log</summary>

```
[01:57:07.4560166] > [Info]  ----- RatScanner 2.5.1 -----
[01:57:07.4579769] > [Info]  Starting RatScanner...
[01:57:07.4581836] > [Info]  Loading config...
[01:57:07.4862679] > [Info]  Loading price data...
[01:57:08.2443814] > [Info]  Setting default item...
[01:57:08.2542039] > [Info]  Initializing name scan...
[01:57:08.2544638] > [Info]  Loading OCR data...
[01:57:08.3723434] > [Info]  Initializing icon scan...
[01:57:08.3739500] > [Info]  Loading static icons...
[01:57:08.6474077] > [Info]  Loaded 1197/1197 icons successfully.
[01:57:08.6495372] > [Info]  Loading static correlation data...
[01:57:08.6749709] > [Info]  Loading dynamic correlation data...
[01:57:08.7865517] > [Info]  Loading dynamic icons...
[01:57:09.3772190] > [Info]  Loaded 3171/3171 icons successfully.
[01:57:09.3887550] > [Info]  Initializing file watcher for icon cache...
[01:57:09.3921186] > [Info]  Prewarming name tool tip...
[01:57:09.5297119] > [Info]  Prewarming icon tool tip...
[01:57:09.5972143] > [Info]  Initializing hotkey manager...
[01:57:09.6003027] > [Info]  Checking for new updates...
[01:57:09.6018226] > [Info]  Loading resource "RSClientVersion"...
[01:57:09.7676077] > [Info]  Ready!
[01:57:09.8042935] > [Info]  Loading resource "RSPatreon"...
[01:57:09.9678539] > [Info]  Loading resource "RSDiscord"...
[01:57:10.1220976] > [Info]  Loading resource "RSGithub"...
[01:58:11.1102840] > [Info]  Loading dynamic correlation data...
[01:58:11.1836687] > [Info]  Loading dynamic icons...
[01:58:11.5868367] > [Info]  Loaded 3172/3172 icons successfully.
[01:58:11.5914152] > [Info]  Loading dynamic correlation data...
[01:58:11.5941986] > [Info]  Dynamic correlation data already up to date
[01:58:11.5942561] > [Info]  Loading dynamic correlation data...
[01:58:11.5985443] > [Info]  Dynamic correlation data already up to date
[02:00:04.8445895] > [Warning] Could not find icon key for:
Uid: 5beec1bd0db834001e6006f3
[02:01:31.9638067] > [Warning] Could not find icon key for:
Uid: 5b432d215acfc4771e1c6624
[02:04:42.1225348] > [Info]  Loading dynamic correlation data...
[02:04:42.1868262] > [Info]  Loading dynamic icons...
[02:04:42.5484187] > [Info]  Loaded 3173/3173 icons successfully.
[02:04:42.5565966] > [Info]  Loading dynamic correlation data...
[02:04:42.5602077] > [Info]  Dynamic correlation data already up to date
[02:04:42.5602722] > [Info]  Loading dynamic correlation data...
[02:04:42.5642708] > [Info]  Dynamic correlation data already up to date
[02:04:42.5643262] > [Info]  Loading dynamic correlation data...
[02:04:42.5682357] > [Info]  Dynamic correlation data already up to date
[02:13:14.4361190] > [Info]  Loading dynamic correlation data...
[02:13:14.5201694] > [Info]  Loading dynamic icons...
[02:13:14.8792668] > [Info]  Loaded 3174/3174 icons successfully.
[02:13:14.8829171] > [Info]  Loading dynamic correlation data...
[02:13:14.8893732] > [Info]  Dynamic correlation data already up to date
[02:13:14.8894339] > [Info]  Loading dynamic correlation dat
```
</details>

**Comment by PISTOLCUPCAKES** [comment]
Duplicate of Issue 68
