### ISSUE TITLE
Loading of resource "RSClientVersion" failed.

### ISSUE THREAD

**Issue by Favoritexxx** [RatScanner/RatScanner#690]
**Error**
Loading of resource "RSClientVersion" failed.
```
System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetString(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
```
<details>
<summary>Log</summary>

```
[10:33:23.3766689] > [Info]  ----- RatScanner 3.8.2 -----
[10:33:23.3775957] > [Info]  Screen Info: 2560x1440 at 100%
[10:33:23.3776025] > [Info]  Initializing TarkovDev API...
[10:33:23.3934160] > [Info]  Queueing request for query: "query{data:items(lang:ru,gameMod..."
[10:33:23.3934193] > [Info]  Queueing request for query: "query{data:tasks(lang:ru,gameMod..."
[10:33:23.3934209] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[10:33:27.0019791] > [Info]  Refreshed cache in 3608ms (173ms) [8ms] for query: "query{data:tasks(lang:ru,gameMod..."
[10:33:27.0690704] > [Info]  Refreshed cache in 3675ms (44ms) [3ms] for query: "query{data:hideoutStations(lang:..."
[10:33:32.8745810] > [Info]  Refreshed cache in 9481ms (935ms) [138ms] for query: "query{data:items(lang:ru,gameMod..."
[10:33:32.8765632] > [Info]  Initializing tarkov tracker database
[10:33:32.8766267] > [Info]  Initializing hotkey manager...
[10:33:32.8785130] > [Info]  UI Ready!
[10:33:32.8785212] > [Info]  Initializing RatEye...
[10:33:34.1445125] > [Info]  Checking for updates...
[10:33:34.1453296] > [Info]  Loading resource "RSClientVersion"...
[10:33:34.4821524] > [Error] Loading of resource "RSClientVersion" failed.
 -------------------- 
 System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at RatScanner.ApiManager.GetString(String url, String bearerToken)
   at RatScanner.ApiManager.GetResource(ResourceType resource)
[13:58:37.0761367] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Cant reproduce it right now, does the issue still persist if you try it right now?
