### ISSUE TITLE
No such host is known.

### ISSUE THREAD

**Issue by salavatov** [RatScanner/RatScanner#691]
**Error**
No such host is known.
```
System.AggregateException: One or more errors occurred. (No such host is known. (tarkovtracker.io:443))
 ---> System.Net.Http.HttpRequestException: No such host is known. (tarkovtracker.io:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHos
```
<details>
<summary>Log</summary>

```
[21:58:32.1254036] > [Info]  ----- RatScanner 3.8.2 -----
[21:58:32.1262770] > [Info]  Screen Info: 3840x1600 at 100%
[21:58:32.1262833] > [Info]  Initializing TarkovDev API...
[21:58:32.1421676] > [Info]  Queueing request for query: "query{data:tasks(lang:en,gameMod..."
[21:58:32.1421709] > [Info]  Queueing request for query: "query{data:items(lang:en,gameMod..."
[21:58:32.1421737] > [Info]  Queueing request for query: "query{data:hideoutStations(lang:..."
[21:58:32.3697555] > [Info]  Refreshed cache in 227ms (86ms) [3ms] for query: "query{data:hideoutStations(lang:..."
[21:58:32.4403082] > [Info]  Refreshed cache in 298ms (153ms) [8ms] for query: "query{data:tasks(lang:en,gameMod..."
[21:58:38.5841176] > [Info]  Refreshed cache in 6441ms (1050ms) [67ms] for query: "query{data:items(lang:en,gameMod..."
[21:58:38.5857157] > [Info]  Initializing tarkov tracker database
[21:58:38.5857937] > [Info]  Initializing hotkey manager...
[21:58:38.5880388] > [Info]  UI Ready!
[21:58:38.5880500] > [Info]  Initializing RatEye...
[21:58:40.4940215] > [Info]  Checking for updates...
[21:58:40.4949993] > [Info]  Loading resource "RSClientVersion"...
[21:58:40.5624841] > [Info]  Loading TarkovTracker data...
[21:58:40.5625008] > [Info]  Loading TarkovTracker...
[21:58:40.9558132] > [Info]  Setting up timer routines...
[21:58:40.9558347] > [Info]  Enabling hotkeys...
[21:58:40.9558675] > [Info]  Ready!
[22:03:40.9670214] > [Info]  Refreshing TarkovTracker DB...
[22:08:41.3721001] > [Info]  Refreshing TarkovTracker DB...
[22:13:41.7755469] > [Info]  Refreshing TarkovTracker DB...
[22:18:42.0702090] > [Info]  Refreshing TarkovTracker DB...
[22:23:42.3610150] > [Info]  Refreshing TarkovTracker DB...
[22:28:42.6784528] > [Info]  Refreshing TarkovTracker DB...
[22:33:43.0411197] > [Info]  Refreshing TarkovTracker DB...
[22:38:43.3848074] > [Info]  Refreshing TarkovTracker DB...
[22:43:43.7537580] > [Info]  Refreshing TarkovTracker DB...
[22:48:44.0851712] > [Info]  Refreshing TarkovTracker DB...
[22:53:44.4799126] > [Info]  Refreshing TarkovTracker DB...
[22:58:44.7736215] > [Info]  Refreshing TarkovTracker DB...
[23:03:45.0584472] > [Info]  Refreshing TarkovTracker DB...
[23:08:45.3942777] > [Info]  Refreshing TarkovTracker DB...
[23:13:45.7693803] > [Info]  Refreshing TarkovTracker DB...
[23:18:46.0619412] > [Info]  Refreshing TarkovTracker DB...
[23:23:46.3726233] > [Info]  Refreshing TarkovTracker DB...
[23:28:46.7664960] > [Info]  Refreshing TarkovTracker DB...
[23:33:47.1548086] > [Info]  Refreshing TarkovTracker DB...
[23:38:47.5622817] > [Info]  Refreshing TarkovTracker DB...
[23:43:47.8251564] > [Info]  Refreshing TarkovTracker DB...
[23:48:48.1878274] > [Info]  Refreshing TarkovTracker DB...
[23:53:48.4611600] > [Info]  Refreshing TarkovTracker DB...
[23:58:48.8573736] > [Info]  Refreshing TarkovTracker DB...
[00:03:49.1719053] > [Info]  Refreshing TarkovTracker DB...
[00:08:49.5684089] > [Info]  Refreshing TarkovTracker DB...
[00:13:49.9975225] > [Info]  Ref
```
</details>

**Comment by Blightbuster** [comment]
looks like you may have lost your internet connection?

**Comment by DysektAI** [comment]
Closing as a duplicate of https://github.com/RatScanner/RatScanner/issues/519.

Same DNS failure resolving TarkovTracker host (`No such host is known` / `Der angegebene Host ist unbekannt` for tarkovtracker.io/org). Transient connectivity / DNS / firewall; #519 is the earliest open report with maintainer discussion.
