### ISSUE TITLE
A task was canceled.

### ISSUE THREAD

**Issue by louisboswell** [RatScanner/RatScanner#71]
**Error**
A task was canceled.
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.<>c.<OnNameScanHotkey>b__7_0()
   at RatScanner.HotkeyManager.Wrap[T](Func`1 func)
```
<details>
<summary>Log</summary>

```
[21:41:33.2141580] > [Info]  ----- RatScanner 2.5.2 -----
[21:41:33.2150153] > [Info]  Starting RatScanner...
[21:41:33.2150786] > [Info]  Loading config...
[21:41:33.2315770] > [Info]  Loading price data...
[21:41:33.6238612] > [Info]  Initializing icon scan...
[21:41:33.6376597] > [Info]  Loading static icons...
[21:41:34.2337352] > [Info]  Setting default item...
[21:41:34.2391696] > [Info]  Initializing name scan...
[21:41:34.2393859] > [Info]  Loading OCR data...
[21:41:34.3283499] > [Info]  Initializing icon scan...
[21:41:34.3295296] > [Info]  Loading static icons...
[21:41:35.3986847] > [Info]  Loaded 1197/1197 icons successfully.
[21:41:35.4009626] > [Info]  Loading static correlation data...
[21:41:35.4379736] > [Info]  Loading dynamic correlation data...
[21:41:35.4743354] > [Info]  Loading dynamic icons...
[21:41:35.5094425] > [Error] Unhandled exception in RatScanner 2.5.2
 -------------------- 
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The process cannot access the file 'D:\Downloads\RatScanner\Log.txt' because it is being used by another process.)
 ---> System.IO.IOException: The process cannot access the file 'D:\Downloads\RatScanner\Log.txt' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.AppendAllText(String path, String contents, Encoding encoding)
   at RatScanner.Logger.ProcessBacklog()
   at RatScanner.Logger.<>c.<AppendToLog>b__11_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
[21:41:37.0583666] > [Info]  Loaded 1548/1548 icons successfully.
[21:41:37.0612964] > [Info]  Initializing file watcher for icon cache...
[21:41:37.0640171] > [Info]  Prewarming name tool tip...
[21:41:37.1437234] > [Inf
```
</details>

**Comment by Blightbuster** [comment]
Why did you close this issue? Did you provoke the exception somehow?
