### ISSUE TITLE
Unhandled exception in RatScanner 2.5.2

### ISSUE THREAD

**Issue by RulesBrooklyn** [RatScanner/RatScanner#74]
After I installed the new version. I tried to open the program withouts Admin Rights and this happened.

**Error**
Unhandled exception in RatScanner 2.5.2
```
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\RatScanner\Log.txt' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at RatScanner.Logger.Clear()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoW
```
<details>
<summary>Log</summary>

```
[15:17:32.3844079] > [Info]  ----- RatScanner 2.5.2 -----
[15:17:32.3851019] > [Info]  Starting RatScanner...
[15:17:32.3851581] > [Info]  Loading config...
[15:17:32.4005024] > [Info]  Loading price data...
[15:17:33.3807850] > [Info]  Setting default item...
[15:17:33.3856573] > [Info]  Initializing name scan...
[15:17:33.3858261] > [Info]  Loading OCR data...
[15:17:33.4720555] > [Info]  Initializing icon scan...
[15:17:33.4735316] > [Info]  Loading static icons...
[15:17:33.5742359] > [Info]  Loaded 1197/1197 icons successfully.
[15:17:33.5763170] > [Info]  Loading static correlation data...
[15:17:33.5887970] > [Info]  Loading dynamic correlation data...
[15:17:33.5969536] > [Info]  Loading dynamic icons...
[15:17:33.6236684] > [Info]  Loaded 230/230 icons successfully.
[15:17:33.6244462] > [Info]  Initializing file watcher for icon cache...
[15:17:33.6262300] > [Info]  Prewarming name tool tip...
[15:17:33.6637674] > [Info]  Prewarming icon tool tip...
[15:17:33.6833197] > [Info]  Initializing hotkey manager...
[15:17:33.6851132] > [Info]  Checking for new updates...
[15:17:33.6861492] > [Info]  Loading resource "RSClientVersion"...
[15:17:34.0162264] > [Info]  Ready!
[15:17:34.0437637] > [Info]  Loading resource "RSPatreon"...
[15:17:34.3669457] > [Info]  Loading resource "RSDiscord"...
[15:17:34.7062527] > [Info]  Loading resource "RSGithub"...

```
</details>

**Comment by Sleaker** [comment]
@RulesBrooklyn - if you've ever opened the program in AdminMode then it'll create files with administrator priveleges and you wont be able to open the program again as a normal user. This is pretty standard behaviour for slimline apps like this.

Workaround for now: delete the Log.txt file that it's complaining about as an administrator.

**Comment by Blightbuster** [comment]
This is indeed a issue with access rights to the `Program Files` folder. Either move rat scanner to another (non protected) folder or start it as admin.
