### ISSUE TITLE
Loading of DB failed.System.Net.WebException: The remote server returned an error: (500) Internal Server Error.   at System.Net.HttpWebRequest.GetResponse()   at System.Net.WebClient.GetWebResponse(WebRequest request)   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)   at System.Net.WebClient.DownloadData(Uri address)   at System.Net.WebClient.DownloadData(String address)   at RatScanner.ApiManager.GetMarketDB(Language language)

### ISSUE THREAD

**Issue by seanjwaters** [RatScanner/RatScanner#82]
**Error**
Loading of DB failed.
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at RatScanner.ApiManager.GetMarketDB(Language language)
<details>
<summary>Log</summary>

```
[20:23:02.3224256] > [Info]  ----- RatScanner 2.5.2 -----
[20:23:02.3231380] > [Info]  Starting RatScanner...
[20:23:02.3232023] > [Info]  Loading config...
[20:23:02.3366481] > [Info]  Loading price data...
[20:23:02.6632909] > [Error] Loading of DB failed.
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at RatScanner.ApiManager.GetMarketDB(Language language)
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.ApiManager.GetMarketDB(Language language)
   at RatScanner.MarketDB.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvoke
```
</details>

**Comment by Blightbuster** [comment]
I'll fix the old backend to return a blank 200 response. It should then prompt you to automatically update to the latest version.

**Comment by seanjwaters** [comment]
> 
> 
> I'll fix the old backend to return a blank 200 response. It should then prompt you to automatically update to the latest version.

Appreciate it.

**Comment by seanjwaters** [comment]
> 
> 
> update to the most recent version

Opening RatScanner immediately prompts that error, which then forces me to close RatScanner.

**Comment by Blightbuster** [comment]
Backend now serves some blank data to prevent the crash of pre 2.6.x clients.

![image](https://user-images.githubusercontent.com/24388294/117373748-27400300-aecc-11eb-86c9-ddf277064f7c.png)
