### ISSUE TITLE
Downloading of file "https://gist.githubusercontent.com/jannik4/d132bb89a51bf4e1508c9e4341ce7d6c/raw/1a39ce3d9a2a2ee2446c7d82e9aefa88fbfe815b/items.json" failed.

### ISSUE THREAD

**Issue by oSAVAGEx** [RatScanner/RatScanner#88]
**Error**
Downloading of file "https://gist.githubusercontent.com/jannik4/d132bb89a51bf4e1508c9e4341ce7d6c/raw/1a39ce3d9a2a2ee2446c7d82e9aefa88fbfe815b/items.json" failed.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\FireS\OneDrive\Desktop\Data\Data\items.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
```
<details>
<summary>Log</summary>

```
[19:58:19.7616192] > [Info]  ----- RatScanner 2.6.1 -----
[19:58:19.7625218] > [Info]  Starting RatScanner...
[19:58:19.7625785] > [Info]  Loading config...
[19:58:19.7793370] > [Info]  Loading item data...
[19:58:19.7876813] > [Info]  Loading resource "RSItemDataLink"...
[19:58:20.9422191] > [Info]  Downloading file "https://gist.githubusercontent.com/jannik4/d132bb89a51bf4e1508c9e4341ce7d6c/raw/1a39ce3d9a2a2ee2446c7d82e9aefa88fbfe815b/items.json"...
[19:58:42.7568300] > [Error] Downloading of file "https://gist.githubusercontent.com/jannik4/d132bb89a51bf4e1508c9e4341ce7d6c/raw/1a39ce3d9a2a2ee2446c7d82e9aefa88fbfe815b/items.json" failed.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\FireS\OneDrive\Desktop\Data\Data\items.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
[19:58:48.2647191] > [Info]  Loading resource "RSFAQLink"...

```
</details>

**Comment by Blightbuster** [comment]
Hey, it looks like this issues is caused by having the Rat Scanner folder in a OneDrive folder.
As you can see in the exception message, your desktop folder is within the OneDrive.

To fix this, simply move the Rat Scanner folder into a different location which is not inside OneDrive.

**Comment by Blightbuster** [comment]
Please comment if this issue persists and I will reopen the issue.
