### ISSUE TITLE
System.Drawing.Graphics.CopyFromScreen - The handle is invalid.

### ISSUE THREAD

**Issue by gunstarpl** [RatScanner/RatScanner#89]
**Error**
The handle is invalid.
```
System.ComponentModel.Win32Exception (6): The handle is invalid.
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at RatScanner.RatScannerMain.GetScreenshot(Vector2 vector2, Size size)
   at RatScanner.RatScannerMain.NameScan(Vector2 position)
   at RatScanner.HotkeyManager.Wrap[T](Func`1 func)
```
<details>
<summary>Log</summary>

```
[10:49:08.0100373] > [Info]  ----- RatScanner 2.6.1 -----
[10:49:08.0112380] > [Info]  Starting RatScanner...
[10:49:08.0112833] > [Info]  Loading config...
[10:49:08.0318543] > [Info]  Loading item data...
[10:49:08.5519775] > [Info]  Loading resource "RSItemDataLink"...
[10:49:09.2849644] > [Info]  Downloading file "https://gist.githubusercontent.com/jannik4/d132bb89a51bf4e1508c9e4341ce7d6c/raw/1a39ce3d9a2a2ee2446c7d82e9aefa88fbfe815b/items.json"...
[10:49:12.4081962] > [Info]  Loading price data...
[10:49:13.1805003] > [Info]  Setting default item...
[10:49:13.1809481] > [Info]  Initializing name scan...
[10:49:13.1811762] > [Info]  Loading OCR data...
[10:49:14.0235239] > [Info]  Initializing icon scan...
[10:49:14.0251320] > [Info]  Loading static icons...
[10:49:16.0689742] > [Info]  Loaded 1197/1197 icons successfully.
[10:49:16.0699092] > [Info]  Loading static correlation data...
[10:49:16.0853459] > [Info]  Loading dynamic correlation data...
[10:49:16.1086442] > [Info]  Loading dynamic icons...
[10:49:16.3037467] > [Info]  Loaded 1609/1609 icons successfully.
[10:49:16.3050071] > [Info]  Initializing file watcher for icon cache...
[10:49:16.3076034] > [Info]  Prewarming name tool tip...
[10:49:16.3652374] > [Info]  Prewarming icon tool tip...
[10:49:16.3856232] > [Info]  Initializing hotkey manager...
[10:49:16.3874230] > [Info]  Checking for new updates...
[10:49:16.3875939] > [Info]  Loading resource "RSClientVersion"...
[10:49:16.7681866] > [Info]  Ready!
[10:49:16.8000058] > [Info]  Loading resource "RSPatreonLink"...
[10:49:17.1779334] > [Info]  Loading resource "RSDiscordLink"...
[10:49:17.5502165] > [Info]  Loading resource "RSGithubLink"...
[11:16:17.2079849] > [Info]  Loading dynamic correlation data...
[11:16:17.2261721] > [Info]  Loading dynamic icons...
[11:16:17.3664591] > [Info]  Loaded 1610/1610 icons successfully.
[11:16:17.3680758] > [Info]  Loading dynamic correlation data...
[11:16:17.3838600] > [Info]  Loading dynamic icons...
[11:16:17.4829370] > [Info]  Loaded 1612/1612 icons successfully.
[11:16:17.4840880] > [Info]  Loading dynamic correlation data...
[11:16:17.4846737] > [Info]  Dynamic correlation data already up to date
[11:16:17.4846958] > [Info]  Loading dynamic correlation data...
[11:16:17.4852956] > [Info]  Dynamic correlation data already up to date
[11:16:17.4853349] > [Info]  Loading dynamic correlation data...
[11:16:17.4859463] > [Info]  Dynamic correlation data already up to date
[11:16:17.4859786] > [Info]  Loading dynamic correlation data...
[11:16:17.4865165] > [Info]  Dynamic correlation data already up to date
[11:16:17.4865693] > [Info]  Loading dynamic correlation data...
[11:16:17.4872049] > [Info]  Dynamic correlation data already up to date
[11:16:17.4872341] > [Info]  Loading dynamic correlation data...
[11:16:17.4878359] > [Info]  Dynamic correlation data already up to date
[11:16:23.4714908] > [Info]  Loading dynamic correlation data...
[11:16:23.4903175] > [Info]  Loading dynamic icon
```
</details>

This seems to happen with 100% repro rate after restoring PC from hibernation while app is open.

**Comment by Blightbuster** [comment]
Fixed in next release.
Thanks for reporting ❤️
