### ISSUE TITLE
Unhandled exception in RatScanner 2.6.1 (Only happens with ratchet wrench) 

### ISSUE THREAD

**Issue by LeopoldoMoreno** [RatScanner/RatScanner#96]
**Error**
Unhandled exception in RatScanner 2.6.1
```
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at RatScanner.View.MainMenu.HyperlinkRequestNavigate(Object sender, RequestNavigateEventArgs e)
   at System.Windows.Navigation.RequestNavigateEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Documents.Hyperlink.NavigateToUri(IInputElement sourceElement, Uri targetUri, String targetWindow)
   at System.Windows
```
<details>
<summary>Log</summary>

```
[23:25:45.7139077] > [Info]  ----- RatScanner 2.6.1 -----
[23:25:45.7148332] > [Info]  Starting RatScanner...
[23:25:45.7149012] > [Info]  Loading config...
[23:25:45.7340525] > [Info]  Loading item data...
[23:25:45.7415862] > [Info]  Loading resource "RSItemDataLink"...
[23:25:46.3646686] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[23:25:49.3257938] > [Info]  Loading price data...
[23:25:49.7105740] > [Info]  Setting default item...
[23:25:49.7109320] > [Info]  Initializing name scan...
[23:25:49.7111612] > [Info]  Loading OCR data...
[23:25:49.7837419] > [Info]  Initializing icon scan...
[23:25:49.7845870] > [Info]  Loading static icons...
[23:25:49.8732437] > [Info]  Loaded 1197/1197 icons successfully.
[23:25:49.8757198] > [Info]  Loading static correlation data...
[23:25:49.8836077] > [Info]  Loading dynamic correlation data...
[23:25:49.8977371] > [Info]  Loading dynamic icons...
[23:25:50.0059071] > [Info]  Loaded 1299/1299 icons successfully.
[23:25:50.0078888] > [Info]  Initializing file watcher for icon cache...
[23:25:50.0115253] > [Info]  Prewarming name tool tip...
[23:25:50.0641097] > [Info]  Prewarming icon tool tip...
[23:25:50.0907896] > [Info]  Initializing hotkey manager...
[23:25:50.0927739] > [Info]  Checking for new updates...
[23:25:50.0929682] > [Info]  Loading resource "RSClientVersion"...
[23:25:50.4628131] > [Info]  Ready!
[23:25:50.4915605] > [Info]  Loading resource "RSPatreonLink"...
[23:25:50.7004275] > [Info]  Loading resource "RSDiscordLink"...
[23:25:50.8599483] > [Info]  Loading resource "RSGithubLink"...
[23:25:56.8189715] > [Error] Unhandled exception in RatScanner 2.6.1
 -------------------- 
 System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at RatScanner.View.MainMenu.HyperlinkRequestNavigate(Object sender, RequestNavigateEventArgs e)
   at System.Windows.Navigation.RequestNavigateEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Documents.Hyperlink.NavigateToUri(IInputElement sourceElement, Uri targetUri, String targetWindow)
   at System.Windows.Documents.Hyperlink.DoNavigation(Object sender)
   at System.Windows.Documents.Hyperlink.OnClick()
   at System.Windows.Documents.Hyperlink.DispatchNavigation(Object sender)
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System
```
</details>

**Comment by Blightbuster** [comment]
I assume it crashes when clicking the wiki link?

**Comment by LeopoldoMoreno** [comment]
Correct.

**Comment by FriedEngineer** [comment]
same hitting the wiki link for Thermite:

System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at RatScanner.View.MainMenu.HyperlinkRequestNavigate(Object sender, RequestNavigateEventArgs e)
   at System.Windows.Navigation.RequestNavigateEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Documents.Hyperlink.NavigateToUri(IInputElement sourceElement, Uri targetUri, String targetWindow)
   at System.Windows.Documents.Hyperlink.DoNavigation(Object sender)
   at System.Wind
