### ISSUE TITLE
Could not find dynamic correlation data at: C:\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by ugrolol** [RatScanner/RatScanner#98]
**Error**
Could not find dynamic correlation data at: C:\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[18:00:13.5854795] > [Info]  ----- RatScanner 2.7.0 -----
[18:00:13.5895779] > [Info]  Starting RatScanner...
[18:00:13.5901509] > [Info]  Loading config...
[18:00:13.6152623] > [Info]  Loading item data...
[18:00:13.6220446] > [Info]  Loading resource "RSItemDataVersion"...
[18:00:16.5657578] > [Info]  Loading TarkovTracker...
[18:00:17.6570926] > [Info]  Loading progress data...
[18:00:18.1035332] > [Info]  Loading price data...
[18:00:18.9207972] > [Info]  Setting default item...
[18:00:18.9212165] > [Info]  Initializing name scan...
[18:00:18.9214242] > [Info]  Loading OCR data...
[18:00:19.0049981] > [Info]  Initializing icon scan...
[18:00:19.0057583] > [Info]  Loading static icons...
[18:00:19.1569210] > [Info]  Loaded 1197/1197 icons successfully.
[18:00:19.1577858] > [Info]  Loading static correlation data...
[18:00:19.1645531] > [Info]  Loading dynamic correlation data...
[18:00:19.1759357] > [Error] Could not find dynamic correlation data at: C:\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnOpen()
   at RatScanner.PageSwitcher.Navigate(UserControl nextControl, Object state)
   at RatScanner.PageSwitcher..ctor()
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateIns
```
</details>

**Comment by Blightbuster** [comment]
Hey, please have a look [here](https://github.com/RatScanner/RatScanner/blob/master/FAQ.md#could-not-find-dynamic-correlation-data-at-).
