### ISSUE TITLE
Could not find dynamic correlation data at: C:\Users\birge\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json

### ISSUE THREAD

**Issue by Birgerev** [RatScanner/RatScanner#99]
**Error**
Could not find dynamic correlation data at: C:\Users\birge\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
<details>
<summary>Log</summary>

```
[10:29:02.5624816] > [Info]  ----- RatScanner 2.6.1 -----
[10:29:02.5631660] > [Info]  Starting RatScanner...
[10:29:02.5632309] > [Info]  Loading config...
[10:29:02.5828620] > [Info]  Loading item data...
[10:29:02.5894157] > [Info]  Loading resource "RSItemDataLink"...
[10:29:03.1423504] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[10:29:14.3759177] > [Info]  Loading price data...
[10:29:15.0136787] > [Info]  Setting default item...
[10:29:15.0141081] > [Info]  Initializing name scan...
[10:29:15.0143772] > [Info]  Loading OCR data...
[10:29:15.0864925] > [Info]  Initializing icon scan...
[10:29:15.0877123] > [Info]  Loading static icons...
[10:29:15.1997367] > [Info]  Loaded 1197/1197 icons successfully.
[10:29:15.2006689] > [Info]  Loading static correlation data...
[10:29:15.2113764] > [Info]  Loading dynamic correlation data...
[10:29:15.2247170] > [Error] Could not find dynamic correlation data at: C:\Users\birge\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at RatScanner.IconManager.Init()
   at RatScanner.Scan.ItemIconScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu.OnLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr 
```
</details>

**Comment by Birgerev** [comment]
Happend on an older version though, might not be valid

**Comment by Birgerev** [comment]
Problem did not persist on the newest version (v2.7.0), closing issue
